// Code generated by weaver. DO NOT EDIT.

// Package myappevent is the Go form of the events named `myapp.*`.
//
// Each event and event refinement has an Emit function that emits it as a
// log record through a myapplogger.Logger, under the event's name and with
// no body. Required attributes are typed parameters, and the rest, the
// severity, and the timestamp are trailing options. A record the logger is
// not enabled for is never emitted. Identifiers omit the namespace prefix
// `myapp.`, because the package name already carries it.
package myappevent
