// Code generated by weaver. DO NOT EDIT.

package myappevent

import (
	"context"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/log"

	"example.com/myapplogger"
	"example.com/upstream/errorattr"
)

// TaskErroredOption sets an attribute, the severity, or the timestamp of an
// event EmitTaskErrored emits.
type TaskErroredOption interface {
	taskErroredOption(record *log.Record)
}

type taskErroredEventSeverity struct{ v log.Severity }

func (o taskErroredEventSeverity) taskErroredOption(record *log.Record) {
	record.SetSeverity(o.v)
}

// WithTaskErroredSeverity sets the severity of the event, in place of
// log.SeverityInfo.
func WithTaskErroredSeverity(severity log.Severity) TaskErroredOption {
	return taskErroredEventSeverity{v: severity}
}

type taskErroredEventTimestamp struct{ v time.Time }

func (o taskErroredEventTimestamp) taskErroredOption(record *log.Record) {
	record.SetTimestamp(o.v)
}

// WithTaskErroredTimestamp sets the time the event occurred. Without it the
// event carries only the time it was observed.
func WithTaskErroredTimestamp(timestamp time.Time) TaskErroredOption {
	return taskErroredEventTimestamp{v: timestamp}
}

type taskErroredEventServerPort struct{ v int }

func (o taskErroredEventServerPort) taskErroredOption(record *log.Record) {
	record.AddAttributes(attribute.Int("server.port", o.v))
}

// WithTaskErroredServerPort sets `server.port` on the event.
func WithTaskErroredServerPort(v int) TaskErroredOption {
	return taskErroredEventServerPort{v: v}
}

// EmitTaskErrored emits the `myapp.task.errored` event through logger. It is
// skipped when logger is not enabled for it, and the zero logger emits
// nothing.
//
// A task failed with an error.
func EmitTaskErrored(ctx context.Context, logger myapplogger.Logger, errorType errorattr.TypeAttr, opts ...TaskErroredOption) {
	var record log.Record
	record.SetEventName("myapp.task.errored")
	record.SetSeverity(log.SeverityInfo)
	record.AddAttributes(
		errorType.KeyValue(),
	)
	for _, opt := range opts {
		opt.taskErroredOption(&record)
	}
	if !logger.LogLogger().Enabled(ctx, log.EnabledParameters{Severity: record.Severity(), EventName: record.EventName()}) {
		return
	}
	logger.LogLogger().Emit(ctx, record)
}
