// Code generated by weaver. DO NOT EDIT.

package workerevent

import (
	"context"
	"time"

	"go.opentelemetry.io/otel/log"

	"example.com/semconv/myappattr"
	"example.com/semconv/semconvlogger"
	"example.com/semconv/workerattr"
)

// HostStartedOption sets an attribute, the severity, or the timestamp of an
// event EmitHostStarted emits.
type HostStartedOption interface {
	hostStartedOption(record *log.Record)
}

type hostStartedEventSeverity struct{ v log.Severity }

func (o hostStartedEventSeverity) hostStartedOption(record *log.Record) {
	record.SetSeverity(o.v)
}

// WithHostStartedSeverity sets the severity of the event, in place of
// log.SeverityInfo.
func WithHostStartedSeverity(severity log.Severity) HostStartedOption {
	return hostStartedEventSeverity{v: severity}
}

type hostStartedEventTimestamp struct{ v time.Time }

func (o hostStartedEventTimestamp) hostStartedOption(record *log.Record) {
	record.SetTimestamp(o.v)
}

// WithHostStartedTimestamp sets the time the event occurred. Without it the
// event carries only the time it was observed.
func WithHostStartedTimestamp(timestamp time.Time) HostStartedOption {
	return hostStartedEventTimestamp{v: timestamp}
}

// EmitHostStarted emits the `worker.host.started` event through logger. It
// is skipped when logger is not enabled for it, and the zero logger emits
// nothing.
//
// A worker host started taking tasks.
func EmitHostStarted(ctx context.Context, logger semconvlogger.Logger, opts ...HostStartedOption) {
	var record log.Record
	record.SetEventName("worker.host.started")
	record.SetSeverity(log.SeverityInfo)
	for _, opt := range opts {
		opt.hostStartedOption(&record)
	}
	if !logger.LogLogger().Enabled(ctx, log.EnabledParameters{Severity: record.Severity(), EventName: record.EventName()}) {
		return
	}
	logger.LogLogger().Emit(ctx, record)
}

// TaskFinishedOption sets an attribute, the severity, or the timestamp of an
// event EmitTaskFinished emits.
type TaskFinishedOption interface {
	taskFinishedOption(record *log.Record)
}

type taskFinishedEventSeverity struct{ v log.Severity }

func (o taskFinishedEventSeverity) taskFinishedOption(record *log.Record) {
	record.SetSeverity(o.v)
}

// WithTaskFinishedSeverity sets the severity of the event, in place of
// log.SeverityInfo.
func WithTaskFinishedSeverity(severity log.Severity) TaskFinishedOption {
	return taskFinishedEventSeverity{v: severity}
}

type taskFinishedEventTimestamp struct{ v time.Time }

func (o taskFinishedEventTimestamp) taskFinishedOption(record *log.Record) {
	record.SetTimestamp(o.v)
}

// WithTaskFinishedTimestamp sets the time the event occurred. Without it the
// event carries only the time it was observed.
func WithTaskFinishedTimestamp(timestamp time.Time) TaskFinishedOption {
	return taskFinishedEventTimestamp{v: timestamp}
}

type taskFinishedEventTaskAttempt struct{ v myappattr.TaskAttemptAttr }

func (o taskFinishedEventTaskAttempt) taskFinishedOption(record *log.Record) {
	record.AddAttributes(o.v.KeyValue())
}

// WithTaskFinishedTaskAttempt sets `myapp.task.attempt` on the event.
//
// Recommended: When the task ran more than once.
func WithTaskFinishedTaskAttempt(v myappattr.TaskAttemptAttr) TaskFinishedOption {
	return taskFinishedEventTaskAttempt{v: v}
}

// EmitTaskFinished emits the `worker.task.finished` event through logger. It
// is skipped when logger is not enabled for it, and the zero logger emits
// nothing.
//
// A task reached a final state on a worker.
//
// Emitted once per task, after its last attempt.
func EmitTaskFinished(ctx context.Context, logger semconvlogger.Logger, myappTaskState myappattr.TaskStateAttr, workerHostName workerattr.HostNameAttr, opts ...TaskFinishedOption) {
	var record log.Record
	record.SetEventName("worker.task.finished")
	record.SetSeverity(log.SeverityInfo)
	record.AddAttributes(
		myappTaskState.KeyValue(),
		workerHostName.KeyValue(),
	)
	for _, opt := range opts {
		opt.taskFinishedOption(&record)
	}
	if !logger.LogLogger().Enabled(ctx, log.EnabledParameters{Severity: record.Severity(), EventName: record.EventName()}) {
		return
	}
	logger.LogLogger().Emit(ctx, record)
}
