// Code generated by weaver. DO NOT EDIT.

// Package acmeconv is the root of the Go form of a semantic convention
// registry.
//
// It declares only SchemaURL, so importing it pulls in no OpenTelemetry API.
// The handles that carry it into telemetry, such as a Meter, live in
// packages of their own. Every name lives in a package scoped by its
// namespace and the kind of signal it describes: attributes become
// `<namespace>attr`, holding typed attribute values, metrics become
// `<namespace>metric`, holding typed instruments, and spans become
// `<namespace>span`, holding typed span starters. Identifiers drop the
// namespace prefix the package name already carries, and a signal package
// imports the `<namespace>attr` packages its signals need, never the
// reverse.
//
// # Packages
//
//   - [example.com/acme/acmeconv/v1.2.0/acmeconvmeter]: the Meter every metric instrument is created from
//   - [example.com/acme/acmeconv/v1.2.0/myappattr]: `myapp.*` attributes
//   - [example.com/acme/acmeconv/v1.2.0/myappmetric]: `myapp.*` metrics
package acmeconv
