// Code generated by weaver. DO NOT EDIT.

// Package acmeconv is the root of the Go form of a semantic convention
// registry.
//
// It declares only SchemaURL. When the registry has metrics, `acmeconvmeter`
// holds the Meter that carries it into every instrument. Every name lives
// in a package scoped by its namespace and the kind of signal it describes:
// attributes become `<namespace>attr`, holding typed attribute values, and
// metrics become `<namespace>metric`, holding typed instruments. Identifiers
// drop the namespace prefix the package name already carries, and a
// `<namespace>metric` package imports the `<namespace>attr` packages its
// metrics need, never the reverse.
//
// # Packages
//
//   - [example.com/acme/acmeconv/v1.2.0/acmeconvmeter]: the Meter every metric instrument is created from
//   - [example.com/acme/acmeconv/v1.2.0/myappattr]: `myapp.*` attributes
//   - [example.com/acme/acmeconv/v1.2.0/myappmetric]: `myapp.*` metrics
package acmeconv
