// Code generated by weaver. DO NOT EDIT.

package acmeconv

// SchemaURL is the schema URL of the registry these packages are generated
// from.
const SchemaURL = "https://example.com/schemas/root_package_version_segment/1.0.0"
