// Code generated by weaver. DO NOT EDIT.

package myappspan

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"go.opentelemetry.io/otel/trace/noop"

	"example.com/myappattr"
	"example.com/myapptracer"
	"example.com/upstream/errorattr"
)

// TaskDispatchStartAttr is an attribute StartTaskDispatch accepts in
// addition to the ones it requires.
type TaskDispatchStartAttr interface {
	taskDispatchStartAttr() attribute.KeyValue
}

// TaskDispatchAttr is an attribute a TaskDispatchSpan also accepts after it
// started, through SetAttributes.
type TaskDispatchAttr interface {
	TaskDispatchStartAttr
	taskDispatchAttr()
}

type taskDispatchSpanServerPort struct{ v int }

func (o taskDispatchSpanServerPort) taskDispatchStartAttr() attribute.KeyValue {
	return attribute.Int("server.port", o.v)
}

func (taskDispatchSpanServerPort) taskDispatchAttr() {}

// WithTaskDispatchServerPort sets `server.port` on a TaskDispatchSpan, when
// StartTaskDispatch starts it or later through SetAttributes.
func WithTaskDispatchServerPort(v int) TaskDispatchAttr {
	return taskDispatchSpanServerPort{v: v}
}

// TaskDispatchSpan is a started span of `myapp.task.dispatch`. The zero
// TaskDispatchSpan records nothing.
type TaskDispatchSpan struct{ span trace.Span }

// Span returns the underlying trace.Span, or a no-op one for the zero
// TaskDispatchSpan.
func (s TaskDispatchSpan) Span() trace.Span {
	if s.span == nil {
		return noop.Span{}
	}
	return s.span
}

// End ends the span.
func (s TaskDispatchSpan) End(opts ...trace.SpanEndOption) {
	s.Span().End(opts...)
}

// SetAttributes sets attributes on the span after it started.
func (s TaskDispatchSpan) SetAttributes(attrs ...TaskDispatchAttr) {
	kvs := make([]attribute.KeyValue, 0, len(attrs))
	for _, attr := range attrs {
		kvs = append(kvs, attr.taskDispatchStartAttr())
	}
	s.Span().SetAttributes(kvs...)
}

// RecordError records err as an exception event on the span.
func (s TaskDispatchSpan) RecordError(err error, opts ...trace.EventOption) {
	s.Span().RecordError(err, opts...)
}

// SetStatus sets the status of the span.
func (s TaskDispatchSpan) SetStatus(code codes.Code, description string) {
	s.Span().SetStatus(code, description)
}

// StartTaskDispatch starts the `myapp.task.dispatch` span from tracer with
// span kind internal.
//
// Dispatch of a task.
//
// The span is named `task {myapp.task.id} failed with {error.type}`, with
// each placeholder replaced by the value of the attribute it names.
func StartTaskDispatch(ctx context.Context, tracer myapptracer.Tracer, errorType errorattr.TypeAttr, myappTaskID myappattr.TaskIDAttr, opts ...TaskDispatchStartAttr) (context.Context, TaskDispatchSpan) {
	kvs := make([]attribute.KeyValue, 0, 2+len(opts))
	kvs = append(kvs, errorType.KeyValue())
	kvs = append(kvs, myappTaskID.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.taskDispatchStartAttr())
	}
	name := "task " + myappTaskID.KeyValue().Value.Emit() + " failed with " + errorType.KeyValue().Value.Emit()
	ctx, span := tracer.TraceTracer().Start(
		ctx,
		name,
		trace.WithSpanKind(trace.SpanKindInternal),
		trace.WithAttributes(kvs...),
	)
	return ctx, TaskDispatchSpan{span: span}
}
