// Code generated by weaver. DO NOT EDIT.

package myappevent

import (
	"context"
	"time"

	"go.opentelemetry.io/otel/log"

	"example.com/semconv/myappattr"
	"example.com/semconv/semconvlogger"
	"example.com/semconv/workerattr"
)

// TaskFinishedOption sets an attribute, the severity, or the timestamp of an
// event EmitTaskFinished emits.
type TaskFinishedOption interface {
	taskFinishedOption(record *log.Record)
}

type taskFinishedEventSeverity struct{ v log.Severity }

func (o taskFinishedEventSeverity) taskFinishedOption(record *log.Record) {
	record.SetSeverity(o.v)
}

// WithTaskFinishedSeverity sets the severity of the event, in place of
// log.SeverityInfo.
func WithTaskFinishedSeverity(severity log.Severity) TaskFinishedOption {
	return taskFinishedEventSeverity{v: severity}
}

type taskFinishedEventTimestamp struct{ v time.Time }

func (o taskFinishedEventTimestamp) taskFinishedOption(record *log.Record) {
	record.SetTimestamp(o.v)
}

// WithTaskFinishedTimestamp sets the time the event occurred. Without it the
// event carries only the time it was observed.
func WithTaskFinishedTimestamp(timestamp time.Time) TaskFinishedOption {
	return taskFinishedEventTimestamp{v: timestamp}
}

type taskFinishedEventTaskAttempt struct{ v myappattr.TaskAttemptAttr }

func (o taskFinishedEventTaskAttempt) taskFinishedOption(record *log.Record) {
	record.AddAttributes(o.v.KeyValue())
}

// WithTaskFinishedTaskAttempt sets `myapp.task.attempt` on the event.
//
// Recommended: When the task ran more than once.
func WithTaskFinishedTaskAttempt(v myappattr.TaskAttemptAttr) TaskFinishedOption {
	return taskFinishedEventTaskAttempt{v: v}
}

type taskFinishedEventHostName struct{ v workerattr.HostNameAttr }

func (o taskFinishedEventHostName) taskFinishedOption(record *log.Record) {
	record.AddAttributes(o.v.KeyValue())
}

// WithTaskFinishedHostName sets `worker.host.name` on the event.
//
// Opt-in: the convention records it only when a user asks for it.
func WithTaskFinishedHostName(v workerattr.HostNameAttr) TaskFinishedOption {
	return taskFinishedEventHostName{v: v}
}

// EmitTaskFinished emits the `myapp.task.finished` event through logger. It
// is skipped when logger is not enabled for it, and the zero logger emits
// nothing.
//
// A task reached a final state.
//
// Emitted once per task, after its last attempt.
func EmitTaskFinished(ctx context.Context, logger semconvlogger.Logger, myappTaskState myappattr.TaskStateAttr, opts ...TaskFinishedOption) {
	var record log.Record
	record.SetEventName("myapp.task.finished")
	record.SetSeverity(log.SeverityInfo)
	record.AddAttributes(
		myappTaskState.KeyValue(),
	)
	for _, opt := range opts {
		opt.taskFinishedOption(&record)
	}
	if !logger.LogLogger().Enabled(ctx, log.EnabledParameters{Severity: record.Severity(), EventName: record.EventName()}) {
		return
	}
	logger.LogLogger().Emit(ctx, record)
}

// TaskRetriedOption sets an attribute, the severity, or the timestamp of an
// event EmitTaskRetried emits.
type TaskRetriedOption interface {
	taskRetriedOption(record *log.Record)
}

type taskRetriedEventSeverity struct{ v log.Severity }

func (o taskRetriedEventSeverity) taskRetriedOption(record *log.Record) {
	record.SetSeverity(o.v)
}

// WithTaskRetriedSeverity sets the severity of the event, in place of
// log.SeverityInfo.
func WithTaskRetriedSeverity(severity log.Severity) TaskRetriedOption {
	return taskRetriedEventSeverity{v: severity}
}

type taskRetriedEventTimestamp struct{ v time.Time }

func (o taskRetriedEventTimestamp) taskRetriedOption(record *log.Record) {
	record.SetTimestamp(o.v)
}

// WithTaskRetriedTimestamp sets the time the event occurred. Without it the
// event carries only the time it was observed.
func WithTaskRetriedTimestamp(timestamp time.Time) TaskRetriedOption {
	return taskRetriedEventTimestamp{v: timestamp}
}

// EmitTaskRetried emits the `myapp.task.retried` event through logger. It is
// skipped when logger is not enabled for it, and the zero logger emits
// nothing.
//
// A task is about to run again.
//
// Opt-in: the convention records `myapp.task.retried` only when a user asks
// for it.
//
// Deprecated: Read the attempt from `myapp.task.finished` instead.
func EmitTaskRetried(ctx context.Context, logger semconvlogger.Logger, myappTaskAttempt myappattr.TaskAttemptAttr, opts ...TaskRetriedOption) {
	var record log.Record
	record.SetEventName("myapp.task.retried")
	record.SetSeverity(log.SeverityInfo)
	record.AddAttributes(
		myappTaskAttempt.KeyValue(),
	)
	for _, opt := range opts {
		opt.taskRetriedOption(&record)
	}
	if !logger.LogLogger().Enabled(ctx, log.EnabledParameters{Severity: record.Severity(), EventName: record.EventName()}) {
		return
	}
	logger.LogLogger().Emit(ctx, record)
}
