// Code generated by weaver. DO NOT EDIT.

package myappmetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"example.com/semconv/myappattr"
	"example.com/semconv/semconvmeter"
)

// TaskDurationHistogram is `myapp.task.duration`.
//
// Time a task took from start to finish.
type TaskDurationHistogram struct{ inst metric.Float64Histogram }

// NewTaskDurationHistogram creates the `myapp.task.duration` instrument from
// meter.
func NewTaskDurationHistogram(meter semconvmeter.Meter) (TaskDurationHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"myapp.task.duration",
		metric.WithDescription("Time a task took from start to finish."),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10),
	)
	if err != nil {
		return TaskDurationHistogram{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.duration", err)
	}
	return TaskDurationHistogram{inst: inst}, nil
}

// Record records one `myapp.task.duration` measurement. The zero
// TaskDurationHistogram records nothing.
func (m TaskDurationHistogram) Record(ctx context.Context, value float64, myappTaskID myappattr.TaskIDAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskID.KeyValue())
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}

// TaskLatencyHistogram is `myapp.task.latency`.
//
// Time between a task being queued and started.
type TaskLatencyHistogram struct{ inst metric.Float64Histogram }

// NewTaskLatencyHistogram creates the `myapp.task.latency` instrument from
// meter.
func NewTaskLatencyHistogram(meter semconvmeter.Meter) (TaskLatencyHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"myapp.task.latency",
		metric.WithDescription("Time between a task being queued and started."),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(1, 10, 100),
	)
	if err != nil {
		return TaskLatencyHistogram{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.latency", err)
	}
	return TaskLatencyHistogram{inst: inst}, nil
}

// Record records one `myapp.task.latency` measurement. The zero
// TaskLatencyHistogram records nothing.
func (m TaskLatencyHistogram) Record(ctx context.Context, value float64, myappTaskID myappattr.TaskIDAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskID.KeyValue())
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}

// TaskRetryDurationHistogram is `myapp.task.retry.duration`, a refinement of
// `myapp.task.duration` that records under that metric's name.
//
// Time a retried task took from start to finish.
type TaskRetryDurationHistogram struct{ inst metric.Float64Histogram }

// NewTaskRetryDurationHistogram creates the `myapp.task.duration` instrument
// from meter.
func NewTaskRetryDurationHistogram(meter semconvmeter.Meter) (TaskRetryDurationHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"myapp.task.duration",
		metric.WithDescription("Time a task took from start to finish."),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10),
	)
	if err != nil {
		return TaskRetryDurationHistogram{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.duration", err)
	}
	return TaskRetryDurationHistogram{inst: inst}, nil
}

// Record records one `myapp.task.retry.duration` measurement. The zero
// TaskRetryDurationHistogram records nothing.
func (m TaskRetryDurationHistogram) Record(ctx context.Context, value float64, myappTaskID myappattr.TaskIDAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskID.KeyValue())
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}

// TaskSizeHistogram is `myapp.task.size`.
//
// Size of a task's payload.
type TaskSizeHistogram struct{ inst metric.Float64Histogram }

// NewTaskSizeHistogram creates the `myapp.task.size` instrument from meter.
func NewTaskSizeHistogram(meter semconvmeter.Meter) (TaskSizeHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"myapp.task.size",
		metric.WithDescription("Size of a task\u0027s payload."),
		metric.WithUnit("By"),
	)
	if err != nil {
		return TaskSizeHistogram{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.size", err)
	}
	return TaskSizeHistogram{inst: inst}, nil
}

// Record records one `myapp.task.size` measurement. The zero
// TaskSizeHistogram records nothing.
func (m TaskSizeHistogram) Record(ctx context.Context, value float64, myappTaskID myappattr.TaskIDAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskID.KeyValue())
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}
