// Code generated by weaver. DO NOT EDIT.

package myappattr

import "go.opentelemetry.io/otel/attribute"

// taskIDKey is the attribute key of `myapp.task.id`.
const taskIDKey = attribute.Key("myapp.task.id")

// TaskIDAttr is a value of `myapp.task.id`.
//
// Unique identifier of the task.
type TaskIDAttr struct{ value string }

// NewTaskIDAttr returns a value of `myapp.task.id`.
func NewTaskIDAttr(value string) TaskIDAttr {
	return TaskIDAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskIDAttr) Key() attribute.Key {
	return taskIDKey
}

// KeyValue is the `myapp.task.id` attribute set to this value.
func (v TaskIDAttr) KeyValue() attribute.KeyValue {
	return taskIDKey.String(v.value)
}
