// Code generated by weaver. DO NOT EDIT.

// Package acmeconvmeter holds the Meter every metric instrument of the
// registry is created from, so everything the instruments record is tied to
// acmeconv.SchemaURL.
package acmeconvmeter
