// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

// Package billingmetric is the Go form of the metrics named `acme.billing.*`.
//
// Each metric and metric refinement is an instrument type built from a
// acmesemconv.Meter by its New constructor, and recorded through the method
// its instrument kind gives it. Counters, up-down counters, and gauges also
// have an Observable form, observed from a callback. Required attributes are
// typed parameters and the rest are trailing options. Identifiers omit the
// namespace prefix `acme.billing.`, because the package name already carries
// it.
package billingmetric
