// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

// Package billingmetric is the Go form of the metrics named `acme.billing.*`.
//
// Each metric is an instrument type built from a metric.Meter by its New
// constructor, and recorded through the method its instrument kind gives it.
// Required attributes are typed parameters and the rest are trailing
// options. Identifiers omit the namespace prefix `acme.billing.`, because
// the package name already carries it.
package billingmetric
