// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

package billingmetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"example.com/acme/internal/acmesemconv/billingattr"
	"example.com/acme/internal/acmesemconv/myappattr"
)

// InvoiceAmountHistogramAttr is an attribute `acme.billing.invoice.amount`
// accepts in addition to the ones InvoiceAmountHistogram.Record requires.
type InvoiceAmountHistogramAttr interface {
	invoiceAmountHistogramAttr() attribute.KeyValue
}

type invoiceAmountHistogramCurrency struct{ v billingattr.CurrencyAttr }

func (o invoiceAmountHistogramCurrency) invoiceAmountHistogramAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithInvoiceAmountHistogramCurrency attaches `billing.currency` to
// InvoiceAmountHistogram.
func WithInvoiceAmountHistogramCurrency(v billingattr.CurrencyAttr) InvoiceAmountHistogramAttr {
	return invoiceAmountHistogramCurrency{v: v}
}

type invoiceAmountHistogramRequestURL struct{ v myappattr.RequestURLAttr }

func (o invoiceAmountHistogramRequestURL) invoiceAmountHistogramAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithInvoiceAmountHistogramRequestURL attaches `myapp.request.url` to
// InvoiceAmountHistogram.
func WithInvoiceAmountHistogramRequestURL(v myappattr.RequestURLAttr) InvoiceAmountHistogramAttr {
	return invoiceAmountHistogramRequestURL{v: v}
}

// InvoiceAmountHistogram is `acme.billing.invoice.amount`.
//
// Amount of each issued invoice.
type InvoiceAmountHistogram struct{ inst metric.Float64Histogram }

// NewInvoiceAmountHistogram creates the `acme.billing.invoice.amount`
// instrument from meter.
func NewInvoiceAmountHistogram(meter metric.Meter) (InvoiceAmountHistogram, error) {
	inst, err := meter.Float64Histogram(
		"acme.billing.invoice.amount",
		metric.WithDescription("Amount of each issued invoice."),
		metric.WithUnit("{currency_unit}"),
	)
	if err != nil {
		return InvoiceAmountHistogram{}, fmt.Errorf("create the %s instrument: %w", "acme.billing.invoice.amount", err)
	}
	return InvoiceAmountHistogram{inst: inst}, nil
}

// Record records one `acme.billing.invoice.amount` measurement. The zero
// InvoiceAmountHistogram records nothing.
func (m InvoiceAmountHistogram) Record(ctx context.Context, value float64, billingInvoiceID billingattr.InvoiceIDAttr, opts ...InvoiceAmountHistogramAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1+len(opts))
	kvs = append(kvs, billingInvoiceID.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.invoiceAmountHistogramAttr())
	}
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}
