// Generated by OpenTelemetry Weaver.
/// How the user was authenticated.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum MethodAttr {
    /// A password was checked.
    Password,
    /// A bearer token was checked.
    Token,
}

#[allow(deprecated)]
impl MethodAttr {
    pub const KEY: &'static str = "auth.method";
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::KeyValue {
    fn from(value: MethodAttr) -> Self {
        let value: String = match value {
            MethodAttr::Password => "password".into(),
            MethodAttr::Token => "token".into(),
        };
        ::opentelemetry::KeyValue::new(MethodAttr::KEY, value)
    }
}
/// Whether the attempt succeeded.
#[derive(Debug, Clone, PartialEq)]
pub struct SuccessAttr(bool);

#[allow(deprecated)]
impl SuccessAttr {
    pub const KEY: &'static str = "auth.success";
}

#[allow(deprecated)]
impl From<bool> for SuccessAttr {
    fn from(value: bool) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<SuccessAttr> for ::opentelemetry::KeyValue {
    fn from(value: SuccessAttr) -> Self {
        ::opentelemetry::KeyValue::new(SuccessAttr::KEY, value.0)
    }
}
