// Generated by OpenTelemetry Weaver.

/// How the user was authenticated.
#[derive(Debug, Clone, PartialEq, Copy)]

pub enum MethodAttr {

    /// A password was checked.
    Password,

    /// A bearer token was checked.
    Token,

}


#[allow(deprecated)]
impl MethodAttr {
    pub const KEY: &'static str = "auth.method";


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        let value: String = match self {

            Self::Password => "password".into(),

            Self::Token => "token".into(),

        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)

    }
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::KeyValue {
    fn from(value: MethodAttr) -> Self {
        value.key_value()
    }
}

/// Whether the attempt succeeded.
#[derive(Debug, Clone, PartialEq)]

pub struct SuccessAttr(bool);


#[allow(deprecated)]
impl SuccessAttr {
    pub const KEY: &'static str = "auth.success";

    pub fn new(value: bool) -> Self {
        Self(value)
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<SuccessAttr> for ::opentelemetry::KeyValue {
    fn from(value: SuccessAttr) -> Self {
        value.key_value()
    }
}
