// Generated by OpenTelemetry Weaver.
/// How the user was authenticated.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum MethodAttr {
    /// A password was checked.
    Password,
    /// A bearer token was checked.
    Token,
}

#[allow(deprecated)]
impl MethodAttr {
    pub const KEY: &'static str = "auth.method";
}

#[allow(deprecated)]
impl AsRef<str> for MethodAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            MethodAttr::Password => "password",
            MethodAttr::Token => "token",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for MethodAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: MethodAttr) -> Self {
        let value: &'static str = match value {
            MethodAttr::Password => "password",
            MethodAttr::Token => "token",
        };
        ::opentelemetry::KeyValue::new(MethodAttr::KEY, value)
    }
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: MethodAttr) -> Self {
        let value: &'static str = match value {
            MethodAttr::Password => "password",
            MethodAttr::Token => "token",
        };
        value.into()
    }
}
/// Whether the attempt succeeded.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct SuccessAttr(bool);

#[allow(deprecated)]
impl SuccessAttr {
    pub const KEY: &'static str = "auth.success";
}

#[allow(deprecated)]
impl From<bool> for SuccessAttr {
    #[inline]
    fn from(value: bool) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for SuccessAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<SuccessAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: SuccessAttr) -> Self {
        ::opentelemetry::KeyValue::new(SuccessAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<SuccessAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: SuccessAttr) -> Self {
        value.0.into()
    }
}
