// Generated by OpenTelemetry Weaver.


pub const SCHEMA_URL: &str = "https://example.com/schemas/metrics/1.0.0";

pub mod authattr;

pub mod myappattr;


pub mod meter;



pub mod authmetric;

pub mod myappmetric;

pub mod workermetric;
