// Generated by OpenTelemetry Weaver.


pub const SCHEMA_URL: &str = "https://example.com/schemas/metrics/1.0.0";

pub mod authattr {

    /// How the user was authenticated.
    #[derive(Debug, Clone, PartialEq, Copy)]

    pub enum MethodAttr {

        /// A password was checked.
        Password,

        /// A bearer token was checked.
        Token,

    }


    #[allow(deprecated)]
    impl MethodAttr {
        pub const KEY: &'static str = "auth.method";


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            let value: String = match self {

                Self::Password => "password".into(),

                Self::Token => "token".into(),

            };
            ::opentelemetry::KeyValue::new(Self::KEY, value)

        }
    }

    #[allow(deprecated)]
    impl From<MethodAttr> for ::opentelemetry::KeyValue {
        fn from(value: MethodAttr) -> Self {
            value.key_value()
        }
    }

    /// Whether the attempt succeeded.
    #[derive(Debug, Clone, PartialEq)]

    pub struct SuccessAttr(bool);


    #[allow(deprecated)]
    impl SuccessAttr {
        pub const KEY: &'static str = "auth.success";

        pub fn new(value: bool) -> Self {
            Self(value)
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<SuccessAttr> for ::opentelemetry::KeyValue {
        fn from(value: SuccessAttr) -> Self {
            value.key_value()
        }
    }

}

pub mod myappattr {

    /// Unique identifier of the task.
    #[derive(Debug, Clone, PartialEq)]

    pub struct TaskIdAttr(String);


    #[allow(deprecated)]
    impl TaskIdAttr {
        pub const KEY: &'static str = "myapp.task.id";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<TaskIdAttr> for ::opentelemetry::KeyValue {
        fn from(value: TaskIdAttr) -> Self {
            value.key_value()
        }
    }

    /// Current state of the task.
    #[derive(Debug, Clone, PartialEq, Copy)]

    pub enum TaskStateAttr {

        /// The task is waiting to run.
        Queued,

        /// The task finished.
        Done,

    }


    #[allow(deprecated)]
    impl TaskStateAttr {
        pub const KEY: &'static str = "myapp.task.state";


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            let value: String = match self {

                Self::Queued => "queued".into(),

                Self::Done => "done".into(),

            };
            ::opentelemetry::KeyValue::new(Self::KEY, value)

        }
    }

    #[allow(deprecated)]
    impl From<TaskStateAttr> for ::opentelemetry::KeyValue {
        fn from(value: TaskStateAttr) -> Self {
            value.key_value()
        }
    }

}


pub mod meter;



pub mod authmetric;

pub mod myappmetric;

pub mod workermetric;
