// Generated by OpenTelemetry Weaver.
/// Unique identifier of the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskIdAttr(String);

#[allow(deprecated)]
impl TaskIdAttr {
    pub const KEY: &'static str = "myapp.task.id";
}

#[allow(deprecated)]
impl From<String> for TaskIdAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for TaskIdAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<TaskIdAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskIdAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskIdAttr::KEY, value.0)
    }
}
/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskStateAttr {
    /// The task is waiting to run.
    Queued,
    /// The task finished.
    Done,
}

#[allow(deprecated)]
impl TaskStateAttr {
    pub const KEY: &'static str = "myapp.task.state";
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskStateAttr) -> Self {
        let value: String = match value {
            TaskStateAttr::Queued => "queued".into(),
            TaskStateAttr::Done => "done".into(),
        };
        ::opentelemetry::KeyValue::new(TaskStateAttr::KEY, value)
    }
}
