// Generated by OpenTelemetry Weaver.
/// Synthetic identifier.
#[derive(Debug, Clone, PartialEq)]
pub struct Http2STATUSApiIDAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl Http2STATUSApiIDAttr {
    pub const KEY: &'static str = "caps.http2_STATUS.api_ID";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for Http2STATUSApiIDAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for Http2STATUSApiIDAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for Http2STATUSApiIDAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for Http2STATUSApiIDAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for Http2STATUSApiIDAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<Http2STATUSApiIDAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: Http2STATUSApiIDAttr) -> Self {
        ::opentelemetry::KeyValue::new(Http2STATUSApiIDAttr::KEY, value.0)
    }
}
/// Synthetic mode.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum Mode2STATEAttr {
    /// Synthetic state.
    HTTP2ReadySTATE,
}

#[allow(deprecated)]
impl Mode2STATEAttr {
    pub const KEY: &'static str = "caps.mode2_STATE";
}

#[allow(deprecated)]
impl AsRef<str> for Mode2STATEAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            Mode2STATEAttr::HTTP2ReadySTATE => "ready",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for Mode2STATEAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<Mode2STATEAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: Mode2STATEAttr) -> Self {
        let value: &'static str = match value {
            Mode2STATEAttr::HTTP2ReadySTATE => "ready",
        };
        ::opentelemetry::KeyValue::new(Mode2STATEAttr::KEY, value)
    }
}
