// Generated by OpenTelemetry Weaver.
/// Synthetic identifier.
#[derive(Debug, Clone, PartialEq)]
pub struct Http2STATUSApiIDAttr(String);

#[allow(deprecated)]
impl Http2STATUSApiIDAttr {
    pub const KEY: &'static str = "caps.http2_STATUS.api_ID";
}

#[allow(deprecated)]
impl From<String> for Http2STATUSApiIDAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for Http2STATUSApiIDAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<Http2STATUSApiIDAttr> for ::opentelemetry::KeyValue {
    fn from(value: Http2STATUSApiIDAttr) -> Self {
        ::opentelemetry::KeyValue::new(Http2STATUSApiIDAttr::KEY, value.0)
    }
}
/// Synthetic mode.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum Mode2STATEAttr {
    /// Synthetic state.
    HTTP2ReadySTATE,
}

#[allow(deprecated)]
impl Mode2STATEAttr {
    pub const KEY: &'static str = "caps.mode2_STATE";
}

#[allow(deprecated)]
impl From<Mode2STATEAttr> for ::opentelemetry::KeyValue {
    fn from(value: Mode2STATEAttr) -> Self {
        let value: String = match value {
            Mode2STATEAttr::HTTP2ReadySTATE => "ready".into(),
        };
        ::opentelemetry::KeyValue::new(Mode2STATEAttr::KEY, value)
    }
}
