// Generated by OpenTelemetry Weaver.
pub const SCHEMA_URL: &str = "https://example.com/schemas/spans/1.0.0";
pub mod myappattr;
pub mod workerattr;

pub mod tracer;
pub mod myappspan;
pub mod workerspan;
