// Generated by OpenTelemetry Weaver.
/// Synthetic naming value.
#[derive(Debug, Clone, PartialEq)]
pub struct ArrayFlagsAttr(Vec<bool>);

#[allow(deprecated)]
impl ArrayFlagsAttr {
    pub const KEY: &'static str = "myapp.array.flags";
}

#[allow(deprecated)]
impl From<Vec<bool>> for ArrayFlagsAttr {
    #[inline]
    fn from(value: Vec<bool>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[bool]> for ArrayFlagsAttr {
    #[inline]
    fn as_ref(&self) -> &[bool] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for ArrayFlagsAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<ArrayFlagsAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: ArrayFlagsAttr) -> Self {
        ::opentelemetry::KeyValue::new(ArrayFlagsAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::Bool(value.0)))
    }
}

#[allow(deprecated)]
impl From<ArrayFlagsAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: ArrayFlagsAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}

/// Synthetic naming value.
#[derive(Debug, Clone, PartialEq)]
pub struct ArrayIndicesAttr(Vec<i64>);

#[allow(deprecated)]
impl ArrayIndicesAttr {
    pub const KEY: &'static str = "myapp.array.indices";
}

#[allow(deprecated)]
impl From<Vec<i64>> for ArrayIndicesAttr {
    #[inline]
    fn from(value: Vec<i64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[i64]> for ArrayIndicesAttr {
    #[inline]
    fn as_ref(&self) -> &[i64] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for ArrayIndicesAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<ArrayIndicesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: ArrayIndicesAttr) -> Self {
        ::opentelemetry::KeyValue::new(ArrayIndicesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(value.0)))
    }
}

#[allow(deprecated)]
impl From<ArrayIndicesAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: ArrayIndicesAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}

/// Synthetic naming value.
#[derive(Debug, Clone, PartialEq)]
pub struct ArraySamplesAttr(Vec<f64>);

#[allow(deprecated)]
impl ArraySamplesAttr {
    pub const KEY: &'static str = "myapp.array.samples";
}

#[allow(deprecated)]
impl From<Vec<f64>> for ArraySamplesAttr {
    #[inline]
    fn from(value: Vec<f64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[f64]> for ArraySamplesAttr {
    #[inline]
    fn as_ref(&self) -> &[f64] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for ArraySamplesAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<ArraySamplesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: ArraySamplesAttr) -> Self {
        ::opentelemetry::KeyValue::new(ArraySamplesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::F64(value.0)))
    }
}

#[allow(deprecated)]
impl From<ArraySamplesAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: ArraySamplesAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}

/// Synthetic naming value.
#[derive(Debug, Clone, PartialEq)]
pub struct ArrayTagsAttr(Vec<::opentelemetry::StringValue>);

#[allow(deprecated)]
impl ArrayTagsAttr {
    pub const KEY: &'static str = "myapp.array.tags";
}

#[allow(deprecated)]
impl From<Vec<::opentelemetry::StringValue>> for ArrayTagsAttr {
    #[inline]
    fn from(value: Vec<::opentelemetry::StringValue>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<Vec<String>> for ArrayTagsAttr {
    fn from(value: Vec<String>) -> Self {
        Self(value.into_iter().map(Into::into).collect())
    }
}

#[allow(deprecated)]
impl AsRef<[::opentelemetry::StringValue]> for ArrayTagsAttr {
    #[inline]
    fn as_ref(&self) -> &[::opentelemetry::StringValue] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for ArrayTagsAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            write!(formatter, "\"{value}\"")?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<ArrayTagsAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: ArrayTagsAttr) -> Self {
        ::opentelemetry::KeyValue::new(ArrayTagsAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::String(value.0)))
    }
}

#[allow(deprecated)]
impl From<ArrayTagsAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: ArrayTagsAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}

/// Synthetic naming value.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct NumberValueAttr(f64);

#[allow(deprecated)]
impl NumberValueAttr {
    pub const KEY: &'static str = "myapp.number.value";
}

#[allow(deprecated)]
impl From<f64> for NumberValueAttr {
    #[inline]
    fn from(value: f64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for NumberValueAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<NumberValueAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: NumberValueAttr) -> Self {
        ::opentelemetry::KeyValue::new(NumberValueAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<NumberValueAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: NumberValueAttr) -> Self {
        value.0.into()
    }
}

/// Name of the queue the task came from.
#[derive(Debug, Clone, PartialEq)]
pub struct QueueNameAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl QueueNameAttr {
    pub const KEY: &'static str = "myapp.queue.name";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for QueueNameAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<String> for QueueNameAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for QueueNameAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for QueueNameAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for QueueNameAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<QueueNameAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: QueueNameAttr) -> Self {
        ::opentelemetry::KeyValue::new(QueueNameAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<QueueNameAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: QueueNameAttr) -> Self {
        value.0.into()
    }
}

/// Number of the attempt, starting at one.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct TaskAttemptAttr(i64);

#[allow(deprecated)]
impl TaskAttemptAttr {
    pub const KEY: &'static str = "myapp.task.attempt";
}

#[allow(deprecated)]
impl From<i64> for TaskAttemptAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for TaskAttemptAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<TaskAttemptAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: TaskAttemptAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskAttemptAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<TaskAttemptAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: TaskAttemptAttr) -> Self {
        value.0.into()
    }
}

/// Unique identifier of the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskIdAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl TaskIdAttr {
    pub const KEY: &'static str = "myapp.task.id";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for TaskIdAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<String> for TaskIdAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for TaskIdAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for TaskIdAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for TaskIdAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<TaskIdAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: TaskIdAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskIdAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<TaskIdAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: TaskIdAttr) -> Self {
        value.0.into()
    }
}

/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskStateAttr {
    /// The task is waiting to run.
    Queued,
    /// The task finished.
    Done,
}

#[allow(deprecated)]
impl TaskStateAttr {
    pub const KEY: &'static str = "myapp.task.state";
}

#[allow(deprecated)]
impl AsRef<str> for TaskStateAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            TaskStateAttr::Queued => "queued",
            TaskStateAttr::Done => "done",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for TaskStateAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: TaskStateAttr) -> Self {
        let value: &'static str = match value {
            TaskStateAttr::Queued => "queued",
            TaskStateAttr::Done => "done",
        };
        ::opentelemetry::KeyValue::new(TaskStateAttr::KEY, value)
    }
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: TaskStateAttr) -> Self {
        let value: &'static str = match value {
            TaskStateAttr::Queued => "queued",
            TaskStateAttr::Done => "done",
        };
        value.into()
    }
}
