// Generated by OpenTelemetry Weaver.
/// Name of the queue the task came from.
#[derive(Debug, Clone, PartialEq)]
pub struct QueueNameAttr(String);

#[allow(deprecated)]
impl QueueNameAttr {
    pub const KEY: &'static str = "myapp.queue.name";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for QueueNameAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for QueueNameAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<QueueNameAttr> for ::opentelemetry::KeyValue {
    fn from(value: QueueNameAttr) -> Self {
        value.key_value()
    }
}
/// Number of the attempt, starting at one.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskAttemptAttr(i64);

#[allow(deprecated)]
impl TaskAttemptAttr {
    pub const KEY: &'static str = "myapp.task.attempt";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<i64> for TaskAttemptAttr {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskAttemptAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskAttemptAttr) -> Self {
        value.key_value()
    }
}
/// Unique identifier of the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskIdAttr(String);

#[allow(deprecated)]
impl TaskIdAttr {
    pub const KEY: &'static str = "myapp.task.id";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for TaskIdAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for TaskIdAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<TaskIdAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskIdAttr) -> Self {
        value.key_value()
    }
}
/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskStateAttr {
    /// The task is waiting to run.
    Queued,
    /// The task finished.
    Done,
}

#[allow(deprecated)]
impl TaskStateAttr {
    pub const KEY: &'static str = "myapp.task.state";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: String = match self {
            Self::Queued => "queued".into(),
            Self::Done => "done".into(),
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskStateAttr) -> Self {
        value.key_value()
    }
}
