// Generated by OpenTelemetry Weaver.
/// Host name of the worker.
#[derive(Debug, Clone, PartialEq)]
pub struct HostNameAttr(String);

#[allow(deprecated)]
impl HostNameAttr {
    pub const KEY: &'static str = "worker.host.name";
}

#[allow(deprecated)]
impl From<String> for HostNameAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for HostNameAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<HostNameAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostNameAttr) -> Self {
        ::opentelemetry::KeyValue::new(HostNameAttr::KEY, value.0)
    }
}
/// Port the worker listens on.
#[derive(Debug, Clone, PartialEq)]
pub struct HostPortAttr(i64);

#[allow(deprecated)]
impl HostPortAttr {
    pub const KEY: &'static str = "worker.host.port";
}

#[allow(deprecated)]
impl From<i64> for HostPortAttr {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<HostPortAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostPortAttr) -> Self {
        ::opentelemetry::KeyValue::new(HostPortAttr::KEY, value.0)
    }
}
