// Generated by OpenTelemetry Weaver.
/// Host name of the worker.
#[derive(Debug, Clone, PartialEq)]
pub struct HostNameAttr(String);

#[allow(deprecated)]
impl HostNameAttr {
    pub const KEY: &'static str = "worker.host.name";
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<HostNameAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostNameAttr) -> Self {
        value.key_value()
    }
}
/// Port the worker listens on.
#[derive(Debug, Clone, PartialEq)]
pub struct HostPortAttr(i64);

#[allow(deprecated)]
impl HostPortAttr {
    pub const KEY: &'static str = "worker.host.port";
    pub fn new(value: i64) -> Self {
        Self(value)
    }

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<HostPortAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostPortAttr) -> Self {
        value.key_value()
    }
}
