// Code generated by weaver. DO NOT EDIT.

package myappmetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"example.com/semconv"
	"example.com/semconv/authattr"
	"example.com/semconv/myappattr"
)

// QueueDepthGauge is `myapp.queue.depth`.
//
// Number of tasks waiting in the queue.
//
// Deprecated: Replaced by `myapp.task.active`.
type QueueDepthGauge struct{ inst metric.Int64Gauge }

// NewQueueDepthGauge creates the `myapp.queue.depth` instrument from meter.
//
// Deprecated: Replaced by `myapp.task.active`.
func NewQueueDepthGauge(meter semconv.Meter) (QueueDepthGauge, error) {
	inst, err := meter.MetricMeter().Int64Gauge(
		"myapp.queue.depth",
		metric.WithDescription("Number of tasks waiting in the queue."),
		metric.WithUnit("{task}"),
	)
	if err != nil {
		return QueueDepthGauge{}, fmt.Errorf("create the %s instrument: %w", "myapp.queue.depth", err)
	}
	return QueueDepthGauge{inst: inst}, nil
}

// Record records one `myapp.queue.depth` measurement. The zero
// QueueDepthGauge records nothing.
func (m QueueDepthGauge) Record(ctx context.Context, value int64) {
	if m.inst == nil {
		return
	}
	m.inst.Record(ctx, value)
}

// TaskActiveUpDownCounter is `myapp.task.active`.
//
// Number of tasks currently running.
type TaskActiveUpDownCounter struct{ inst metric.Int64UpDownCounter }

// NewTaskActiveUpDownCounter creates the `myapp.task.active` instrument from
// meter.
func NewTaskActiveUpDownCounter(meter semconv.Meter) (TaskActiveUpDownCounter, error) {
	inst, err := meter.MetricMeter().Int64UpDownCounter(
		"myapp.task.active",
		metric.WithDescription("Number of tasks currently running."),
		metric.WithUnit("{task}"),
	)
	if err != nil {
		return TaskActiveUpDownCounter{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.active", err)
	}
	return TaskActiveUpDownCounter{inst: inst}, nil
}

// Add records one `myapp.task.active` measurement. The zero
// TaskActiveUpDownCounter records nothing.
func (m TaskActiveUpDownCounter) Add(ctx context.Context, incr int64, myappTaskState myappattr.TaskStateAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskState.KeyValue())
	m.inst.Add(ctx, incr, metric.WithAttributes(kvs...))
}

// TaskDurationHistogramAttr is an attribute `myapp.task.duration` accepts in
// addition to the ones TaskDurationHistogram.Record requires.
type TaskDurationHistogramAttr interface {
	taskDurationHistogramAttr() attribute.KeyValue
}

type taskDurationHistogramMethod struct{ v authattr.MethodAttr }

func (o taskDurationHistogramMethod) taskDurationHistogramAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithTaskDurationHistogramMethod attaches `auth.method` to
// TaskDurationHistogram.
func WithTaskDurationHistogramMethod(v authattr.MethodAttr) TaskDurationHistogramAttr {
	return taskDurationHistogramMethod{v: v}
}

type taskDurationHistogramTaskState struct{ v myappattr.TaskStateAttr }

func (o taskDurationHistogramTaskState) taskDurationHistogramAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithTaskDurationHistogramTaskState attaches `myapp.task.state` to
// TaskDurationHistogram.
func WithTaskDurationHistogramTaskState(v myappattr.TaskStateAttr) TaskDurationHistogramAttr {
	return taskDurationHistogramTaskState{v: v}
}

// TaskDurationHistogram is `myapp.task.duration`.
//
// Time a task took from start to finish.
//
// Measured by the worker that ran the task.
type TaskDurationHistogram struct{ inst metric.Float64Histogram }

// NewTaskDurationHistogram creates the `myapp.task.duration` instrument from
// meter.
func NewTaskDurationHistogram(meter semconv.Meter) (TaskDurationHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"myapp.task.duration",
		metric.WithDescription("Time a task took from start to finish."),
		metric.WithUnit("s"),
	)
	if err != nil {
		return TaskDurationHistogram{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.duration", err)
	}
	return TaskDurationHistogram{inst: inst}, nil
}

// Record records one `myapp.task.duration` measurement. The zero
// TaskDurationHistogram records nothing.
func (m TaskDurationHistogram) Record(ctx context.Context, value float64, myappTaskID myappattr.TaskIDAttr, opts ...TaskDurationHistogramAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1+len(opts))
	kvs = append(kvs, myappTaskID.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.taskDurationHistogramAttr())
	}
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}

// TaskStartedCounter is `myapp.task.started`.
//
// Number of tasks started.
type TaskStartedCounter struct{ inst metric.Int64Counter }

// NewTaskStartedCounter creates the `myapp.task.started` instrument from
// meter.
func NewTaskStartedCounter(meter semconv.Meter) (TaskStartedCounter, error) {
	inst, err := meter.MetricMeter().Int64Counter(
		"myapp.task.started",
		metric.WithDescription("Number of tasks started."),
		metric.WithUnit("{task}"),
	)
	if err != nil {
		return TaskStartedCounter{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.started", err)
	}
	return TaskStartedCounter{inst: inst}, nil
}

// Add records one `myapp.task.started` measurement. The zero
// TaskStartedCounter records nothing.
func (m TaskStartedCounter) Add(ctx context.Context, incr int64) {
	if m.inst == nil {
		return
	}
	m.inst.Add(ctx, incr)
}
