// Code generated by weaver. DO NOT EDIT.

package workerattr

import "go.opentelemetry.io/otel/attribute"

// hostNameKey is the attribute key of `worker.host.name`.
const hostNameKey = attribute.Key("worker.host.name")

// HostNameAttr is a value of `worker.host.name`.
//
// Name of the worker host.
type HostNameAttr struct{ value string }

// NewHostNameAttr returns a value of `worker.host.name`.
func NewHostNameAttr(value string) HostNameAttr {
	return HostNameAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (HostNameAttr) Key() attribute.Key {
	return hostNameKey
}

// KeyValue is the `worker.host.name` attribute set to this value.
func (v HostNameAttr) KeyValue() attribute.KeyValue {
	return hostNameKey.String(v.value)
}
