// Code generated by weaver. DO NOT EDIT.

// Package semconvmeter holds the Meter every metric instrument of the
// registry is created from, so everything the instruments record is tied to
// semconv.SchemaURL.
package semconvmeter
