// Code generated by weaver. DO NOT EDIT.

package semconvmeter

import (
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/noop"

	"example.com/semconv"
)

// Meter is a metric.Meter whose instrumentation scope carries
// semconv.SchemaURL. Every instrument in this registry is created from one,
// so everything it records is tied to the registry's schema.
//
// The zero Meter creates instruments that record nothing.
type Meter struct{ meter metric.Meter }

// New returns the meter named name from provider, with semconv.SchemaURL set
// on its instrumentation scope. A schema URL in opts is replaced.
func New(provider metric.MeterProvider, name string, opts ...metric.MeterOption) Meter {
	opts = append(opts[:len(opts):len(opts)], metric.WithSchemaURL(semconv.SchemaURL))
	return Meter{meter: provider.Meter(name, opts...)}
}

// MetricMeter returns the underlying metric.Meter, or a no-op one for the
// zero Meter.
func (m Meter) MetricMeter() metric.Meter {
	if m.meter == nil {
		return noop.Meter{}
	}
	return m.meter
}
