// Code generated by weaver. DO NOT EDIT.

package myappmetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"example.com/semconv/myappattr"
	"example.com/semconv/semconvmeter"
)

// TaskDurationHistogram is `myapp.task.duration`.
//
// Time a task took from start to finish.
type TaskDurationHistogram struct{ inst metric.Float64Histogram }

// NewTaskDurationHistogram creates the `myapp.task.duration` instrument from
// meter.
func NewTaskDurationHistogram(meter semconvmeter.Meter) (TaskDurationHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"myapp.task.duration",
		metric.WithDescription("Time a task took from start to finish."),
		metric.WithUnit("s"),
	)
	if err != nil {
		return TaskDurationHistogram{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.duration", err)
	}
	return TaskDurationHistogram{inst: inst}, nil
}

// Record records one `myapp.task.duration` measurement. The zero
// TaskDurationHistogram records nothing.
func (m TaskDurationHistogram) Record(ctx context.Context, value float64, myappTaskID myappattr.TaskIDAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskID.KeyValue())
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}

// TaskQueueWaitHistogram is `myapp.task.queue_wait`.
//
// Time a task waited in the queue, in minutes.
type TaskQueueWaitHistogram struct{ inst metric.Float64Histogram }

// NewTaskQueueWaitHistogram creates the `myapp.task.queue_wait` instrument
// from meter.
func NewTaskQueueWaitHistogram(meter semconvmeter.Meter) (TaskQueueWaitHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"myapp.task.queue_wait",
		metric.WithDescription("Time a task waited in the queue, in minutes."),
		metric.WithUnit("min"),
		metric.WithExplicitBucketBoundaries(1, 5, 10, 30, 60),
	)
	if err != nil {
		return TaskQueueWaitHistogram{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.queue_wait", err)
	}
	return TaskQueueWaitHistogram{inst: inst}, nil
}

// Record records one `myapp.task.queue_wait` measurement. The zero
// TaskQueueWaitHistogram records nothing.
func (m TaskQueueWaitHistogram) Record(ctx context.Context, value float64, myappTaskID myappattr.TaskIDAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskID.KeyValue())
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}
