// Code generated by weaver. DO NOT EDIT.

// Package workermetric is the Go form of the metrics named `worker.*`.
//
// Each metric is an instrument type built from a metric.Meter by its New
// constructor, and recorded through the method its instrument kind gives it.
// Required attributes are typed parameters and the rest are trailing
// options. Identifiers omit the namespace prefix `worker.`, because the
// package name already carries it.
package workermetric
