// Code generated by weaver. DO NOT EDIT.

package workermetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"example.com/semconv"
	"example.com/semconv/authattr"
	"example.com/semconv/myappattr"
)

// TaskDurationHistogramAttr is an attribute `worker.task.duration` accepts
// in addition to the ones TaskDurationHistogram.Record requires.
type TaskDurationHistogramAttr interface {
	taskDurationHistogramAttr() attribute.KeyValue
}

type taskDurationHistogramMethod struct{ v authattr.MethodAttr }

func (o taskDurationHistogramMethod) taskDurationHistogramAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithTaskDurationHistogramMethod attaches `auth.method` to
// TaskDurationHistogram.
//
// Opt-in: the convention records it only when a user asks for it.
func WithTaskDurationHistogramMethod(v authattr.MethodAttr) TaskDurationHistogramAttr {
	return taskDurationHistogramMethod{v: v}
}

type taskDurationHistogramTaskState struct{ v myappattr.TaskStateAttr }

func (o taskDurationHistogramTaskState) taskDurationHistogramAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithTaskDurationHistogramTaskState attaches `myapp.task.state` to
// TaskDurationHistogram.
//
// Conditionally required: If the task reached a final state.
func WithTaskDurationHistogramTaskState(v myappattr.TaskStateAttr) TaskDurationHistogramAttr {
	return taskDurationHistogramTaskState{v: v}
}

// TaskDurationHistogram is `worker.task.duration`, a refinement of
// `myapp.task.duration` that records under that metric's name.
//
// Time a task took on the worker that ran it.
//
// Measured by the worker that ran the task.
type TaskDurationHistogram struct{ inst metric.Float64Histogram }

// NewTaskDurationHistogram creates the `myapp.task.duration` instrument from
// meter.
func NewTaskDurationHistogram(meter semconv.Meter) (TaskDurationHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"myapp.task.duration",
		metric.WithDescription("Time a task took from start to finish."),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0, 0.005, 0.01, 0.1, 1, 10),
	)
	if err != nil {
		return TaskDurationHistogram{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.duration", err)
	}
	return TaskDurationHistogram{inst: inst}, nil
}

// Record records one `worker.task.duration` measurement. The zero
// TaskDurationHistogram records nothing.
func (m TaskDurationHistogram) Record(ctx context.Context, value float64, myappTaskID myappattr.TaskIDAttr, opts ...TaskDurationHistogramAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1+len(opts))
	kvs = append(kvs, myappTaskID.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.taskDurationHistogramAttr())
	}
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}
