// Code generated by weaver. DO NOT EDIT.

package myappmetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"example.com/semconv/myappattr"
)

// TaskFailedCounterAttr is an attribute `myapp.task.failed` accepts in
// addition to the ones TaskFailedCounter.Add requires.
type TaskFailedCounterAttr interface {
	taskFailedCounterAttr() attribute.KeyValue
}

type taskFailedCounterHTTPRequestMethodList struct{ v []string }

func (o taskFailedCounterHTTPRequestMethodList) taskFailedCounterAttr() attribute.KeyValue {
	return attribute.StringSlice("http.request.method_list", o.v)
}

// WithTaskFailedCounterHTTPRequestMethodList attaches
// `http.request.method_list` to TaskFailedCounter.
func WithTaskFailedCounterHTTPRequestMethodList(v []string) TaskFailedCounterAttr {
	return taskFailedCounterHTTPRequestMethodList{v: v}
}

// TaskFailedCounter is `myapp.task.failed`.
//
// Number of tasks that failed.
type TaskFailedCounter struct{ inst metric.Int64Counter }

// NewTaskFailedCounter creates the `myapp.task.failed` instrument from
// meter.
func NewTaskFailedCounter(meter metric.Meter) (TaskFailedCounter, error) {
	inst, err := meter.Int64Counter(
		"myapp.task.failed",
		metric.WithDescription("Number of tasks that failed."),
		metric.WithUnit("{task}"),
	)
	if err != nil {
		return TaskFailedCounter{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.failed", err)
	}
	return TaskFailedCounter{inst: inst}, nil
}

// Add records one `myapp.task.failed` measurement. The zero
// TaskFailedCounter records nothing.
func (m TaskFailedCounter) Add(ctx context.Context, incr int64, errorType string, myappTaskID myappattr.TaskIDAttr, opts ...TaskFailedCounterAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 2+len(opts))
	kvs = append(kvs, attribute.String("error.type", errorType))
	kvs = append(kvs, myappTaskID.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.taskFailedCounterAttr())
	}
	m.inst.Add(ctx, incr, metric.WithAttributes(kvs...))
}
