// Code generated by weaver. DO NOT EDIT.
#![allow(deprecated)]
#[derive(Clone, Debug)]
pub enum HostEntityAttr {
    /// Opt-in: the convention records it only when a user asks for it.
    HostCpuCount(super::myappattr::HostCpuCountAttr),
    HostType(super::myappattr::HostTypeAttr),
}

impl From<HostEntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostEntityAttr) -> Self {
        match value {
            HostEntityAttr::HostCpuCount(value) => ::opentelemetry::KeyValue::from(value),
            HostEntityAttr::HostType(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// A host running the application.
///
/// Identified by its name across its lifetime.
/// Identifies the entity: `myapp.host.name`.
/// Describes the entity: `myapp.host.cpu.count`, `myapp.host.type`.
#[derive(Clone, Debug)]
pub struct HostEntity {
    r#myapp_host_name: super::myappattr::HostNameAttr,
    options: ::smallvec::SmallVec<[HostEntityAttr; 2]>,
}

impl HostEntity {
    pub fn new(r#myapp_host_name: super::myappattr::HostNameAttr, options: impl IntoIterator<Item = HostEntityAttr>) -> Self {
        Self {
            r#myapp_host_name,
            options: options.into_iter().collect(),
        }
    }

    pub fn attributes(&self) -> impl Iterator<Item = ::opentelemetry::KeyValue> + '_ {
        ::std::iter::empty()
            .chain(::std::iter::once_with(move || ::opentelemetry::KeyValue::from(self.r#myapp_host_name.clone())))
            .chain(self.options.iter().cloned().map(::opentelemetry::KeyValue::from))
    }
}

impl From<HostEntity> for ::opentelemetry_sdk::Resource {
    fn from(value: HostEntity) -> Self {
        let attributes = [
            ::opentelemetry::KeyValue::from(value.r#myapp_host_name),
        ].into_iter().chain(value.options.into_iter().map(::opentelemetry::KeyValue::from));
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(attributes, super::SCHEMA_URL)
            .build()
    }
}
#[derive(Clone, Debug)]
pub enum HostWorkerEntityAttr {
    /// Opt-in: the convention records it only when a user asks for it.
    HostCpuCount(super::myappattr::HostCpuCountAttr),
    HostType(super::myappattr::HostTypeAttr),
}

impl From<HostWorkerEntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostWorkerEntityAttr) -> Self {
        match value {
            HostWorkerEntityAttr::HostCpuCount(value) => ::opentelemetry::KeyValue::from(value),
            HostWorkerEntityAttr::HostType(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// A host dedicated to running worker processes.
///
/// Identified by its name across its lifetime.
/// Identifies the entity: `myapp.host.name`.
/// Describes the entity: `myapp.host.cpu.count`, `myapp.host.role`, `myapp.host.type`.
/// Refines `myapp.host`.
#[derive(Clone, Debug)]
pub struct HostWorkerEntity {
    r#myapp_host_name: super::myappattr::HostNameAttr,
    r#myapp_host_role: super::myappattr::HostRoleAttr,
    options: ::smallvec::SmallVec<[HostWorkerEntityAttr; 2]>,
}

impl HostWorkerEntity {
    pub fn new(r#myapp_host_name: super::myappattr::HostNameAttr, r#myapp_host_role: super::myappattr::HostRoleAttr, options: impl IntoIterator<Item = HostWorkerEntityAttr>) -> Self {
        Self {
            r#myapp_host_name,
            r#myapp_host_role,
            options: options.into_iter().collect(),
        }
    }

    pub fn attributes(&self) -> impl Iterator<Item = ::opentelemetry::KeyValue> + '_ {
        ::std::iter::empty()
            .chain(::std::iter::once_with(move || ::opentelemetry::KeyValue::from(self.r#myapp_host_name.clone())))
            .chain(::std::iter::once_with(move || ::opentelemetry::KeyValue::from(self.r#myapp_host_role.clone())))
            .chain(self.options.iter().cloned().map(::opentelemetry::KeyValue::from))
    }
}

impl From<HostWorkerEntity> for ::opentelemetry_sdk::Resource {
    fn from(value: HostWorkerEntity) -> Self {
        let attributes = [
            ::opentelemetry::KeyValue::from(value.r#myapp_host_name),
            ::opentelemetry::KeyValue::from(value.r#myapp_host_role),
        ].into_iter().chain(value.options.into_iter().map(::opentelemetry::KeyValue::from));
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(attributes, super::SCHEMA_URL)
            .build()
    }
}
#[derive(Clone, Debug)]
pub enum OptionalEntityAttr {
    QueueName(super::myappattr::QueueNameAttr),
    QueueSize(super::myappattr::QueueSizeAttr),
}

impl From<OptionalEntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: OptionalEntityAttr) -> Self {
        match value {
            OptionalEntityAttr::QueueName(value) => ::opentelemetry::KeyValue::from(value),
            OptionalEntityAttr::QueueSize(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// An entity with optional description only.
/// Identifies the entity: `myapp.queue.name`.
/// Describes the entity: `myapp.queue.size`.
#[derive(Clone, Debug, Default)]
pub struct OptionalEntity {
    options: ::smallvec::SmallVec<[OptionalEntityAttr; 2]>,
}

impl OptionalEntity {
    pub fn new(options: impl IntoIterator<Item = OptionalEntityAttr>) -> Self {
        Self {
            options: options.into_iter().collect(),
        }
    }

    pub fn attributes(&self) -> impl Iterator<Item = ::opentelemetry::KeyValue> + '_ {
        ::std::iter::empty()
            .chain(self.options.iter().cloned().map(::opentelemetry::KeyValue::from))
    }
}

impl From<OptionalEntity> for ::opentelemetry_sdk::Resource {
    fn from(value: OptionalEntity) -> Self {
        let attributes = [
        ].into_iter().chain(value.options.into_iter().map(::opentelemetry::KeyValue::from));
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(attributes, super::SCHEMA_URL)
            .build()
    }
}
#[derive(Clone, Debug)]
pub enum QueueEntityAttr {
    QueueSize(super::myappattr::QueueSizeAttr),
}

impl From<QueueEntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: QueueEntityAttr) -> Self {
        match value {
            QueueEntityAttr::QueueSize(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// A queue of tasks.
/// Identifies the entity: `myapp.queue.name`.
/// Describes the entity: `myapp.queue.size`.
#[derive(Clone, Debug)]
pub struct QueueEntity {
    r#myapp_queue_name: super::myappattr::QueueNameAttr,
    options: ::smallvec::SmallVec<[QueueEntityAttr; 1]>,
}

impl QueueEntity {
    pub fn new(r#myapp_queue_name: super::myappattr::QueueNameAttr, options: impl IntoIterator<Item = QueueEntityAttr>) -> Self {
        Self {
            r#myapp_queue_name,
            options: options.into_iter().collect(),
        }
    }

    pub fn attributes(&self) -> impl Iterator<Item = ::opentelemetry::KeyValue> + '_ {
        ::std::iter::empty()
            .chain(::std::iter::once_with(move || ::opentelemetry::KeyValue::from(self.r#myapp_queue_name.clone())))
            .chain(self.options.iter().cloned().map(::opentelemetry::KeyValue::from))
    }
}

impl From<QueueEntity> for ::opentelemetry_sdk::Resource {
    fn from(value: QueueEntity) -> Self {
        let attributes = [
            ::opentelemetry::KeyValue::from(value.r#myapp_queue_name),
        ].into_iter().chain(value.options.into_iter().map(::opentelemetry::KeyValue::from));
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(attributes, super::SCHEMA_URL)
            .build()
    }
}
