// Code generated by weaver. DO NOT EDIT.
#![allow(deprecated)]


#[derive(Clone, Debug)]
pub enum HostEntityAttr {

/// Opt-in: the convention records it only when a user asks for it.
    HostCpuCount(super::myappattr::HostCpuCountAttr),


    HostType(super::myappattr::HostTypeAttr),

}

impl HostEntityAttr {
    fn key_value(self) -> ::opentelemetry::KeyValue {
        match self {

            Self::HostCpuCount(value) => value.key_value(),

            Self::HostType(value) => value.key_value(),

        }
    }
}

/// A host running the application.
///
/// Identified by its name across its lifetime.
/// Identifies the entity: `myapp.host.name`.
/// Describes the entity: `myapp.host.cpu.count`, `myapp.host.type`.
#[derive(Clone, Debug, Default)]
pub struct HostEntity {
    attributes: Vec<::opentelemetry::KeyValue>,
}

impl HostEntity {
    pub fn new(r#myapp_host_name: super::myappattr::HostNameAttr, options: impl IntoIterator<Item = HostEntityAttr>) -> Self {
        let mut attributes = vec![

            r#myapp_host_name.key_value(),

        ];
        attributes.extend(options.into_iter().map(HostEntityAttr::key_value));
        Self { attributes }
    }

    pub fn attributes(&self) -> Vec<::opentelemetry::KeyValue> {
        self.attributes.clone()
    }

    pub fn resource(&self) -> ::opentelemetry_sdk::Resource {
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(self.attributes(), super::SCHEMA_URL)
            .build()
    }
}


#[derive(Clone, Debug)]
pub enum HostWorkerEntityAttr {

/// Opt-in: the convention records it only when a user asks for it.
    HostCpuCount(super::myappattr::HostCpuCountAttr),


    HostType(super::myappattr::HostTypeAttr),

}

impl HostWorkerEntityAttr {
    fn key_value(self) -> ::opentelemetry::KeyValue {
        match self {

            Self::HostCpuCount(value) => value.key_value(),

            Self::HostType(value) => value.key_value(),

        }
    }
}

/// A host dedicated to running worker processes.
///
/// Identified by its name across its lifetime.
/// Identifies the entity: `myapp.host.name`.
/// Describes the entity: `myapp.host.cpu.count`, `myapp.host.role`, `myapp.host.type`.
/// Refines `myapp.host`.
#[derive(Clone, Debug, Default)]
pub struct HostWorkerEntity {
    attributes: Vec<::opentelemetry::KeyValue>,
}

impl HostWorkerEntity {
    pub fn new(r#myapp_host_name: super::myappattr::HostNameAttr, r#myapp_host_role: super::myappattr::HostRoleAttr, options: impl IntoIterator<Item = HostWorkerEntityAttr>) -> Self {
        let mut attributes = vec![

            r#myapp_host_name.key_value(),

            r#myapp_host_role.key_value(),

        ];
        attributes.extend(options.into_iter().map(HostWorkerEntityAttr::key_value));
        Self { attributes }
    }

    pub fn attributes(&self) -> Vec<::opentelemetry::KeyValue> {
        self.attributes.clone()
    }

    pub fn resource(&self) -> ::opentelemetry_sdk::Resource {
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(self.attributes(), super::SCHEMA_URL)
            .build()
    }
}


#[derive(Clone, Debug)]
pub enum QueueEntityAttr {


    QueueSize(super::myappattr::QueueSizeAttr),

}

impl QueueEntityAttr {
    fn key_value(self) -> ::opentelemetry::KeyValue {
        match self {

            Self::QueueSize(value) => value.key_value(),

        }
    }
}

/// A queue of tasks.
/// Identifies the entity: `myapp.queue.name`.
/// Describes the entity: `myapp.queue.size`.
#[derive(Clone, Debug, Default)]
pub struct QueueEntity {
    attributes: Vec<::opentelemetry::KeyValue>,
}

impl QueueEntity {
    pub fn new(r#myapp_queue_name: super::myappattr::QueueNameAttr, options: impl IntoIterator<Item = QueueEntityAttr>) -> Self {
        let mut attributes = vec![

            r#myapp_queue_name.key_value(),

        ];
        attributes.extend(options.into_iter().map(QueueEntityAttr::key_value));
        Self { attributes }
    }

    pub fn attributes(&self) -> Vec<::opentelemetry::KeyValue> {
        self.attributes.clone()
    }

    pub fn resource(&self) -> ::opentelemetry_sdk::Resource {
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(self.attributes(), super::SCHEMA_URL)
            .build()
    }
}
