// Code generated by weaver. DO NOT EDIT.
#![allow(deprecated)]
#[derive(Clone, Debug)]
pub enum HostEntityAttr {
    /// Opt-in: the convention records it only when a user asks for it.
    HostCpuCount(super::myappattr::HostCpuCountAttr),
    HostType(super::myappattr::HostTypeAttr),
}

impl From<HostEntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostEntityAttr) -> Self {
        match value {
            HostEntityAttr::HostCpuCount(value) => ::opentelemetry::KeyValue::from(value),
            HostEntityAttr::HostType(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// A host running the application.
///
/// Identified by its name across its lifetime.
/// Identifies the entity: `myapp.host.name`.
/// Describes the entity: `myapp.host.cpu.count`, `myapp.host.type`.
#[derive(Clone, Debug, Default)]
pub struct HostEntity {
    attributes: Vec<::opentelemetry::KeyValue>,
}

impl HostEntity {
    pub fn new(r#myapp_host_name: super::myappattr::HostNameAttr, options: impl IntoIterator<Item = HostEntityAttr>) -> Self {
        let mut attributes = vec![
            ::opentelemetry::KeyValue::from(r#myapp_host_name),
        ];
        attributes.extend(options.into_iter().map(::opentelemetry::KeyValue::from));
        Self { attributes }
    }

    pub fn attributes(&self) -> Vec<::opentelemetry::KeyValue> {
        self.attributes.clone()
    }

    pub fn resource(&self) -> ::opentelemetry_sdk::Resource {
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(self.attributes(), super::SCHEMA_URL)
            .build()
    }
}
#[derive(Clone, Debug)]
pub enum HostWorkerEntityAttr {
    /// Opt-in: the convention records it only when a user asks for it.
    HostCpuCount(super::myappattr::HostCpuCountAttr),
    HostType(super::myappattr::HostTypeAttr),
}

impl From<HostWorkerEntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostWorkerEntityAttr) -> Self {
        match value {
            HostWorkerEntityAttr::HostCpuCount(value) => ::opentelemetry::KeyValue::from(value),
            HostWorkerEntityAttr::HostType(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// A host dedicated to running worker processes.
///
/// Identified by its name across its lifetime.
/// Identifies the entity: `myapp.host.name`.
/// Describes the entity: `myapp.host.cpu.count`, `myapp.host.role`, `myapp.host.type`.
/// Refines `myapp.host`.
#[derive(Clone, Debug, Default)]
pub struct HostWorkerEntity {
    attributes: Vec<::opentelemetry::KeyValue>,
}

impl HostWorkerEntity {
    pub fn new(r#myapp_host_name: super::myappattr::HostNameAttr, r#myapp_host_role: super::myappattr::HostRoleAttr, options: impl IntoIterator<Item = HostWorkerEntityAttr>) -> Self {
        let mut attributes = vec![
            ::opentelemetry::KeyValue::from(r#myapp_host_name),
            ::opentelemetry::KeyValue::from(r#myapp_host_role),
        ];
        attributes.extend(options.into_iter().map(::opentelemetry::KeyValue::from));
        Self { attributes }
    }

    pub fn attributes(&self) -> Vec<::opentelemetry::KeyValue> {
        self.attributes.clone()
    }

    pub fn resource(&self) -> ::opentelemetry_sdk::Resource {
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(self.attributes(), super::SCHEMA_URL)
            .build()
    }
}
#[derive(Clone, Debug)]
pub enum QueueEntityAttr {
    QueueSize(super::myappattr::QueueSizeAttr),
}

impl From<QueueEntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: QueueEntityAttr) -> Self {
        match value {
            QueueEntityAttr::QueueSize(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// A queue of tasks.
/// Identifies the entity: `myapp.queue.name`.
/// Describes the entity: `myapp.queue.size`.
#[derive(Clone, Debug, Default)]
pub struct QueueEntity {
    attributes: Vec<::opentelemetry::KeyValue>,
}

impl QueueEntity {
    pub fn new(r#myapp_queue_name: super::myappattr::QueueNameAttr, options: impl IntoIterator<Item = QueueEntityAttr>) -> Self {
        let mut attributes = vec![
            ::opentelemetry::KeyValue::from(r#myapp_queue_name),
        ];
        attributes.extend(options.into_iter().map(::opentelemetry::KeyValue::from));
        Self { attributes }
    }

    pub fn attributes(&self) -> Vec<::opentelemetry::KeyValue> {
        self.attributes.clone()
    }

    pub fn resource(&self) -> ::opentelemetry_sdk::Resource {
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(self.attributes(), super::SCHEMA_URL)
            .build()
    }
}
