// Generated by OpenTelemetry Weaver.
/// Number of CPUs the host has.
#[deprecated(note = "Use `myapp.host.cpu.logical_count` instead.")]
#[derive(Debug, Clone, PartialEq)]
pub struct HostCpuCountAttr(i64);

#[allow(deprecated)]
impl HostCpuCountAttr {
    pub const KEY: &'static str = "myapp.host.cpu.count";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<i64> for HostCpuCountAttr {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<HostCpuCountAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostCpuCountAttr) -> Self {
        value.key_value()
    }
}
/// Name of the host.
#[derive(Debug, Clone, PartialEq)]
pub struct HostNameAttr(String);

#[allow(deprecated)]
impl HostNameAttr {
    pub const KEY: &'static str = "myapp.host.name";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for HostNameAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for HostNameAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<HostNameAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostNameAttr) -> Self {
        value.key_value()
    }
}
/// Role the host plays in the cluster.
#[derive(Debug, Clone, PartialEq)]
pub struct HostRoleAttr(String);

#[allow(deprecated)]
impl HostRoleAttr {
    pub const KEY: &'static str = "myapp.host.role";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for HostRoleAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for HostRoleAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<HostRoleAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostRoleAttr) -> Self {
        value.key_value()
    }
}
/// Type of the host.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum HostTypeAttr {
    /// A physical host.
    Physical,
    /// A virtual host.
    Virtual,
}

#[allow(deprecated)]
impl HostTypeAttr {
    pub const KEY: &'static str = "myapp.host.type";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: String = match self {
            Self::Physical => "physical".into(),
            Self::Virtual => "virtual".into(),
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<HostTypeAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostTypeAttr) -> Self {
        value.key_value()
    }
}
/// Name of the queue.
#[derive(Debug, Clone, PartialEq)]
pub struct QueueNameAttr(String);

#[allow(deprecated)]
impl QueueNameAttr {
    pub const KEY: &'static str = "myapp.queue.name";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for QueueNameAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for QueueNameAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<QueueNameAttr> for ::opentelemetry::KeyValue {
    fn from(value: QueueNameAttr) -> Self {
        value.key_value()
    }
}
/// Number of items currently in the queue.
#[derive(Debug, Clone, PartialEq)]
pub struct QueueSizeAttr(i64);

#[allow(deprecated)]
impl QueueSizeAttr {
    pub const KEY: &'static str = "myapp.queue.size";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<i64> for QueueSizeAttr {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<QueueSizeAttr> for ::opentelemetry::KeyValue {
    fn from(value: QueueSizeAttr) -> Self {
        value.key_value()
    }
}
