// Generated by OpenTelemetry Weaver.
/// Number of CPUs the host has.
#[deprecated(note = "Use `myapp.host.cpu.logical_count` instead.")]
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct HostCpuCountAttr(i64);

#[allow(deprecated)]
impl HostCpuCountAttr {
    pub const KEY: &'static str = "myapp.host.cpu.count";
}

#[allow(deprecated)]
impl From<i64> for HostCpuCountAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for HostCpuCountAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<HostCpuCountAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: HostCpuCountAttr) -> Self {
        ::opentelemetry::KeyValue::new(HostCpuCountAttr::KEY, value.0)
    }
}
/// Name of the host.
#[derive(Debug, Clone, PartialEq)]
pub struct HostNameAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl HostNameAttr {
    pub const KEY: &'static str = "myapp.host.name";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for HostNameAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for HostNameAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for HostNameAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for HostNameAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for HostNameAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<HostNameAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: HostNameAttr) -> Self {
        ::opentelemetry::KeyValue::new(HostNameAttr::KEY, value.0)
    }
}
/// Role the host plays in the cluster.
#[derive(Debug, Clone, PartialEq)]
pub struct HostRoleAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl HostRoleAttr {
    pub const KEY: &'static str = "myapp.host.role";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for HostRoleAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for HostRoleAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for HostRoleAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for HostRoleAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for HostRoleAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<HostRoleAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: HostRoleAttr) -> Self {
        ::opentelemetry::KeyValue::new(HostRoleAttr::KEY, value.0)
    }
}
/// Type of the host.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum HostTypeAttr {
    /// A physical host.
    Physical,
    /// A virtual host.
    Virtual,
}

#[allow(deprecated)]
impl HostTypeAttr {
    pub const KEY: &'static str = "myapp.host.type";
}

#[allow(deprecated)]
impl AsRef<str> for HostTypeAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            HostTypeAttr::Physical => "physical",
            HostTypeAttr::Virtual => "virtual",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for HostTypeAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<HostTypeAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: HostTypeAttr) -> Self {
        let value: &'static str = match value {
            HostTypeAttr::Physical => "physical",
            HostTypeAttr::Virtual => "virtual",
        };
        ::opentelemetry::KeyValue::new(HostTypeAttr::KEY, value)
    }
}
/// Name of the queue.
#[derive(Debug, Clone, PartialEq)]
pub struct QueueNameAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl QueueNameAttr {
    pub const KEY: &'static str = "myapp.queue.name";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for QueueNameAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for QueueNameAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for QueueNameAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for QueueNameAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for QueueNameAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<QueueNameAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: QueueNameAttr) -> Self {
        ::opentelemetry::KeyValue::new(QueueNameAttr::KEY, value.0)
    }
}
/// Number of items currently in the queue.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct QueueSizeAttr(i64);

#[allow(deprecated)]
impl QueueSizeAttr {
    pub const KEY: &'static str = "myapp.queue.size";
}

#[allow(deprecated)]
impl From<i64> for QueueSizeAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for QueueSizeAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<QueueSizeAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: QueueSizeAttr) -> Self {
        ::opentelemetry::KeyValue::new(QueueSizeAttr::KEY, value.0)
    }
}
