// Generated by OpenTelemetry Weaver.
/// How the user was authenticated.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum MethodAttr {
    /// A password was checked.
    Password,
    /// A bearer token was checked.
    Token,
}

#[allow(deprecated)]
impl MethodAttr {
    pub const KEY: &'static str = "auth.method";
}

#[allow(deprecated)]
impl AsRef<str> for MethodAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            MethodAttr::Password => "password",
            MethodAttr::Token => "token",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for MethodAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: MethodAttr) -> Self {
        let value: &'static str = match value {
            MethodAttr::Password => "password",
            MethodAttr::Token => "token",
        };
        ::opentelemetry::KeyValue::new(MethodAttr::KEY, value)
    }
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: MethodAttr) -> Self {
        let value: &'static str = match value {
            MethodAttr::Password => "password",
            MethodAttr::Token => "token",
        };
        value.into()
    }
}
/// Identifier of the authenticated user.
#[derive(Debug, Clone, PartialEq)]
pub struct UserIdAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl UserIdAttr {
    pub const KEY: &'static str = "auth.user.id";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for UserIdAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for UserIdAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for UserIdAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for UserIdAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for UserIdAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<UserIdAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: UserIdAttr) -> Self {
        ::opentelemetry::KeyValue::new(UserIdAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<UserIdAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: UserIdAttr) -> Self {
        value.0.into()
    }
}
