// Generated by OpenTelemetry Weaver.
/// How the user was authenticated.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum MethodAttr {
    /// A password was checked.
    Password,
    /// A bearer token was checked.
    Token,
}

#[allow(deprecated)]
impl MethodAttr {
    pub const KEY: &'static str = "auth.method";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: String = match self {
            Self::Password => "password".into(),
            Self::Token => "token".into(),
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::KeyValue {
    fn from(value: MethodAttr) -> Self {
        value.key_value()
    }
}
/// Identifier of the authenticated user.
#[derive(Debug, Clone, PartialEq)]
pub struct UserIdAttr(String);

#[allow(deprecated)]
impl UserIdAttr {
    pub const KEY: &'static str = "auth.user.id";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for UserIdAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for UserIdAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<UserIdAttr> for ::opentelemetry::KeyValue {
    fn from(value: UserIdAttr) -> Self {
        value.key_value()
    }
}
