// Generated by OpenTelemetry Weaver.
/// Who assigned the task.
///
/// The scheduler sets it on every task it passes along to `myapp.task.state`. Workers never set it themselves.
#[derive(Debug, Clone, PartialEq)]
pub struct AssignedByAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl AssignedByAttr {
    pub const KEY: &'static str = "myapp.task.assigned_by";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for AssignedByAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for AssignedByAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for AssignedByAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for AssignedByAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for AssignedByAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<AssignedByAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: AssignedByAttr) -> Self {
        ::opentelemetry::KeyValue::new(AssignedByAttr::KEY, value.0)
    }
}
/// Whether the task was cancelled.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct CancelledAttr(bool);

#[allow(deprecated)]
impl CancelledAttr {
    pub const KEY: &'static str = "myapp.task.cancelled";
}

#[allow(deprecated)]
impl From<bool> for CancelledAttr {
    #[inline]
    fn from(value: bool) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for CancelledAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<CancelledAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: CancelledAttr) -> Self {
        ::opentelemetry::KeyValue::new(CancelledAttr::KEY, value.0)
    }
}
/// Unique identifier of the task.
///
/// The identifier is assigned by the scheduler and stays stable across retries.
#[derive(Debug, Clone, PartialEq)]
pub struct IdAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl IdAttr {
    pub const KEY: &'static str = "myapp.task.id";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for IdAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for IdAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for IdAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for IdAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for IdAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<IdAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: IdAttr) -> Self {
        ::opentelemetry::KeyValue::new(IdAttr::KEY, value.0)
    }
}
/// Whether the scheduler may preempt the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum PreemptibleAttr {
    /// The scheduler may preempt the task.
    Allowed,
    /// The task runs to completion.
    Forbidden,
}

#[allow(deprecated)]
impl PreemptibleAttr {
    pub const KEY: &'static str = "myapp.task.preemptible";
}

#[allow(deprecated)]
impl ::std::fmt::Display for PreemptibleAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let value: bool = match self {
            PreemptibleAttr::Allowed => true,
            PreemptibleAttr::Forbidden => false,
        };
        ::std::fmt::Display::fmt(&value, formatter)
    }
}

#[allow(deprecated)]
impl From<PreemptibleAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: PreemptibleAttr) -> Self {
        let value: bool = match value {
            PreemptibleAttr::Allowed => true,
            PreemptibleAttr::Forbidden => false,
        };
        ::opentelemetry::KeyValue::new(PreemptibleAttr::KEY, value)
    }
}
/// Number of times the task was retried.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct RetriesAttr(i64);

#[allow(deprecated)]
impl RetriesAttr {
    pub const KEY: &'static str = "myapp.task.retries";
}

#[allow(deprecated)]
impl From<i64> for RetriesAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for RetriesAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<RetriesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: RetriesAttr) -> Self {
        ::opentelemetry::KeyValue::new(RetriesAttr::KEY, value.0)
    }
}
/// Fraction of tasks whose telemetry is sampled.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum SampleRateAttr {
    /// One task in ten is sampled.
    Tenth,
    /// Every task is sampled.
    All,
}

#[allow(deprecated)]
impl SampleRateAttr {
    pub const KEY: &'static str = "myapp.task.sample_rate";
}

#[allow(deprecated)]
impl ::std::fmt::Display for SampleRateAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let value: f64 = match self {
            SampleRateAttr::Tenth => 0.1_f64,
            SampleRateAttr::All => 1_f64,
        };
        ::std::fmt::Display::fmt(&value, formatter)
    }
}

#[allow(deprecated)]
impl From<SampleRateAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: SampleRateAttr) -> Self {
        let value: f64 = match value {
            SampleRateAttr::Tenth => 0.1_f64,
            SampleRateAttr::All => 1_f64,
        };
        ::opentelemetry::KeyValue::new(SampleRateAttr::KEY, value)
    }
}
/// Shards the task touched.
#[derive(Debug, Clone, PartialEq)]
pub struct ShardIdsAttr(Vec<i64>);

#[allow(deprecated)]
impl ShardIdsAttr {
    pub const KEY: &'static str = "myapp.task.shard_ids";
}

#[allow(deprecated)]
impl From<Vec<i64>> for ShardIdsAttr {
    #[inline]
    fn from(value: Vec<i64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[i64]> for ShardIdsAttr {
    #[inline]
    fn as_ref(&self) -> &[i64] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for ShardIdsAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<ShardIdsAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: ShardIdsAttr) -> Self {
        ::opentelemetry::KeyValue::new(ShardIdsAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(value.0)))
    }
}
/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum StateAttr {
    /// The task is waiting to run.
    Queued,
    /// The task is running.
    ///
    /// A task stays running until it finishes or is cancelled.
    Running,
}

#[allow(deprecated)]
impl StateAttr {
    pub const KEY: &'static str = "myapp.task.state";
}

#[allow(deprecated)]
impl AsRef<str> for StateAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            StateAttr::Queued => "queued",
            StateAttr::Running => "running",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for StateAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<StateAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: StateAttr) -> Self {
        let value: &'static str = match value {
            StateAttr::Queued => "queued",
            StateAttr::Running => "running",
        };
        ::opentelemetry::KeyValue::new(StateAttr::KEY, value)
    }
}
/// Tags attached to the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TagsAttr(Vec<::opentelemetry::StringValue>);

#[allow(deprecated)]
impl TagsAttr {
    pub const KEY: &'static str = "myapp.task.tags";
}

#[allow(deprecated)]
impl From<Vec<::opentelemetry::StringValue>> for TagsAttr {
    #[inline]
    fn from(value: Vec<::opentelemetry::StringValue>) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<Vec<String>> for TagsAttr {
    fn from(value: Vec<String>) -> Self {
        Self(value.into_iter().map(Into::into).collect())
    }
}

#[allow(deprecated)]
impl AsRef<[::opentelemetry::StringValue]> for TagsAttr {
    #[inline]
    fn as_ref(&self) -> &[::opentelemetry::StringValue] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for TagsAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            write!(formatter, "\"{value}\"")?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<TagsAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: TagsAttr) -> Self {
        ::opentelemetry::KeyValue::new(TagsAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::String(value.0)))
    }
}
