// Generated by OpenTelemetry Weaver.
/// Who assigned the task.
///
/// The scheduler sets it on every task it passes along to `myapp.task.state`. Workers never set it themselves.
#[derive(Debug, Clone, PartialEq)]
pub struct AssignedByAttr(String);

#[allow(deprecated)]
impl AssignedByAttr {
    pub const KEY: &'static str = "myapp.task.assigned_by";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for AssignedByAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for AssignedByAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<AssignedByAttr> for ::opentelemetry::KeyValue {
    fn from(value: AssignedByAttr) -> Self {
        value.key_value()
    }
}
/// Whether the task was cancelled.
#[derive(Debug, Clone, PartialEq)]
pub struct CancelledAttr(bool);

#[allow(deprecated)]
impl CancelledAttr {
    pub const KEY: &'static str = "myapp.task.cancelled";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<bool> for CancelledAttr {
    fn from(value: bool) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<CancelledAttr> for ::opentelemetry::KeyValue {
    fn from(value: CancelledAttr) -> Self {
        value.key_value()
    }
}
/// Unique identifier of the task.
///
/// The identifier is assigned by the scheduler and stays stable across retries.
#[derive(Debug, Clone, PartialEq)]
pub struct IdAttr(String);

#[allow(deprecated)]
impl IdAttr {
    pub const KEY: &'static str = "myapp.task.id";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for IdAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for IdAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<IdAttr> for ::opentelemetry::KeyValue {
    fn from(value: IdAttr) -> Self {
        value.key_value()
    }
}
/// Whether the scheduler may preempt the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum PreemptibleAttr {
    /// The scheduler may preempt the task.
    Allowed,
    /// The task runs to completion.
    Forbidden,
}

#[allow(deprecated)]
impl PreemptibleAttr {
    pub const KEY: &'static str = "myapp.task.preemptible";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: bool = match self {
            Self::Allowed => true,
            Self::Forbidden => false,
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<PreemptibleAttr> for ::opentelemetry::KeyValue {
    fn from(value: PreemptibleAttr) -> Self {
        value.key_value()
    }
}
/// Number of times the task was retried.
#[derive(Debug, Clone, PartialEq)]
pub struct RetriesAttr(i64);

#[allow(deprecated)]
impl RetriesAttr {
    pub const KEY: &'static str = "myapp.task.retries";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<i64> for RetriesAttr {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<RetriesAttr> for ::opentelemetry::KeyValue {
    fn from(value: RetriesAttr) -> Self {
        value.key_value()
    }
}
/// Fraction of tasks whose telemetry is sampled.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum SampleRateAttr {
    /// One task in ten is sampled.
    Tenth,
    /// Every task is sampled.
    All,
}

#[allow(deprecated)]
impl SampleRateAttr {
    pub const KEY: &'static str = "myapp.task.sample_rate";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: f64 = match self {
            Self::Tenth => 0.1_f64,
            Self::All => 1_f64,
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<SampleRateAttr> for ::opentelemetry::KeyValue {
    fn from(value: SampleRateAttr) -> Self {
        value.key_value()
    }
}
/// Shards the task touched.
#[derive(Debug, Clone, PartialEq)]
pub struct ShardIdsAttr(Vec<i64>);

#[allow(deprecated)]
impl ShardIdsAttr {
    pub const KEY: &'static str = "myapp.task.shard_ids";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(self.0)))
    }
}

#[allow(deprecated)]
impl From<Vec<i64>> for ShardIdsAttr {
    fn from(value: Vec<i64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<ShardIdsAttr> for ::opentelemetry::KeyValue {
    fn from(value: ShardIdsAttr) -> Self {
        value.key_value()
    }
}
/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum StateAttr {
    /// The task is waiting to run.
    Queued,
    /// The task is running.
    ///
    /// A task stays running until it finishes or is cancelled.
    Running,
}

#[allow(deprecated)]
impl StateAttr {
    pub const KEY: &'static str = "myapp.task.state";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: String = match self {
            Self::Queued => "queued".into(),
            Self::Running => "running".into(),
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<StateAttr> for ::opentelemetry::KeyValue {
    fn from(value: StateAttr) -> Self {
        value.key_value()
    }
}
/// Tags attached to the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TagsAttr(Vec<String>);

#[allow(deprecated)]
impl TagsAttr {
    pub const KEY: &'static str = "myapp.task.tags";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::String(self.0.into_iter().map(Into::into).collect())))
    }
}

#[allow(deprecated)]
impl From<Vec<String>> for TagsAttr {
    fn from(value: Vec<String>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TagsAttr> for ::opentelemetry::KeyValue {
    fn from(value: TagsAttr) -> Self {
        value.key_value()
    }
}
