// Generated by OpenTelemetry Weaver.
/// A synthetic boolean value.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct FlagAttr(bool);

#[allow(deprecated)]
impl FlagAttr {
    pub const KEY: &'static str = "probe.flag";
}

#[allow(deprecated)]
impl From<bool> for FlagAttr {
    #[inline]
    fn from(value: bool) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for FlagAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<FlagAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: FlagAttr) -> Self {
        ::opentelemetry::KeyValue::new(FlagAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<FlagAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: FlagAttr) -> Self {
        value.0.into()
    }
}
/// A synthetic fractional value.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct FractionAttr(f64);

#[allow(deprecated)]
impl FractionAttr {
    pub const KEY: &'static str = "probe.fraction";
}

#[allow(deprecated)]
impl From<f64> for FractionAttr {
    #[inline]
    fn from(value: f64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for FractionAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<FractionAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: FractionAttr) -> Self {
        ::opentelemetry::KeyValue::new(FractionAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<FractionAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: FractionAttr) -> Self {
        value.0.into()
    }
}
/// A synthetic text value.
#[derive(Debug, Clone, PartialEq)]
pub struct LabelAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl LabelAttr {
    pub const KEY: &'static str = "probe.label";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for LabelAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for LabelAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for LabelAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for LabelAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for LabelAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<LabelAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: LabelAttr) -> Self {
        ::opentelemetry::KeyValue::new(LabelAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<LabelAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: LabelAttr) -> Self {
        value.0.into()
    }
}
/// Optional numeric measurement identity.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct OptionalAttr(i64);

#[allow(deprecated)]
impl OptionalAttr {
    pub const KEY: &'static str = "probe.optional";
}

#[allow(deprecated)]
impl From<i64> for OptionalAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for OptionalAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<OptionalAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: OptionalAttr) -> Self {
        ::opentelemetry::KeyValue::new(OptionalAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<OptionalAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: OptionalAttr) -> Self {
        value.0.into()
    }
}
/// Required numeric measurement identity.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct RequiredAttr(i64);

#[allow(deprecated)]
impl RequiredAttr {
    pub const KEY: &'static str = "probe.required";
}

#[allow(deprecated)]
impl From<i64> for RequiredAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for RequiredAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<RequiredAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: RequiredAttr) -> Self {
        ::opentelemetry::KeyValue::new(RequiredAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<RequiredAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: RequiredAttr) -> Self {
        value.0.into()
    }
}
/// Numeric values attached to an event.
#[derive(Debug, Clone, PartialEq)]
pub struct ValuesAttr(Vec<i64>);

#[allow(deprecated)]
impl ValuesAttr {
    pub const KEY: &'static str = "probe.values";
}

#[allow(deprecated)]
impl From<Vec<i64>> for ValuesAttr {
    #[inline]
    fn from(value: Vec<i64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[i64]> for ValuesAttr {
    #[inline]
    fn as_ref(&self) -> &[i64] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for ValuesAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<ValuesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: ValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(ValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(value.0)))
    }
}

#[allow(deprecated)]
impl From<ValuesAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: ValuesAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}
