// Generated by OpenTelemetry Weaver.
/// Optional numeric measurement identity.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct OptionalAttr(i64);

#[allow(deprecated)]
impl OptionalAttr {
    pub const KEY: &'static str = "probe.optional";
}

#[allow(deprecated)]
impl From<i64> for OptionalAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for OptionalAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<OptionalAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: OptionalAttr) -> Self {
        ::opentelemetry::KeyValue::new(OptionalAttr::KEY, value.0)
    }
}
/// Required numeric measurement identity.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct RequiredAttr(i64);

#[allow(deprecated)]
impl RequiredAttr {
    pub const KEY: &'static str = "probe.required";
}

#[allow(deprecated)]
impl From<i64> for RequiredAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for RequiredAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<RequiredAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: RequiredAttr) -> Self {
        ::opentelemetry::KeyValue::new(RequiredAttr::KEY, value.0)
    }
}
/// Numeric values attached to an event.
#[derive(Debug, Clone, PartialEq)]
pub struct ValuesAttr(Vec<i64>);

#[allow(deprecated)]
impl ValuesAttr {
    pub const KEY: &'static str = "probe.values";
}

#[allow(deprecated)]
impl From<Vec<i64>> for ValuesAttr {
    #[inline]
    fn from(value: Vec<i64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[i64]> for ValuesAttr {
    #[inline]
    fn as_ref(&self) -> &[i64] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for ValuesAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<ValuesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: ValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(ValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(value.0)))
    }
}
