// Code generated by weaver. DO NOT EDIT.

package authattr

import "go.opentelemetry.io/otel/attribute"

// levelKey is the attribute key of `auth.level`.
const levelKey = attribute.Key("auth.level")

// LevelAttr is a value of `auth.level`.
//
// Assurance level of the authentication.
type LevelAttr struct{ value int }

// Key is the attribute key, for filters and views that need it.
func (LevelAttr) Key() attribute.Key {
	return levelKey
}

// KeyValue is the `auth.level` attribute set to this value.
func (v LevelAttr) KeyValue() attribute.KeyValue {
	return levelKey.Int(v.value)
}

var (
	// LevelLow is the 1 member of `auth.level`.
	//
	// Single factor.
	LevelLow = LevelAttr{value: 1}

	// LevelHigh is the 2 member of `auth.level`.
	//
	// Multiple factors.
	LevelHigh = LevelAttr{value: 2}
)

// methodKey is the attribute key of `auth.method`.
const methodKey = attribute.Key("auth.method")

// MethodAttr is a value of `auth.method`.
//
// How the user was authenticated.
type MethodAttr struct{ value string }

// Key is the attribute key, for filters and views that need it.
func (MethodAttr) Key() attribute.Key {
	return methodKey
}

// KeyValue is the `auth.method` attribute set to this value.
func (v MethodAttr) KeyValue() attribute.KeyValue {
	return methodKey.String(v.value)
}

var (
	// MethodPassword is the "password" member of `auth.method`.
	//
	// A password was checked.
	MethodPassword = MethodAttr{value: "password"}

	// MethodToken is the "token" member of `auth.method`.
	//
	// A bearer token was checked.
	MethodToken = MethodAttr{value: "token"}
)

// userIDKey is the attribute key of `auth.user.id`.
const userIDKey = attribute.Key("auth.user.id")

// UserIDAttr is a value of `auth.user.id`.
//
// Identifier of the authenticated user.
type UserIDAttr struct{ value string }

// NewUserIDAttr returns a value of `auth.user.id`.
func NewUserIDAttr(value string) UserIDAttr {
	return UserIDAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (UserIDAttr) Key() attribute.Key {
	return userIDKey
}

// KeyValue is the `auth.user.id` attribute set to this value.
func (v UserIDAttr) KeyValue() attribute.KeyValue {
	return userIDKey.String(v.value)
}
