// Code generated by weaver. DO NOT EDIT.

package heartbeatattr

import "go.opentelemetry.io/otel/attribute"

// sequenceKey is the attribute key of `heartbeat.sequence`.
const sequenceKey = attribute.Key("heartbeat.sequence")

// SequenceAttr is a value of `heartbeat.sequence`.
//
// Sequence number of the heartbeat.
type SequenceAttr struct{ value int }

// NewSequenceAttr returns a value of `heartbeat.sequence`.
func NewSequenceAttr(value int) SequenceAttr {
	return SequenceAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (SequenceAttr) Key() attribute.Key {
	return sequenceKey
}

// KeyValue is the `heartbeat.sequence` attribute set to this value.
func (v SequenceAttr) KeyValue() attribute.KeyValue {
	return sequenceKey.Int(v.value)
}

// sourceKey is the attribute key of `heartbeat.source`.
const sourceKey = attribute.Key("heartbeat.source")

// SourceAttr is a value of `heartbeat.source`.
//
// Name of the component that sent the heartbeat.
type SourceAttr struct{ value string }

// NewSourceAttr returns a value of `heartbeat.source`.
func NewSourceAttr(value string) SourceAttr {
	return SourceAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (SourceAttr) Key() attribute.Key {
	return sourceKey
}

// KeyValue is the `heartbeat.source` attribute set to this value.
func (v SourceAttr) KeyValue() attribute.KeyValue {
	return sourceKey.String(v.value)
}
