// Generated by OpenTelemetry Weaver.
/// Literal escape sequences.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum LiteralAttr {
    /// Literal escape sequences.
    Literal,
    /// Actual controls and escaped text.
    Controls,
}

#[allow(deprecated)]
impl LiteralAttr {
    pub const KEY: &'static str = "demo.literal";
}

#[allow(deprecated)]
impl AsRef<str> for LiteralAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            LiteralAttr::Literal => "backspace\\b formfeed\\f unicode\\u1234 doubled\\\\b tripled\\\\\\u0000",
            LiteralAttr::Controls => "backspace\u{0008} formfeed\u{000c} unicode\u{0001} slash\\b",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for LiteralAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<LiteralAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: LiteralAttr) -> Self {
        let value: &'static str = match value {
            LiteralAttr::Literal => "backspace\\b formfeed\\f unicode\\u1234 doubled\\\\b tripled\\\\\\u0000",
            LiteralAttr::Controls => "backspace\u{0008} formfeed\u{000c} unicode\u{0001} slash\\b",
        };
        ::opentelemetry::KeyValue::new(LiteralAttr::KEY, value)
    }
}

#[allow(deprecated)]
impl From<LiteralAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: LiteralAttr) -> Self {
        let value: &'static str = match value {
            LiteralAttr::Literal => "backspace\\b formfeed\\f unicode\\u1234 doubled\\\\b tripled\\\\\\u0000",
            LiteralAttr::Controls => "backspace\u{0008} formfeed\u{000c} unicode\u{0001} slash\\b",
        };
        value.into()
    }
}
