// Generated by OpenTelemetry Weaver.
/// Literal escape sequences.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum LiteralAttr {
    /// Literal escape sequences.
    Literal,
    /// Actual controls and escaped text.
    Controls,
}

#[allow(deprecated)]
impl LiteralAttr {
    pub const KEY: &'static str = "demo.literal";
}

#[allow(deprecated)]
impl From<LiteralAttr> for ::opentelemetry::KeyValue {
    fn from(value: LiteralAttr) -> Self {
        let value: String = match value {
            LiteralAttr::Literal => "backspace\\b formfeed\\f unicode\\u1234 doubled\\\\b tripled\\\\\\u0000".into(),
            LiteralAttr::Controls => "backspace\u{0008} formfeed\u{000c} unicode\u{0001} slash\\b".into(),
        };
        ::opentelemetry::KeyValue::new(LiteralAttr::KEY, value)
    }
}
