// Generated by OpenTelemetry Weaver.


pub const SCHEMA_URL: &str = "https://example.com/schemas/escaping/1.0.0";

pub mod demoattr {

    /// Literal escape sequences.
    #[derive(Debug, Clone, PartialEq, Copy)]

    pub enum LiteralAttr {

        /// Literal escape sequences.
        Literal,

        /// Actual controls and escaped text.
        Controls,

    }


    #[allow(deprecated)]
    impl LiteralAttr {
        pub const KEY: &'static str = "demo.literal";


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            let value: String = match self {

                Self::Literal => "backspace\\b formfeed\\f unicode\\u1234 doubled\\\\b tripled\\\\\\u0000".into(),

                Self::Controls => "backspace\u{0008} formfeed\u{000c} unicode\u{0001} slash\\b".into(),

            };
            ::opentelemetry::KeyValue::new(Self::KEY, value)

        }
    }

    #[allow(deprecated)]
    impl From<LiteralAttr> for ::opentelemetry::KeyValue {
        fn from(value: LiteralAttr) -> Self {
            value.key_value()
        }
    }

}


pub mod meter;



pub mod demometric;
