// Code generated by weaver. DO NOT EDIT.

package myappmetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	acmeconv "example.com/acme/acmeconv/v1.2.0"
	"example.com/acme/acmeconv/v1.2.0/myappattr"
)

// TaskStartedCounter is `myapp.task.started`.
//
// Number of tasks started.
type TaskStartedCounter struct{ inst metric.Int64Counter }

// NewTaskStartedCounter creates the `myapp.task.started` instrument from
// meter.
func NewTaskStartedCounter(meter acmeconv.Meter) (TaskStartedCounter, error) {
	inst, err := meter.MetricMeter().Int64Counter(
		"myapp.task.started",
		metric.WithDescription("Number of tasks started."),
		metric.WithUnit("{task}"),
	)
	if err != nil {
		return TaskStartedCounter{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.started", err)
	}
	return TaskStartedCounter{inst: inst}, nil
}

// Add records one `myapp.task.started` measurement. The zero
// TaskStartedCounter records nothing.
func (m TaskStartedCounter) Add(ctx context.Context, incr int64, myappTaskState myappattr.TaskStateAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskState.KeyValue())
	m.inst.Add(ctx, incr, metric.WithAttributes(kvs...))
}

// TaskStartedCounterObserver records `myapp.task.started` observations from
// the callback of a TaskStartedObservableCounter. The zero
// TaskStartedCounterObserver records nothing.
type TaskStartedCounterObserver struct {
	o metric.Int64Observer
}

// Observe records one `myapp.task.started` observation.
func (o TaskStartedCounterObserver) Observe(value int64, myappTaskState myappattr.TaskStateAttr) {
	if o.o == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1)
	kvs = append(kvs, myappTaskState.KeyValue())
	o.o.Observe(value, metric.WithAttributes(kvs...))
}

// TaskStartedCounterCallback observes `myapp.task.started` through o on
// every collection of a TaskStartedObservableCounter.
//
// An error it returns is returned by the collection that ran it, and the
// observations made before it returned are still recorded.
type TaskStartedCounterCallback func(ctx context.Context, o TaskStartedCounterObserver) error

// TaskStartedObservableCounter is the asynchronous form of
// TaskStartedCounter, observed through the callback it was created with.
type TaskStartedObservableCounter struct {
	inst metric.Int64ObservableCounter
}

// NewTaskStartedObservableCounter creates the `myapp.task.started`
// instrument from meter and registers callback to observe it on every
// collection.
func NewTaskStartedObservableCounter(meter acmeconv.Meter, callback TaskStartedCounterCallback) (TaskStartedObservableCounter, error) {
	if callback == nil {
		return TaskStartedObservableCounter{}, fmt.Errorf("create the %s instrument: the callback is nil", "myapp.task.started")
	}
	inst, err := meter.MetricMeter().Int64ObservableCounter(
		"myapp.task.started",
		metric.WithDescription("Number of tasks started."),
		metric.WithUnit("{task}"),
		metric.WithInt64Callback(func(ctx context.Context, o metric.Int64Observer) error {
			return callback(ctx, TaskStartedCounterObserver{o: o})
		}),
	)
	if err != nil {
		return TaskStartedObservableCounter{}, fmt.Errorf("create the %s instrument: %w", "myapp.task.started", err)
	}
	return TaskStartedObservableCounter{inst: inst}, nil
}
