// Code generated by weaver. DO NOT EDIT.

package heartbeatspan

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"go.opentelemetry.io/otel/trace/noop"

	"example.com/semconv/heartbeatattr"
	"example.com/semconv/semconvtracer"
)

// StartAttr is an attribute Start accepts in addition to the ones it
// requires.
type StartAttr interface {
	bareStartAttr() attribute.KeyValue
}

// Attr is an attribute a Span also accepts after it started, through
// SetAttributes.
type Attr interface {
	StartAttr
	bareAttr()
}

type bareSpanSource struct{ v heartbeatattr.SourceAttr }

func (o bareSpanSource) bareStartAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

func (bareSpanSource) bareAttr() {}

// WithSource sets `heartbeat.source` on a Span, when Start starts it or
// later through SetAttributes.
func WithSource(v heartbeatattr.SourceAttr) Attr {
	return bareSpanSource{v: v}
}

// Name is the name the `heartbeat` span is started with.
//
// `heartbeat`
//
// An empty Name, including the zero one, names the span `heartbeat`.
type Name struct{ value string }

// NewName returns name as a Name.
func NewName(name string) Name {
	return Name{value: name}
}

// Span is a started span of `heartbeat`. The zero Span records nothing.
type Span struct{ span trace.Span }

// Span returns the underlying trace.Span, or a no-op one for the zero Span.
func (s Span) Span() trace.Span {
	if s.span == nil {
		return noop.Span{}
	}
	return s.span
}

// End ends the span.
func (s Span) End(opts ...trace.SpanEndOption) {
	s.Span().End(opts...)
}

// SetAttributes sets attributes on the span after it started.
func (s Span) SetAttributes(attrs ...Attr) {
	kvs := make([]attribute.KeyValue, 0, len(attrs))
	for _, attr := range attrs {
		kvs = append(kvs, attr.bareStartAttr())
	}
	s.Span().SetAttributes(kvs...)
}

// RecordError records err as an exception event on the span.
func (s Span) RecordError(err error, opts ...trace.EventOption) {
	s.Span().RecordError(err, opts...)
}

// SetStatus sets the status of the span.
func (s Span) SetStatus(code codes.Code, description string) {
	s.Span().SetStatus(code, description)
}

// Start starts the `heartbeat` span from tracer with span kind internal.
//
// A periodic liveness signal.
func Start(ctx context.Context, tracer semconvtracer.Tracer, name Name, heartbeatSequence heartbeatattr.SequenceAttr, opts ...StartAttr) (context.Context, Span) {
	if name.value == "" {
		name = Name{value: "heartbeat"}
	}
	kvs := make([]attribute.KeyValue, 0, 1+len(opts))
	kvs = append(kvs, heartbeatSequence.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.bareStartAttr())
	}
	ctx, span := tracer.TraceTracer().Start(
		ctx,
		name.value,
		trace.WithSpanKind(trace.SpanKindInternal),
		trace.WithAttributes(kvs...),
	)
	return ctx, Span{span: span}
}
