// Code generated by weaver. DO NOT EDIT.

package authmetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"example.com/semconv/authattr"
)

// AttemptsCounter is `auth.attempts`.
//
// Number of authentication attempts.
type AttemptsCounter struct{ inst metric.Int64Counter }

// NewAttemptsCounter creates the `auth.attempts` instrument from meter.
func NewAttemptsCounter(meter metric.Meter) (AttemptsCounter, error) {
	inst, err := meter.Int64Counter(
		"auth.attempts",
		metric.WithDescription("Number of authentication attempts."),
		metric.WithUnit("{attempt}"),
	)
	if err != nil {
		return AttemptsCounter{}, fmt.Errorf("create the %s instrument: %w", "auth.attempts", err)
	}
	return AttemptsCounter{inst: inst}, nil
}

// Add records one `auth.attempts` measurement. The zero AttemptsCounter
// records nothing.
func (m AttemptsCounter) Add(ctx context.Context, incr int64, authMethod authattr.MethodAttr, authSuccess authattr.SuccessAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 2)
	kvs = append(kvs, authMethod.KeyValue())
	kvs = append(kvs, authSuccess.KeyValue())
	m.inst.Add(ctx, incr, metric.WithAttributes(kvs...))
}
