// Code generated by weaver. DO NOT EDIT.

package myappattr

import "go.opentelemetry.io/otel/attribute"

// taskIDKey is the attribute key of `myapp.task.id`.
const taskIDKey = attribute.Key("myapp.task.id")

// TaskIDAttr is a value of `myapp.task.id`.
//
// Unique identifier of the task.
type TaskIDAttr struct{ value string }

// NewTaskIDAttr returns a value of `myapp.task.id`.
func NewTaskIDAttr(value string) TaskIDAttr {
	return TaskIDAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskIDAttr) Key() attribute.Key {
	return taskIDKey
}

// KeyValue is the `myapp.task.id` attribute set to this value.
func (v TaskIDAttr) KeyValue() attribute.KeyValue {
	return taskIDKey.String(v.value)
}

// taskStateKey is the attribute key of `myapp.task.state`.
const taskStateKey = attribute.Key("myapp.task.state")

// TaskStateAttr is a value of `myapp.task.state`.
//
// Current state of the task.
type TaskStateAttr struct{ value string }

// Key is the attribute key, for filters and views that need it.
func (TaskStateAttr) Key() attribute.Key {
	return taskStateKey
}

// KeyValue is the `myapp.task.state` attribute set to this value.
func (v TaskStateAttr) KeyValue() attribute.KeyValue {
	return taskStateKey.String(v.value)
}

var (
	// TaskStateQueued is the "queued" member of `myapp.task.state`.
	//
	// The task is waiting to run.
	TaskStateQueued = TaskStateAttr{value: "queued"}

	// TaskStateDone is the "done" member of `myapp.task.state`.
	//
	// The task finished.
	TaskStateDone = TaskStateAttr{value: "done"}
)
