// Code generated by weaver. DO NOT EDIT.

// Package edgemetric is the Go form of the metrics named `edge.*`.
//
// Each metric and metric refinement is an instrument type built from a
// semconvmeter.Meter by its New constructor, and recorded through the method
// its instrument kind gives it. Counters, up-down counters, and gauges also
// have an Observable form, observed from a callback. Required attributes are
// typed parameters and the rest are trailing options. Identifiers omit the
// namespace prefix `edge.`, because the package name already carries it.
package edgemetric
