// Code generated by weaver. DO NOT EDIT.

package edgemetric

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"example.com/semconv/semconvmeter"
)

// UpstreamDurationHistogramAttr is an attribute `edge.upstream.duration`
// accepts in addition to the ones UpstreamDurationHistogram.Record requires.
type UpstreamDurationHistogramAttr interface {
	upstreamDurationHistogramAttr() attribute.KeyValue
}

type upstreamDurationHistogramServerPort struct{ v int }

func (o upstreamDurationHistogramServerPort) upstreamDurationHistogramAttr() attribute.KeyValue {
	return attribute.Int("server.port", o.v)
}

// WithUpstreamDurationHistogramServerPort attaches `server.port` to
// UpstreamDurationHistogram.
func WithUpstreamDurationHistogramServerPort(v int) UpstreamDurationHistogramAttr {
	return upstreamDurationHistogramServerPort{v: v}
}

// UpstreamDurationHistogram is `edge.upstream.duration`.
//
// Time spent waiting on an upstream server.
type UpstreamDurationHistogram struct{ inst metric.Float64Histogram }

// NewUpstreamDurationHistogram creates the `edge.upstream.duration`
// instrument from meter.
func NewUpstreamDurationHistogram(meter semconvmeter.Meter) (UpstreamDurationHistogram, error) {
	inst, err := meter.MetricMeter().Float64Histogram(
		"edge.upstream.duration",
		metric.WithDescription("Time spent waiting on an upstream server."),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10),
	)
	if err != nil {
		return UpstreamDurationHistogram{}, fmt.Errorf("create the %s instrument: %w", "edge.upstream.duration", err)
	}
	return UpstreamDurationHistogram{inst: inst}, nil
}

// Record records one `edge.upstream.duration` measurement. The zero
// UpstreamDurationHistogram records nothing.
func (m UpstreamDurationHistogram) Record(ctx context.Context, value float64, serverAddress string, opts ...UpstreamDurationHistogramAttr) {
	if m.inst == nil {
		return
	}
	kvs := make([]attribute.KeyValue, 0, 1+len(opts))
	kvs = append(kvs, attribute.String("server.address", serverAddress))
	for _, opt := range opts {
		kvs = append(kvs, opt.upstreamDurationHistogramAttr())
	}
	m.inst.Record(ctx, value, metric.WithAttributes(kvs...))
}
