// Code generated by weaver. DO NOT EDIT.

// Package edgespan is the Go form of the spans named `edge.*`.
//
// Each span and span refinement has a Start function that starts it from a
// semconvtracer.Tracer with the kind the convention gives it, and returns a
// typed span. Required attributes are typed parameters and the rest are
// trailing options. Attributes passed to Start are set as the span starts,
// so a sampler sees them, and the options a sampler does not need can also
// be set later through the span's SetAttributes. A span whose name the
// convention spells as a template of its required attributes is named from
// them; any other span takes a typed name. Identifiers omit the namespace
// prefix `edge.`, because the package name already carries it.
package edgespan
