// Code generated by weaver. DO NOT EDIT.

package edgespan

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"go.opentelemetry.io/otel/trace/noop"

	"example.com/semconv/semconvtracer"
)

// UpstreamRequestStartAttr is an attribute StartUpstreamRequest accepts in
// addition to the ones it requires.
type UpstreamRequestStartAttr interface {
	upstreamRequestStartAttr() attribute.KeyValue
}

// UpstreamRequestAttr is an attribute a UpstreamRequestSpan also accepts
// after it started, through SetAttributes.
type UpstreamRequestAttr interface {
	UpstreamRequestStartAttr
	upstreamRequestAttr()
}

type upstreamRequestSpanErrorType struct{ v string }

func (o upstreamRequestSpanErrorType) upstreamRequestStartAttr() attribute.KeyValue {
	return attribute.String("error.type", o.v)
}

// WithUpstreamRequestErrorType sets `error.type` when StartUpstreamRequest
// starts the span. Samplers read it, so it is accepted only at start.
//
// Conditionally required: If the request failed.
func WithUpstreamRequestErrorType(v string) UpstreamRequestStartAttr {
	return upstreamRequestSpanErrorType{v: v}
}

type upstreamRequestSpanHTTPRequestMethodList struct{ v []string }

func (o upstreamRequestSpanHTTPRequestMethodList) upstreamRequestStartAttr() attribute.KeyValue {
	return attribute.StringSlice("http.request.method_list", o.v)
}

func (upstreamRequestSpanHTTPRequestMethodList) upstreamRequestAttr() {}

// WithUpstreamRequestHTTPRequestMethodList sets `http.request.method_list`
// on a UpstreamRequestSpan, when StartUpstreamRequest starts it or later
// through SetAttributes.
func WithUpstreamRequestHTTPRequestMethodList(v []string) UpstreamRequestAttr {
	return upstreamRequestSpanHTTPRequestMethodList{v: v}
}

// UpstreamRequestSpan is a started span of `edge.upstream.request`. The zero
// UpstreamRequestSpan records nothing.
type UpstreamRequestSpan struct{ span trace.Span }

// Span returns the underlying trace.Span, or a no-op one for the zero
// UpstreamRequestSpan.
func (s UpstreamRequestSpan) Span() trace.Span {
	if s.span == nil {
		return noop.Span{}
	}
	return s.span
}

// End ends the span.
func (s UpstreamRequestSpan) End(opts ...trace.SpanEndOption) {
	s.Span().End(opts...)
}

// SetAttributes sets attributes on the span after it started.
func (s UpstreamRequestSpan) SetAttributes(attrs ...UpstreamRequestAttr) {
	kvs := make([]attribute.KeyValue, 0, len(attrs))
	for _, attr := range attrs {
		kvs = append(kvs, attr.upstreamRequestStartAttr())
	}
	s.Span().SetAttributes(kvs...)
}

// RecordError records err as an exception event on the span.
func (s UpstreamRequestSpan) RecordError(err error, opts ...trace.EventOption) {
	s.Span().RecordError(err, opts...)
}

// SetStatus sets the status of the span.
func (s UpstreamRequestSpan) SetStatus(code codes.Code, description string) {
	s.Span().SetStatus(code, description)
}

// StartUpstreamRequest starts the `edge.upstream.request` span from tracer
// with span kind client.
//
// A request to an upstream server.
//
// The span is named `{server.address}:{server.port}`, with each placeholder
// replaced by the value of the attribute it names.
func StartUpstreamRequest(ctx context.Context, tracer semconvtracer.Tracer, serverAddress string, serverPort int, opts ...UpstreamRequestStartAttr) (context.Context, UpstreamRequestSpan) {
	kvs := make([]attribute.KeyValue, 0, 2+len(opts))
	kvs = append(kvs, attribute.String("server.address", serverAddress))
	kvs = append(kvs, attribute.Int("server.port", serverPort))
	for _, opt := range opts {
		kvs = append(kvs, opt.upstreamRequestStartAttr())
	}
	name := attribute.String("server.address", serverAddress).Value.Emit() + ":" + attribute.Int("server.port", serverPort).Value.Emit()
	ctx, span := tracer.TraceTracer().Start(
		ctx,
		name,
		trace.WithSpanKind(trace.SpanKindClient),
		trace.WithAttributes(kvs...),
	)
	return ctx, UpstreamRequestSpan{span: span}
}
