// Code generated by weaver. DO NOT EDIT.

package workerattr

import "go.opentelemetry.io/otel/attribute"

// hostNameKey is the attribute key of `worker.host.name`.
const hostNameKey = attribute.Key("worker.host.name")

// HostNameAttr is a value of `worker.host.name`.
//
// Host name of the worker.
type HostNameAttr struct{ value string }

// NewHostNameAttr returns a value of `worker.host.name`.
func NewHostNameAttr(value string) HostNameAttr {
	return HostNameAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (HostNameAttr) Key() attribute.Key {
	return hostNameKey
}

// KeyValue is the `worker.host.name` attribute set to this value.
func (v HostNameAttr) KeyValue() attribute.KeyValue {
	return hostNameKey.String(v.value)
}

// hostPortKey is the attribute key of `worker.host.port`.
const hostPortKey = attribute.Key("worker.host.port")

// HostPortAttr is a value of `worker.host.port`.
//
// Port the worker listens on.
type HostPortAttr struct{ value int }

// NewHostPortAttr returns a value of `worker.host.port`.
func NewHostPortAttr(value int) HostPortAttr {
	return HostPortAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (HostPortAttr) Key() attribute.Key {
	return hostPortKey
}

// KeyValue is the `worker.host.port` attribute set to this value.
func (v HostPortAttr) KeyValue() attribute.KeyValue {
	return hostPortKey.Int(v.value)
}
