// Code generated by weaver. DO NOT EDIT.

// Package workerattr is the Go form of the attributes named `worker.*`.
//
// Each attribute is a value type bound to its attribute.Key, so an
// attribute.KeyValue only exists once a value has gone through the type's
// constructor. Identifiers omit the namespace prefix `worker.`, because the
// package name already carries it.
package workerattr
