// Code generated by weaver. DO NOT EDIT.

// Package semconvlogger holds the Logger that emits the registry's events,
// so every log record it emits is tied to semconv.SchemaURL.
package semconvlogger
