// Code generated by weaver. DO NOT EDIT.

package workerspan

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"go.opentelemetry.io/otel/trace/noop"

	"example.com/semconv/myappattr"
	"example.com/semconv/semconvtracer"
	"example.com/semconv/workerattr"
)

// TaskDispatchStartAttr is an attribute StartTaskDispatch accepts in
// addition to the ones it requires.
type TaskDispatchStartAttr interface {
	taskDispatchStartAttr() attribute.KeyValue
}

// TaskDispatchAttr is an attribute a TaskDispatchSpan also accepts after it
// started, through SetAttributes.
type TaskDispatchAttr interface {
	TaskDispatchStartAttr
	taskDispatchAttr()
}

type taskDispatchSpanQueueName struct{ v myappattr.QueueNameAttr }

func (o taskDispatchSpanQueueName) taskDispatchStartAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

func (taskDispatchSpanQueueName) taskDispatchAttr() {}

// WithTaskDispatchQueueName sets `myapp.queue.name` on a TaskDispatchSpan,
// when StartTaskDispatch starts it or later through SetAttributes.
//
// Recommended: When the task came from a named queue.
func WithTaskDispatchQueueName(v myappattr.QueueNameAttr) TaskDispatchAttr {
	return taskDispatchSpanQueueName{v: v}
}

type taskDispatchSpanTaskID struct{ v myappattr.TaskIDAttr }

func (o taskDispatchSpanTaskID) taskDispatchStartAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithTaskDispatchTaskID sets `myapp.task.id` when StartTaskDispatch starts
// the span. Samplers read it, so it is accepted only at start.
func WithTaskDispatchTaskID(v myappattr.TaskIDAttr) TaskDispatchStartAttr {
	return taskDispatchSpanTaskID{v: v}
}

// TaskDispatchSpan is a started span of `worker.task.dispatch`. The zero
// TaskDispatchSpan records nothing.
type TaskDispatchSpan struct{ span trace.Span }

// Span returns the underlying trace.Span, or a no-op one for the zero
// TaskDispatchSpan.
func (s TaskDispatchSpan) Span() trace.Span {
	if s.span == nil {
		return noop.Span{}
	}
	return s.span
}

// End ends the span.
func (s TaskDispatchSpan) End(opts ...trace.SpanEndOption) {
	s.Span().End(opts...)
}

// SetAttributes sets attributes on the span after it started.
func (s TaskDispatchSpan) SetAttributes(attrs ...TaskDispatchAttr) {
	kvs := make([]attribute.KeyValue, 0, len(attrs))
	for _, attr := range attrs {
		kvs = append(kvs, attr.taskDispatchStartAttr())
	}
	s.Span().SetAttributes(kvs...)
}

// RecordError records err as an exception event on the span.
func (s TaskDispatchSpan) RecordError(err error, opts ...trace.EventOption) {
	s.Span().RecordError(err, opts...)
}

// SetStatus sets the status of the span.
func (s TaskDispatchSpan) SetStatus(code codes.Code, description string) {
	s.Span().SetStatus(code, description)
}

// StartTaskDispatch starts the `worker.task.dispatch` span from tracer with
// span kind client, as a refinement of `myapp.task.dispatch`.
//
// The scheduler handing a task to a worker.
//
// Ends when the worker accepts the task.
//
// The span is named `dispatch {worker.host.name}:{worker.host.port}`, with
// each placeholder replaced by the value of the attribute it names.
func StartTaskDispatch(ctx context.Context, tracer semconvtracer.Tracer, myappTaskAttempt myappattr.TaskAttemptAttr, workerHostName workerattr.HostNameAttr, workerHostPort workerattr.HostPortAttr, opts ...TaskDispatchStartAttr) (context.Context, TaskDispatchSpan) {
	kvs := make([]attribute.KeyValue, 0, 3+len(opts))
	kvs = append(kvs, myappTaskAttempt.KeyValue())
	kvs = append(kvs, workerHostName.KeyValue())
	kvs = append(kvs, workerHostPort.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.taskDispatchStartAttr())
	}
	name := "dispatch " + workerHostName.KeyValue().Value.Emit() + ":" + workerHostPort.KeyValue().Value.Emit()
	ctx, span := tracer.TraceTracer().Start(
		ctx,
		name,
		trace.WithSpanKind(trace.SpanKindClient),
		trace.WithAttributes(kvs...),
	)
	return ctx, TaskDispatchSpan{span: span}
}
