// Generated by OpenTelemetry Weaver.
/// Synthetic bool values.
#[derive(Debug, Clone, PartialEq)]
pub struct BoolValuesAttr(Vec<bool>);

#[allow(deprecated)]
impl BoolValuesAttr {
    pub const KEY: &'static str = "myapp.bool.values";
}

#[allow(deprecated)]
impl From<Vec<bool>> for BoolValuesAttr {
    fn from(value: Vec<bool>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<BoolValuesAttr> for ::opentelemetry::KeyValue {
    fn from(value: BoolValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(BoolValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::Bool(value.0)))
    }
}
/// Synthetic double values.
#[derive(Debug, Clone, PartialEq)]
pub struct DoubleValuesAttr(Vec<f64>);

#[allow(deprecated)]
impl DoubleValuesAttr {
    pub const KEY: &'static str = "myapp.double.values";
}

#[allow(deprecated)]
impl From<Vec<f64>> for DoubleValuesAttr {
    fn from(value: Vec<f64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<DoubleValuesAttr> for ::opentelemetry::KeyValue {
    fn from(value: DoubleValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(DoubleValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::F64(value.0)))
    }
}
/// Synthetic int values.
#[derive(Debug, Clone, PartialEq)]
pub struct IntValuesAttr(Vec<i64>);

#[allow(deprecated)]
impl IntValuesAttr {
    pub const KEY: &'static str = "myapp.int.values";
}

#[allow(deprecated)]
impl From<Vec<i64>> for IntValuesAttr {
    fn from(value: Vec<i64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<IntValuesAttr> for ::opentelemetry::KeyValue {
    fn from(value: IntValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(IntValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(value.0)))
    }
}
/// Synthetic string values.
#[derive(Debug, Clone, PartialEq)]
pub struct StringValuesAttr(Vec<String>);

#[allow(deprecated)]
impl StringValuesAttr {
    pub const KEY: &'static str = "myapp.string.values";
}

#[allow(deprecated)]
impl From<Vec<String>> for StringValuesAttr {
    fn from(value: Vec<String>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<StringValuesAttr> for ::opentelemetry::KeyValue {
    fn from(value: StringValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(StringValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::String(value.0.into_iter().map(Into::into).collect())))
    }
}
/// Number of the attempt, starting at 1.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskAttemptAttr(i64);

#[allow(deprecated)]
impl TaskAttemptAttr {
    pub const KEY: &'static str = "myapp.task.attempt";
}

#[allow(deprecated)]
impl From<i64> for TaskAttemptAttr {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskAttemptAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskAttemptAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskAttemptAttr::KEY, value.0)
    }
}
/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskStateAttr {
    /// The task finished.
    Done,
    /// The task gave up.
    Failed,
}

#[allow(deprecated)]
impl TaskStateAttr {
    pub const KEY: &'static str = "myapp.task.state";
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskStateAttr) -> Self {
        let value: String = match value {
            TaskStateAttr::Done => "done".into(),
            TaskStateAttr::Failed => "failed".into(),
        };
        ::opentelemetry::KeyValue::new(TaskStateAttr::KEY, value)
    }
}
