// Generated by OpenTelemetry Weaver.

/// Synthetic bool values.
#[derive(Debug, Clone, PartialEq)]

pub struct BoolValuesAttr(Vec<bool>);


#[allow(deprecated)]
impl BoolValuesAttr {
    pub const KEY: &'static str = "myapp.bool.values";

    pub fn new(value: Vec<bool>) -> Self {
        Self(value)
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::Bool(self.0)))

    }
}

#[allow(deprecated)]
impl From<BoolValuesAttr> for ::opentelemetry::KeyValue {
    fn from(value: BoolValuesAttr) -> Self {
        value.key_value()
    }
}

/// Synthetic double values.
#[derive(Debug, Clone, PartialEq)]

pub struct DoubleValuesAttr(Vec<f64>);


#[allow(deprecated)]
impl DoubleValuesAttr {
    pub const KEY: &'static str = "myapp.double.values";

    pub fn new(value: Vec<f64>) -> Self {
        Self(value)
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::F64(self.0)))

    }
}

#[allow(deprecated)]
impl From<DoubleValuesAttr> for ::opentelemetry::KeyValue {
    fn from(value: DoubleValuesAttr) -> Self {
        value.key_value()
    }
}

/// Synthetic int values.
#[derive(Debug, Clone, PartialEq)]

pub struct IntValuesAttr(Vec<i64>);


#[allow(deprecated)]
impl IntValuesAttr {
    pub const KEY: &'static str = "myapp.int.values";

    pub fn new(value: Vec<i64>) -> Self {
        Self(value)
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(self.0)))

    }
}

#[allow(deprecated)]
impl From<IntValuesAttr> for ::opentelemetry::KeyValue {
    fn from(value: IntValuesAttr) -> Self {
        value.key_value()
    }
}

/// Synthetic string values.
#[derive(Debug, Clone, PartialEq)]

pub struct StringValuesAttr(Vec<String>);


#[allow(deprecated)]
impl StringValuesAttr {
    pub const KEY: &'static str = "myapp.string.values";

    pub fn new(value: Vec<String>) -> Self {
        Self(value)
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::String(self.0.into_iter().map(Into::into).collect())))

    }
}

#[allow(deprecated)]
impl From<StringValuesAttr> for ::opentelemetry::KeyValue {
    fn from(value: StringValuesAttr) -> Self {
        value.key_value()
    }
}

/// Number of the attempt, starting at 1.
#[derive(Debug, Clone, PartialEq)]

pub struct TaskAttemptAttr(i64);


#[allow(deprecated)]
impl TaskAttemptAttr {
    pub const KEY: &'static str = "myapp.task.attempt";

    pub fn new(value: i64) -> Self {
        Self(value)
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<TaskAttemptAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskAttemptAttr) -> Self {
        value.key_value()
    }
}

/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]

pub enum TaskStateAttr {

    /// The task finished.
    Done,

    /// The task gave up.
    Failed,

}


#[allow(deprecated)]
impl TaskStateAttr {
    pub const KEY: &'static str = "myapp.task.state";


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        let value: String = match self {

            Self::Done => "done".into(),

            Self::Failed => "failed".into(),

        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)

    }
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskStateAttr) -> Self {
        value.key_value()
    }
}
