// Generated by OpenTelemetry Weaver.
/// Synthetic bool values.
#[derive(Debug, Clone, PartialEq)]
pub struct BoolValuesAttr(Vec<bool>);

#[allow(deprecated)]
impl BoolValuesAttr {
    pub const KEY: &'static str = "myapp.bool.values";
}

#[allow(deprecated)]
impl From<Vec<bool>> for BoolValuesAttr {
    #[inline]
    fn from(value: Vec<bool>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[bool]> for BoolValuesAttr {
    #[inline]
    fn as_ref(&self) -> &[bool] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for BoolValuesAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<BoolValuesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: BoolValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(BoolValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::Bool(value.0)))
    }
}

#[allow(deprecated)]
impl From<BoolValuesAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: BoolValuesAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}

/// Synthetic double values.
#[derive(Debug, Clone, PartialEq)]
pub struct DoubleValuesAttr(Vec<f64>);

#[allow(deprecated)]
impl DoubleValuesAttr {
    pub const KEY: &'static str = "myapp.double.values";
}

#[allow(deprecated)]
impl From<Vec<f64>> for DoubleValuesAttr {
    #[inline]
    fn from(value: Vec<f64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[f64]> for DoubleValuesAttr {
    #[inline]
    fn as_ref(&self) -> &[f64] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for DoubleValuesAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<DoubleValuesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: DoubleValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(DoubleValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::F64(value.0)))
    }
}

#[allow(deprecated)]
impl From<DoubleValuesAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: DoubleValuesAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}

/// Synthetic int values.
#[derive(Debug, Clone, PartialEq)]
pub struct IntValuesAttr(Vec<i64>);

#[allow(deprecated)]
impl IntValuesAttr {
    pub const KEY: &'static str = "myapp.int.values";
}

#[allow(deprecated)]
impl From<Vec<i64>> for IntValuesAttr {
    #[inline]
    fn from(value: Vec<i64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl AsRef<[i64]> for IntValuesAttr {
    #[inline]
    fn as_ref(&self) -> &[i64] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for IntValuesAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            ::std::fmt::Display::fmt(value, formatter)?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<IntValuesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: IntValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(IntValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(value.0)))
    }
}

#[allow(deprecated)]
impl From<IntValuesAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: IntValuesAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}

/// Synthetic string values.
#[derive(Debug, Clone, PartialEq)]
pub struct StringValuesAttr(Vec<::opentelemetry::StringValue>);

#[allow(deprecated)]
impl StringValuesAttr {
    pub const KEY: &'static str = "myapp.string.values";
}

#[allow(deprecated)]
impl From<Vec<::opentelemetry::StringValue>> for StringValuesAttr {
    #[inline]
    fn from(value: Vec<::opentelemetry::StringValue>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<Vec<String>> for StringValuesAttr {
    fn from(value: Vec<String>) -> Self {
        Self(value.into_iter().map(Into::into).collect())
    }
}

#[allow(deprecated)]
impl AsRef<[::opentelemetry::StringValue]> for StringValuesAttr {
    #[inline]
    fn as_ref(&self) -> &[::opentelemetry::StringValue] {
        &self.0
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for StringValuesAttr {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str("[")?;
        for (index, value) in self.0.iter().enumerate() {
            if index != 0 {
                formatter.write_str(",")?;
            }
            write!(formatter, "\"{value}\"")?;
        }
        formatter.write_str("]")
    }
}

#[allow(deprecated)]
impl From<StringValuesAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: StringValuesAttr) -> Self {
        ::opentelemetry::KeyValue::new(StringValuesAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::String(value.0)))
    }
}

#[allow(deprecated)]
impl From<StringValuesAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: StringValuesAttr) -> Self {
        value.0.into_iter().collect::<::opentelemetry::logs::AnyValue>()
    }
}

/// Number of the attempt, starting at 1.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct TaskAttemptAttr(i64);

#[allow(deprecated)]
impl TaskAttemptAttr {
    pub const KEY: &'static str = "myapp.task.attempt";
}

#[allow(deprecated)]
impl From<i64> for TaskAttemptAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for TaskAttemptAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<TaskAttemptAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: TaskAttemptAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskAttemptAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<TaskAttemptAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: TaskAttemptAttr) -> Self {
        value.0.into()
    }
}

/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskStateAttr {
    /// The task finished.
    Done,
    /// The task gave up.
    Failed,
}

#[allow(deprecated)]
impl TaskStateAttr {
    pub const KEY: &'static str = "myapp.task.state";
}

#[allow(deprecated)]
impl AsRef<str> for TaskStateAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            TaskStateAttr::Done => "done",
            TaskStateAttr::Failed => "failed",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for TaskStateAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: TaskStateAttr) -> Self {
        let value: &'static str = match value {
            TaskStateAttr::Done => "done",
            TaskStateAttr::Failed => "failed",
        };
        ::opentelemetry::KeyValue::new(TaskStateAttr::KEY, value)
    }
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: TaskStateAttr) -> Self {
        let value: &'static str = match value {
            TaskStateAttr::Done => "done",
            TaskStateAttr::Failed => "failed",
        };
        value.into()
    }
}
