// Generated by OpenTelemetry Weaver.
/// Name of the worker host.
#[derive(Debug, Clone, PartialEq)]
pub struct HostNameAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl HostNameAttr {
    pub const KEY: &'static str = "worker.host.name";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for HostNameAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for HostNameAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for HostNameAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for HostNameAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for HostNameAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<HostNameAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: HostNameAttr) -> Self {
        ::opentelemetry::KeyValue::new(HostNameAttr::KEY, value.0)
    }
}
