// Generated by OpenTelemetry Weaver.
/// Name of the worker host.
#[derive(Debug, Clone, PartialEq)]
pub struct HostNameAttr(String);

#[allow(deprecated)]
impl HostNameAttr {
    pub const KEY: &'static str = "worker.host.name";
}

#[allow(deprecated)]
impl From<String> for HostNameAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for HostNameAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<HostNameAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostNameAttr) -> Self {
        ::opentelemetry::KeyValue::new(HostNameAttr::KEY, value.0)
    }
}
