// Generated by OpenTelemetry Weaver.
/// Name of the worker host.
#[derive(Debug, Clone, PartialEq)]
pub struct HostNameAttr(String);

#[allow(deprecated)]
impl HostNameAttr {
    pub const KEY: &'static str = "worker.host.name";
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<HostNameAttr> for ::opentelemetry::KeyValue {
    fn from(value: HostNameAttr) -> Self {
        value.key_value()
    }
}
