// Generated by OpenTelemetry Weaver.
/// Unique identifier of the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskIdAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl TaskIdAttr {
    pub const KEY: &'static str = "myapp.task.id";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for TaskIdAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for TaskIdAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for TaskIdAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for TaskIdAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for TaskIdAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<TaskIdAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: TaskIdAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskIdAttr::KEY, value.0)
    }
}
