// Code generated by weaver. DO NOT EDIT.

package exceptionevent

import (
	"context"
	"time"

	"go.opentelemetry.io/otel/log"

	"example.com/semconv/exceptionattr"
	"example.com/semconv/semconvlogger"
)

// Option sets an attribute, the severity, or the timestamp of an event Emit
// emits.
type Option interface {
	bareOption(record *log.Record)
}

type bareEventSeverity struct{ v log.Severity }

func (o bareEventSeverity) bareOption(record *log.Record) {
	record.SetSeverity(o.v)
}

// WithSeverity sets the severity of the event, in place of log.SeverityInfo.
func WithSeverity(severity log.Severity) Option {
	return bareEventSeverity{v: severity}
}

type bareEventTimestamp struct{ v time.Time }

func (o bareEventTimestamp) bareOption(record *log.Record) {
	record.SetTimestamp(o.v)
}

// WithTimestamp sets the time the event occurred. Without it the event
// carries only the time it was observed.
func WithTimestamp(timestamp time.Time) Option {
	return bareEventTimestamp{v: timestamp}
}

type bareEventMessage struct{ v exceptionattr.MessageAttr }

func (o bareEventMessage) bareOption(record *log.Record) {
	record.AddAttributes(o.v.KeyValue())
}

// WithMessage sets `exception.message` on the event.
func WithMessage(v exceptionattr.MessageAttr) Option {
	return bareEventMessage{v: v}
}

// Emit emits the `exception` event through logger. It is skipped when logger
// is not enabled for it, and the zero logger emits nothing.
//
// A noteworthy exception occurred.
func Emit(ctx context.Context, logger semconvlogger.Logger, exceptionType exceptionattr.TypeAttr, opts ...Option) {
	var record log.Record
	record.SetEventName("exception")
	record.SetSeverity(log.SeverityInfo)
	record.AddAttributes(
		exceptionType.KeyValue(),
	)
	for _, opt := range opts {
		opt.bareOption(&record)
	}
	if !logger.LogLogger().Enabled(ctx, log.EnabledParameters{Severity: record.Severity(), EventName: record.EventName()}) {
		return
	}
	logger.LogLogger().Emit(ctx, record)
}
