// Code generated by weaver. DO NOT EDIT.

package myappspan

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"go.opentelemetry.io/otel/trace/noop"

	"example.com/semconv/myappattr"
	"example.com/semconv/semconvtracer"
	"example.com/semconv/workerattr"
)

// QueueDrainName is the name the `myapp.queue.drain` span is started with.
//
// `drain` followed by the queue's name, such as `drain reports`.
//
// An empty QueueDrainName, including the zero one, names the span
// `myapp.queue.drain`.
type QueueDrainName struct{ value string }

// NewQueueDrainName returns name as a QueueDrainName.
func NewQueueDrainName(name string) QueueDrainName {
	return QueueDrainName{value: name}
}

// QueueDrainSpan is a started span of `myapp.queue.drain`. The zero
// QueueDrainSpan records nothing.
//
// Deprecated: Drain queues by dispatching their tasks instead.
type QueueDrainSpan struct{ span trace.Span }

// Span returns the underlying trace.Span, or a no-op one for the zero
// QueueDrainSpan.
func (s QueueDrainSpan) Span() trace.Span {
	if s.span == nil {
		return noop.Span{}
	}
	return s.span
}

// End ends the span.
func (s QueueDrainSpan) End(opts ...trace.SpanEndOption) {
	s.Span().End(opts...)
}

// RecordError records err as an exception event on the span.
func (s QueueDrainSpan) RecordError(err error, opts ...trace.EventOption) {
	s.Span().RecordError(err, opts...)
}

// SetStatus sets the status of the span.
func (s QueueDrainSpan) SetStatus(code codes.Code, description string) {
	s.Span().SetStatus(code, description)
}

// StartQueueDrain starts the `myapp.queue.drain` span from tracer with span
// kind consumer.
//
// Removing every task from a queue.
//
// Opt-in: the convention records `myapp.queue.drain` only when a user asks
// for it.
//
// Deprecated: Drain queues by dispatching their tasks instead.
func StartQueueDrain(ctx context.Context, tracer semconvtracer.Tracer, name QueueDrainName) (context.Context, QueueDrainSpan) {
	if name.value == "" {
		name = QueueDrainName{value: "myapp.queue.drain"}
	}
	ctx, span := tracer.TraceTracer().Start(
		ctx,
		name.value,
		trace.WithSpanKind(trace.SpanKindConsumer),
	)
	return ctx, QueueDrainSpan{span: span}
}

// TaskDispatchStartAttr is an attribute StartTaskDispatch accepts in
// addition to the ones it requires.
type TaskDispatchStartAttr interface {
	taskDispatchStartAttr() attribute.KeyValue
}

// TaskDispatchAttr is an attribute a TaskDispatchSpan also accepts after it
// started, through SetAttributes.
type TaskDispatchAttr interface {
	TaskDispatchStartAttr
	taskDispatchAttr()
}

type taskDispatchSpanQueueName struct{ v myappattr.QueueNameAttr }

func (o taskDispatchSpanQueueName) taskDispatchStartAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

func (taskDispatchSpanQueueName) taskDispatchAttr() {}

// WithTaskDispatchQueueName sets `myapp.queue.name` on a TaskDispatchSpan,
// when StartTaskDispatch starts it or later through SetAttributes.
//
// Recommended: When the task came from a named queue.
func WithTaskDispatchQueueName(v myappattr.QueueNameAttr) TaskDispatchAttr {
	return taskDispatchSpanQueueName{v: v}
}

type taskDispatchSpanTaskAttempt struct{ v myappattr.TaskAttemptAttr }

func (o taskDispatchSpanTaskAttempt) taskDispatchStartAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

func (taskDispatchSpanTaskAttempt) taskDispatchAttr() {}

// WithTaskDispatchTaskAttempt sets `myapp.task.attempt` on a
// TaskDispatchSpan, when StartTaskDispatch starts it or later through
// SetAttributes.
//
// Opt-in: the convention records it only when a user asks for it.
func WithTaskDispatchTaskAttempt(v myappattr.TaskAttemptAttr) TaskDispatchAttr {
	return taskDispatchSpanTaskAttempt{v: v}
}

type taskDispatchSpanTaskID struct{ v myappattr.TaskIDAttr }

func (o taskDispatchSpanTaskID) taskDispatchStartAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithTaskDispatchTaskID sets `myapp.task.id` when StartTaskDispatch starts
// the span. Samplers read it, so it is accepted only at start.
func WithTaskDispatchTaskID(v myappattr.TaskIDAttr) TaskDispatchStartAttr {
	return taskDispatchSpanTaskID{v: v}
}

// TaskDispatchSpan is a started span of `myapp.task.dispatch`. The zero
// TaskDispatchSpan records nothing.
type TaskDispatchSpan struct{ span trace.Span }

// Span returns the underlying trace.Span, or a no-op one for the zero
// TaskDispatchSpan.
func (s TaskDispatchSpan) Span() trace.Span {
	if s.span == nil {
		return noop.Span{}
	}
	return s.span
}

// End ends the span.
func (s TaskDispatchSpan) End(opts ...trace.SpanEndOption) {
	s.Span().End(opts...)
}

// SetAttributes sets attributes on the span after it started.
func (s TaskDispatchSpan) SetAttributes(attrs ...TaskDispatchAttr) {
	kvs := make([]attribute.KeyValue, 0, len(attrs))
	for _, attr := range attrs {
		kvs = append(kvs, attr.taskDispatchStartAttr())
	}
	s.Span().SetAttributes(kvs...)
}

// RecordError records err as an exception event on the span.
func (s TaskDispatchSpan) RecordError(err error, opts ...trace.EventOption) {
	s.Span().RecordError(err, opts...)
}

// SetStatus sets the status of the span.
func (s TaskDispatchSpan) SetStatus(code codes.Code, description string) {
	s.Span().SetStatus(code, description)
}

// StartTaskDispatch starts the `myapp.task.dispatch` span from tracer with
// span kind client.
//
// The scheduler handing a task to a worker.
//
// Ends when the worker accepts the task.
//
// The span is named `dispatch {worker.host.name}:{worker.host.port}`, with
// each placeholder replaced by the value of the attribute it names.
func StartTaskDispatch(ctx context.Context, tracer semconvtracer.Tracer, workerHostName workerattr.HostNameAttr, workerHostPort workerattr.HostPortAttr, opts ...TaskDispatchStartAttr) (context.Context, TaskDispatchSpan) {
	kvs := make([]attribute.KeyValue, 0, 2+len(opts))
	kvs = append(kvs, workerHostName.KeyValue())
	kvs = append(kvs, workerHostPort.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.taskDispatchStartAttr())
	}
	name := "dispatch " + workerHostName.KeyValue().Value.Emit() + ":" + workerHostPort.KeyValue().Value.Emit()
	ctx, span := tracer.TraceTracer().Start(
		ctx,
		name,
		trace.WithSpanKind(trace.SpanKindClient),
		trace.WithAttributes(kvs...),
	)
	return ctx, TaskDispatchSpan{span: span}
}

// TaskRunStartAttr is an attribute StartTaskRun accepts in addition to the
// ones it requires.
type TaskRunStartAttr interface {
	taskRunStartAttr() attribute.KeyValue
}

// TaskRunAttr is an attribute a TaskRunSpan also accepts after it started,
// through SetAttributes.
type TaskRunAttr interface {
	TaskRunStartAttr
	taskRunAttr()
}

type taskRunSpanTaskID struct{ v myappattr.TaskIDAttr }

func (o taskRunSpanTaskID) taskRunStartAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

func (taskRunSpanTaskID) taskRunAttr() {}

// WithTaskRunTaskID sets `myapp.task.id` on a TaskRunSpan, when StartTaskRun
// starts it or later through SetAttributes.
func WithTaskRunTaskID(v myappattr.TaskIDAttr) TaskRunAttr {
	return taskRunSpanTaskID{v: v}
}

// TaskRunName is the name the `myapp.task.run` span is started with.
//
// `run {myapp.task.id}`
//
// An empty TaskRunName, including the zero one, names the span
// `myapp.task.run`.
type TaskRunName struct{ value string }

// NewTaskRunName returns name as a TaskRunName.
func NewTaskRunName(name string) TaskRunName {
	return TaskRunName{value: name}
}

// TaskRunSpan is a started span of `myapp.task.run`. The zero TaskRunSpan
// records nothing.
type TaskRunSpan struct{ span trace.Span }

// Span returns the underlying trace.Span, or a no-op one for the zero
// TaskRunSpan.
func (s TaskRunSpan) Span() trace.Span {
	if s.span == nil {
		return noop.Span{}
	}
	return s.span
}

// End ends the span.
func (s TaskRunSpan) End(opts ...trace.SpanEndOption) {
	s.Span().End(opts...)
}

// SetAttributes sets attributes on the span after it started.
func (s TaskRunSpan) SetAttributes(attrs ...TaskRunAttr) {
	kvs := make([]attribute.KeyValue, 0, len(attrs))
	for _, attr := range attrs {
		kvs = append(kvs, attr.taskRunStartAttr())
	}
	s.Span().SetAttributes(kvs...)
}

// RecordError records err as an exception event on the span.
func (s TaskRunSpan) RecordError(err error, opts ...trace.EventOption) {
	s.Span().RecordError(err, opts...)
}

// SetStatus sets the status of the span.
func (s TaskRunSpan) SetStatus(code codes.Code, description string) {
	s.Span().SetStatus(code, description)
}

// StartTaskRun starts the `myapp.task.run` span from tracer with span kind
// internal.
//
// One run of a task.
func StartTaskRun(ctx context.Context, tracer semconvtracer.Tracer, name TaskRunName, myappTaskState myappattr.TaskStateAttr, opts ...TaskRunStartAttr) (context.Context, TaskRunSpan) {
	if name.value == "" {
		name = TaskRunName{value: "myapp.task.run"}
	}
	kvs := make([]attribute.KeyValue, 0, 1+len(opts))
	kvs = append(kvs, myappTaskState.KeyValue())
	for _, opt := range opts {
		kvs = append(kvs, opt.taskRunStartAttr())
	}
	ctx, span := tracer.TraceTracer().Start(
		ctx,
		name.value,
		trace.WithSpanKind(trace.SpanKindInternal),
		trace.WithAttributes(kvs...),
	)
	return ctx, TaskRunSpan{span: span}
}
