// Generated by OpenTelemetry Weaver.
pub const SCHEMA_URL: &str = "https://example.com/schemas/myapp/1.0.0";
pub mod myappattr;

pub mod meter;
pub mod tracer;
pub mod logger;
pub mod myappevent;
pub mod myappmetric;
pub mod myappspan;
