// Generated by OpenTelemetry Weaver.
/// Identifier of the invoice.
#[derive(Debug, Clone, PartialEq)]
pub struct InvoiceIdAttr(String);

#[allow(deprecated)]
impl InvoiceIdAttr {
    pub const KEY: &'static str = "acme.billing.invoice.id";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for InvoiceIdAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for InvoiceIdAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<InvoiceIdAttr> for ::opentelemetry::KeyValue {
    fn from(value: InvoiceIdAttr) -> Self {
        value.key_value()
    }
}
/// ISO 4217 currency code of the amount.
#[derive(Debug, Clone, PartialEq)]
pub struct CurrencyAttr(String);

#[allow(deprecated)]
impl CurrencyAttr {
    pub const KEY: &'static str = "billing.currency";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for CurrencyAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for CurrencyAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<CurrencyAttr> for ::opentelemetry::KeyValue {
    fn from(value: CurrencyAttr) -> Self {
        value.key_value()
    }
}
