// Generated by OpenTelemetry Weaver.
/// Identifier of the invoice.
#[derive(Debug, Clone, PartialEq)]
pub struct InvoiceIdAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl InvoiceIdAttr {
    pub const KEY: &'static str = "acme.billing.invoice.id";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for InvoiceIdAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for InvoiceIdAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for InvoiceIdAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for InvoiceIdAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for InvoiceIdAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<InvoiceIdAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: InvoiceIdAttr) -> Self {
        ::opentelemetry::KeyValue::new(InvoiceIdAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<InvoiceIdAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: InvoiceIdAttr) -> Self {
        value.0.into()
    }
}
/// ISO 4217 currency code of the amount.
#[derive(Debug, Clone, PartialEq)]
pub struct CurrencyAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl CurrencyAttr {
    pub const KEY: &'static str = "billing.currency";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for CurrencyAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for CurrencyAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for CurrencyAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for CurrencyAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for CurrencyAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<CurrencyAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: CurrencyAttr) -> Self {
        ::opentelemetry::KeyValue::new(CurrencyAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<CurrencyAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: CurrencyAttr) -> Self {
        value.0.into()
    }
}
