//! Typed telemetry for a synthetic registry.
// Generated by OpenTelemetry Weaver.
// Source: model/

// Regenerate: mise run generate

pub const SCHEMA_URL: &str = "https://example.com/schemas/params/1.0.0";

pub mod billingattr;

pub mod myappattr;


pub mod meter;



pub mod billingmetric;
