//! Typed telemetry for a synthetic registry.
// Generated by OpenTelemetry Weaver.
// Source: model/

// Regenerate: mise run generate

pub const SCHEMA_URL: &str = "https://example.com/schemas/params/1.0.0";

pub mod billingattr {

    /// Identifier of the invoice.
    #[derive(Debug, Clone, PartialEq)]

    pub struct InvoiceIdAttr(String);


    #[allow(deprecated)]
    impl InvoiceIdAttr {
        pub const KEY: &'static str = "acme.billing.invoice.id";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<InvoiceIdAttr> for ::opentelemetry::KeyValue {
        fn from(value: InvoiceIdAttr) -> Self {
            value.key_value()
        }
    }

    /// ISO 4217 currency code of the amount.
    #[derive(Debug, Clone, PartialEq)]

    pub struct CurrencyAttr(String);


    #[allow(deprecated)]
    impl CurrencyAttr {
        pub const KEY: &'static str = "billing.currency";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<CurrencyAttr> for ::opentelemetry::KeyValue {
        fn from(value: CurrencyAttr) -> Self {
            value.key_value()
        }
    }

}

pub mod myappattr {

    /// URL the request was sent to.
    #[derive(Debug, Clone, PartialEq)]

    pub struct RequestUrlAttr(String);


    #[allow(deprecated)]
    impl RequestUrlAttr {
        pub const KEY: &'static str = "myapp.request.url";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<RequestUrlAttr> for ::opentelemetry::KeyValue {
        fn from(value: RequestUrlAttr) -> Self {
            value.key_value()
        }
    }

}


pub mod meter;



pub mod billingmetric;
