// Generated by OpenTelemetry Weaver.

/// URL the request was sent to.
#[derive(Debug, Clone, PartialEq)]

pub struct RequestUrlAttr(String);


#[allow(deprecated)]
impl RequestUrlAttr {
    pub const KEY: &'static str = "myapp.request.url";

    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<RequestUrlAttr> for ::opentelemetry::KeyValue {
    fn from(value: RequestUrlAttr) -> Self {
        value.key_value()
    }
}
