// Generated by OpenTelemetry Weaver.
/// URL the request was sent to.
#[derive(Debug, Clone, PartialEq)]
pub struct RequestUrlAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl RequestUrlAttr {
    pub const KEY: &'static str = "myapp.request.url";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for RequestUrlAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for RequestUrlAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for RequestUrlAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for RequestUrlAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for RequestUrlAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<RequestUrlAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: RequestUrlAttr) -> Self {
        ::opentelemetry::KeyValue::new(RequestUrlAttr::KEY, value.0)
    }
}
