// Generated by OpenTelemetry Weaver.
/// URL the request was sent to.
#[derive(Debug, Clone, PartialEq)]
pub struct RequestUrlAttr(String);

#[allow(deprecated)]
impl RequestUrlAttr {
    pub const KEY: &'static str = "myapp.request.url";
}

#[allow(deprecated)]
impl From<String> for RequestUrlAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for RequestUrlAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<RequestUrlAttr> for ::opentelemetry::KeyValue {
    fn from(value: RequestUrlAttr) -> Self {
        ::opentelemetry::KeyValue::new(RequestUrlAttr::KEY, value.0)
    }
}
