// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

// Package billingattr is the Go form of the attributes named
// `acme.billing.*` and `billing.*`.
//
// Each attribute is a value type bound to its attribute.Key, so an
// attribute.KeyValue only exists once a value has gone through the type's
// constructor. Identifiers omit the namespace prefix `acme.billing.` or
// `billing.`, because the package name already carries it.
package billingattr
