// Code generated by weaver. DO NOT EDIT.

package hostentity

import (
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/sdk/resource"

	"example.com/semconv/hostattr"

	"example.com/semconv"
)

// EntityAttr is an attribute NewEntity accepts in addition to the ones it
// requires.
type EntityAttr interface {
	bareEntityAttr() attribute.KeyValue
}

type bareEntityName struct{ v hostattr.NameAttr }

func (o bareEntityName) bareEntityAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithEntityName sets `host.name` on the entity.
func WithEntityName(v hostattr.NameAttr) EntityAttr {
	return bareEntityName{v: v}
}

// Entity is the `host` entity. The zero Entity has no attributes.
//
// A physical or virtual machine.
//
// Identifies the entity: `host.id`.
//
// Describes the entity: `host.name`.
type Entity struct{ attrs []attribute.KeyValue }

// NewEntity builds a Entity from its required attributes and any given
// options.
func NewEntity(hostID hostattr.IDAttr, opts ...EntityAttr) Entity {
	attrs := make([]attribute.KeyValue, 0, 1+len(opts))
	attrs = append(attrs, hostID.KeyValue())
	for _, opt := range opts {
		attrs = append(attrs, opt.bareEntityAttr())
	}
	return Entity{attrs: attrs}
}

// Attributes returns a copy of the entity's attributes. The zero Entity
// returns none.
func (e Entity) Attributes() []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(e.attrs))
	copy(out, e.attrs)
	return out
}

// Resource returns a *resource.Resource built from the entity's attributes,
// tied to semconv.SchemaURL.
func (e Entity) Resource() *resource.Resource {
	return resource.NewWithAttributes(semconv.SchemaURL, e.attrs...)
}
