// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

// Package acmesemconvmeter holds the Meter every metric instrument of the
// registry is created from, so everything the instruments record is tied to
// acmesemconv.SchemaURL.
package acmesemconvmeter
