// Generated by OpenTelemetry Weaver.

/// The exception message.
#[derive(Debug, Clone, PartialEq)]

pub struct MessageAttr(String);


#[allow(deprecated)]
impl MessageAttr {
    pub const KEY: &'static str = "exception.message";

    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<MessageAttr> for ::opentelemetry::KeyValue {
    fn from(value: MessageAttr) -> Self {
        value.key_value()
    }
}

/// The type of the exception.
#[derive(Debug, Clone, PartialEq)]

pub struct TypeAttr(String);


#[allow(deprecated)]
impl TypeAttr {
    pub const KEY: &'static str = "exception.type";

    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<TypeAttr> for ::opentelemetry::KeyValue {
    fn from(value: TypeAttr) -> Self {
        value.key_value()
    }
}
