// Generated by OpenTelemetry Weaver.
/// The exception message.
#[derive(Debug, Clone, PartialEq)]
pub struct MessageAttr(String);

#[allow(deprecated)]
impl MessageAttr {
    pub const KEY: &'static str = "exception.message";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for MessageAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for MessageAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<MessageAttr> for ::opentelemetry::KeyValue {
    fn from(value: MessageAttr) -> Self {
        value.key_value()
    }
}
/// The type of the exception.
#[derive(Debug, Clone, PartialEq)]
pub struct TypeAttr(String);

#[allow(deprecated)]
impl TypeAttr {
    pub const KEY: &'static str = "exception.type";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for TypeAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for TypeAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<TypeAttr> for ::opentelemetry::KeyValue {
    fn from(value: TypeAttr) -> Self {
        value.key_value()
    }
}
