// Generated by OpenTelemetry Weaver.

/// Sequence number of the heartbeat.
#[derive(Debug, Clone, PartialEq)]

pub struct SequenceAttr(i64);


#[allow(deprecated)]
impl SequenceAttr {
    pub const KEY: &'static str = "heartbeat.sequence";

    pub fn new(value: i64) -> Self {
        Self(value)
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<SequenceAttr> for ::opentelemetry::KeyValue {
    fn from(value: SequenceAttr) -> Self {
        value.key_value()
    }
}

/// Name of the component that sent the heartbeat.
#[derive(Debug, Clone, PartialEq)]

pub struct SourceAttr(String);


#[allow(deprecated)]
impl SourceAttr {
    pub const KEY: &'static str = "heartbeat.source";

    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<SourceAttr> for ::opentelemetry::KeyValue {
    fn from(value: SourceAttr) -> Self {
        value.key_value()
    }
}
