// Generated by OpenTelemetry Weaver.
/// Sequence number of the heartbeat.
#[derive(Debug, Clone, PartialEq, Copy)]
pub struct SequenceAttr(i64);

#[allow(deprecated)]
impl SequenceAttr {
    pub const KEY: &'static str = "heartbeat.sequence";
}

#[allow(deprecated)]
impl From<i64> for SequenceAttr {
    #[inline]
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for SequenceAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(&self.0, formatter)
    }
}

#[allow(deprecated)]
impl From<SequenceAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: SequenceAttr) -> Self {
        ::opentelemetry::KeyValue::new(SequenceAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<SequenceAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: SequenceAttr) -> Self {
        value.0.into()
    }
}
/// Name of the component that sent the heartbeat.
#[derive(Debug, Clone, PartialEq)]
pub struct SourceAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl SourceAttr {
    pub const KEY: &'static str = "heartbeat.source";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for SourceAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for SourceAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for SourceAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for SourceAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for SourceAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<SourceAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: SourceAttr) -> Self {
        ::opentelemetry::KeyValue::new(SourceAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<SourceAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: SourceAttr) -> Self {
        value.0.into()
    }
}
