// Generated by OpenTelemetry Weaver.
/// Unique identifier of the host.
#[derive(Debug, Clone, PartialEq)]
pub struct IdAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl IdAttr {
    pub const KEY: &'static str = "host.id";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for IdAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for IdAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for IdAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for IdAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for IdAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<IdAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: IdAttr) -> Self {
        ::opentelemetry::KeyValue::new(IdAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<IdAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: IdAttr) -> Self {
        value.0.into()
    }
}
/// Name of the host.
#[derive(Debug, Clone, PartialEq)]
pub struct NameAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl NameAttr {
    pub const KEY: &'static str = "host.name";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for NameAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for NameAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for NameAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for NameAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for NameAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<NameAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: NameAttr) -> Self {
        ::opentelemetry::KeyValue::new(NameAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<NameAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: NameAttr) -> Self {
        value.0.into()
    }
}
