// Code generated by weaver. DO NOT EDIT.
#![allow(deprecated)]
#[derive(Clone, Debug)]
pub enum EntityAttr {
    Name(super::hostattr::NameAttr),
}

impl From<EntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: EntityAttr) -> Self {
        match value {
            EntityAttr::Name(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// A physical or virtual machine.
/// Identifies the entity: `host.id`.
/// Describes the entity: `host.name`.
#[derive(Clone, Debug, Default)]
pub struct Entity {
    attributes: Vec<::opentelemetry::KeyValue>,
}

impl Entity {
    pub fn new(r#host_id: super::hostattr::IdAttr, options: impl IntoIterator<Item = EntityAttr>) -> Self {
        let mut attributes = vec![
            ::opentelemetry::KeyValue::from(r#host_id),
        ];
        attributes.extend(options.into_iter().map(::opentelemetry::KeyValue::from));
        Self { attributes }
    }

    pub fn attributes(&self) -> Vec<::opentelemetry::KeyValue> {
        self.attributes.clone()
    }

    pub fn resource(&self) -> ::opentelemetry_sdk::Resource {
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(self.attributes(), super::SCHEMA_URL)
            .build()
    }
}
