// Generated by OpenTelemetry Weaver.

/// Unique identifier of the host.
#[derive(Debug, Clone, PartialEq)]

pub struct IdAttr(String);


#[allow(deprecated)]
impl IdAttr {
    pub const KEY: &'static str = "host.id";

    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<IdAttr> for ::opentelemetry::KeyValue {
    fn from(value: IdAttr) -> Self {
        value.key_value()
    }
}

/// Name of the host.
#[derive(Debug, Clone, PartialEq)]

pub struct NameAttr(String);


#[allow(deprecated)]
impl NameAttr {
    pub const KEY: &'static str = "host.name";

    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }


    pub fn key_value(self) -> ::opentelemetry::KeyValue {

        ::opentelemetry::KeyValue::new(Self::KEY, self.0)

    }
}

#[allow(deprecated)]
impl From<NameAttr> for ::opentelemetry::KeyValue {
    fn from(value: NameAttr) -> Self {
        value.key_value()
    }
}
