// Code generated by weaver. DO NOT EDIT.
#![allow(deprecated)]
#[derive(Clone, Debug)]
pub enum EntityAttr {
    Name(super::hostattr::NameAttr),
}

impl From<EntityAttr> for ::opentelemetry::KeyValue {
    fn from(value: EntityAttr) -> Self {
        match value {
            EntityAttr::Name(value) => ::opentelemetry::KeyValue::from(value),
        }
    }
}
/// A physical or virtual machine.
/// Identifies the entity: `host.id`.
/// Describes the entity: `host.name`.
#[derive(Clone, Debug)]
pub struct Entity {
    r#host_id: super::hostattr::IdAttr,
    options: ::smallvec::SmallVec<[EntityAttr; 1]>,
}

impl Entity {
    pub fn new(r#host_id: super::hostattr::IdAttr, options: impl IntoIterator<Item = EntityAttr>) -> Self {
        Self {
            r#host_id,
            options: options.into_iter().collect(),
        }
    }

    pub fn attributes(&self) -> impl Iterator<Item = ::opentelemetry::KeyValue> + '_ {
        ::std::iter::empty()
            .chain(::std::iter::once_with(move || ::opentelemetry::KeyValue::from(self.r#host_id.clone())))
            .chain(self.options.iter().cloned().map(::opentelemetry::KeyValue::from))
    }
}

impl From<Entity> for ::opentelemetry_sdk::Resource {
    fn from(value: Entity) -> Self {
        let attributes = [
            ::opentelemetry::KeyValue::from(value.r#host_id),
        ].into_iter().chain(value.options.into_iter().map(::opentelemetry::KeyValue::from));
        ::opentelemetry_sdk::Resource::builder_empty()
            .with_schema_url(attributes, super::SCHEMA_URL)
            .build()
    }
}
