// Generated by OpenTelemetry Weaver.
pub const SCHEMA_URL: &str = "https://example.com/schemas/no_namespace/1.0.0";
pub mod exceptionattr;
pub mod heartbeatattr;
pub mod hostattr;

pub mod tracer;
pub mod logger;
pub mod exceptionevent;
pub mod heartbeatspan;
pub mod hostentity;
