// Generated by OpenTelemetry Weaver.


pub const SCHEMA_URL: &str = "https://example.com/schemas/no_namespace/1.0.0";

pub mod exceptionattr {

    /// The exception message.
    #[derive(Debug, Clone, PartialEq)]

    pub struct MessageAttr(String);


    #[allow(deprecated)]
    impl MessageAttr {
        pub const KEY: &'static str = "exception.message";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<MessageAttr> for ::opentelemetry::KeyValue {
        fn from(value: MessageAttr) -> Self {
            value.key_value()
        }
    }

    /// The type of the exception.
    #[derive(Debug, Clone, PartialEq)]

    pub struct TypeAttr(String);


    #[allow(deprecated)]
    impl TypeAttr {
        pub const KEY: &'static str = "exception.type";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<TypeAttr> for ::opentelemetry::KeyValue {
        fn from(value: TypeAttr) -> Self {
            value.key_value()
        }
    }

}

pub mod heartbeatattr {

    /// Sequence number of the heartbeat.
    #[derive(Debug, Clone, PartialEq)]

    pub struct SequenceAttr(i64);


    #[allow(deprecated)]
    impl SequenceAttr {
        pub const KEY: &'static str = "heartbeat.sequence";

        pub fn new(value: i64) -> Self {
            Self(value)
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<SequenceAttr> for ::opentelemetry::KeyValue {
        fn from(value: SequenceAttr) -> Self {
            value.key_value()
        }
    }

    /// Name of the component that sent the heartbeat.
    #[derive(Debug, Clone, PartialEq)]

    pub struct SourceAttr(String);


    #[allow(deprecated)]
    impl SourceAttr {
        pub const KEY: &'static str = "heartbeat.source";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<SourceAttr> for ::opentelemetry::KeyValue {
        fn from(value: SourceAttr) -> Self {
            value.key_value()
        }
    }

}

pub mod hostattr {

    /// Unique identifier of the host.
    #[derive(Debug, Clone, PartialEq)]

    pub struct IdAttr(String);


    #[allow(deprecated)]
    impl IdAttr {
        pub const KEY: &'static str = "host.id";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<IdAttr> for ::opentelemetry::KeyValue {
        fn from(value: IdAttr) -> Self {
            value.key_value()
        }
    }

    /// Name of the host.
    #[derive(Debug, Clone, PartialEq)]

    pub struct NameAttr(String);


    #[allow(deprecated)]
    impl NameAttr {
        pub const KEY: &'static str = "host.name";

        pub fn new(value: impl Into<String>) -> Self {
            Self(value.into())
        }


        pub fn key_value(self) -> ::opentelemetry::KeyValue {

            ::opentelemetry::KeyValue::new(Self::KEY, self.0)

        }
    }

    #[allow(deprecated)]
    impl From<NameAttr> for ::opentelemetry::KeyValue {
        fn from(value: NameAttr) -> Self {
            value.key_value()
        }
    }

}



pub mod tracer;
pub mod logger;

pub mod exceptionevent;

pub mod heartbeatspan;

pub mod hostentity;
