// Code generated by weaver. DO NOT EDIT.

package hostattr

import "go.opentelemetry.io/otel/attribute"

// idKey is the attribute key of `host.id`.
const idKey = attribute.Key("host.id")

// IDAttr is a value of `host.id`.
//
// Unique identifier of the host.
type IDAttr struct{ value string }

// NewIDAttr returns a value of `host.id`.
func NewIDAttr(value string) IDAttr {
	return IDAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (IDAttr) Key() attribute.Key {
	return idKey
}

// KeyValue is the `host.id` attribute set to this value.
func (v IDAttr) KeyValue() attribute.KeyValue {
	return idKey.String(v.value)
}

// nameKey is the attribute key of `host.name`.
const nameKey = attribute.Key("host.name")

// NameAttr is a value of `host.name`.
//
// Name of the host.
type NameAttr struct{ value string }

// NewNameAttr returns a value of `host.name`.
func NewNameAttr(value string) NameAttr {
	return NameAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (NameAttr) Key() attribute.Key {
	return nameKey
}

// KeyValue is the `host.name` attribute set to this value.
func (v NameAttr) KeyValue() attribute.KeyValue {
	return nameKey.String(v.value)
}
