// Generated by OpenTelemetry Weaver.
/// Synthetic kept attribute.
#[derive(Debug, Clone, PartialEq)]
pub struct KeptAttr(String);

#[allow(deprecated)]
impl KeptAttr {
    pub const KEY: &'static str = "demo.kept";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<String> for KeptAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for KeptAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<KeptAttr> for ::opentelemetry::KeyValue {
    fn from(value: KeptAttr) -> Self {
        value.key_value()
    }
}
/// Synthetic mode.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum ModeAttr {
    /// Included mode.
    Kept,
}

#[allow(deprecated)]
impl ModeAttr {
    pub const KEY: &'static str = "demo.mode";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: String = match self {
            Self::Kept => "kept".into(),
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<ModeAttr> for ::opentelemetry::KeyValue {
    fn from(value: ModeAttr) -> Self {
        value.key_value()
    }
}
