// Generated by OpenTelemetry Weaver.
/// Synthetic kept attribute.
#[derive(Debug, Clone, PartialEq)]
pub struct KeptAttr(::opentelemetry::StringValue);

#[allow(deprecated)]
impl KeptAttr {
    pub const KEY: &'static str = "demo.kept";
}

#[allow(deprecated)]
impl From<::opentelemetry::StringValue> for KeptAttr {
    #[inline]
    fn from(value: ::opentelemetry::StringValue) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<String> for KeptAttr {
    #[inline]
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl From<&'static str> for KeptAttr {
    #[inline]
    fn from(value: &'static str) -> Self {
        Self(value.into())
    }
}

#[allow(deprecated)]
impl AsRef<str> for KeptAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        self.0.as_str()
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for KeptAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<KeptAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: KeptAttr) -> Self {
        ::opentelemetry::KeyValue::new(KeptAttr::KEY, value.0)
    }
}

#[allow(deprecated)]
impl From<KeptAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: KeptAttr) -> Self {
        value.0.into()
    }
}
/// Synthetic mode.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum ModeAttr {
    /// Included mode.
    Kept,
}

#[allow(deprecated)]
impl ModeAttr {
    pub const KEY: &'static str = "demo.mode";
}

#[allow(deprecated)]
impl AsRef<str> for ModeAttr {
    #[inline]
    fn as_ref(&self) -> &str {
        match self {
            ModeAttr::Kept => "kept",
        }
    }
}

#[allow(deprecated)]
impl ::std::fmt::Display for ModeAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.write_str(self.as_ref())
    }
}

#[allow(deprecated)]
impl From<ModeAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: ModeAttr) -> Self {
        let value: &'static str = match value {
            ModeAttr::Kept => "kept",
        };
        ::opentelemetry::KeyValue::new(ModeAttr::KEY, value)
    }
}

#[allow(deprecated)]
impl From<ModeAttr> for ::opentelemetry::logs::AnyValue {
    #[inline]
    fn from(value: ModeAttr) -> Self {
        let value: &'static str = match value {
            ModeAttr::Kept => "kept",
        };
        value.into()
    }
}
