// Code generated by weaver. DO NOT EDIT.

// Package myapp is the root of the Go form of a semantic convention
// registry.
//
// It declares only SchemaURL, so importing it pulls in no OpenTelemetry API.
// The handles that carry it into telemetry, such as a Meter, live in
// packages of their own. Every name lives in a package scoped by its
// namespace and the kind of signal it describes: attributes become
// `<namespace>attr`, holding typed attribute values, metrics become
// `<namespace>metric`, holding typed instruments, spans become
// `<namespace>span`, holding typed span starters, and events become
// `<namespace>event`, holding typed event emitters. Identifiers drop the
// namespace prefix the package name already carries, and a signal package
// imports the `<namespace>attr` packages its signals need, never the
// reverse.
//
// # Packages
//
//   - [example.com/myappmeter]: the Meter every metric instrument is created from
//   - [example.com/myapptracer]: the Tracer that starts spans tied to the schema
//   - [example.com/myapplogger]: the Logger that emits events tied to the schema
//   - [example.com/myappattr]: `myapp.*` attributes
//   - [example.com/myappevent]: `myapp.*` events
//   - [example.com/myappmetric]: `myapp.*` metrics
//   - [example.com/myappspan]: `myapp.*` spans
package myapp
