// Code generated by weaver. DO NOT EDIT.

// Package myappmeter holds the Meter every metric instrument of the registry
// is created from, so everything the instruments record is tied to
// myapp.SchemaURL.
package myappmeter
