// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

package myappattr

import "go.opentelemetry.io/otel/attribute"

// requestURLKey is the attribute key of `myapp.request.url`.
const requestURLKey = attribute.Key("myapp.request.url")

// RequestURLAttr is a value of `myapp.request.url`.
//
// URL the request was sent to.
type RequestURLAttr struct{ value string }

// NewRequestURLAttr returns a value of `myapp.request.url`.
func NewRequestURLAttr(value string) RequestURLAttr {
	return RequestURLAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (RequestURLAttr) Key() attribute.Key {
	return requestURLKey
}

// KeyValue is the `myapp.request.url` attribute set to this value.
func (v RequestURLAttr) KeyValue() attribute.KeyValue {
	return requestURLKey.String(v.value)
}
