// Code generated by weaver. DO NOT EDIT.

// Package edgeevent is the Go form of the events named `edge.*`.
//
// Each event and event refinement has an Emit function that emits it as a
// log record through a semconvlogger.Logger, under the event's name and with
// no body. Required attributes are typed parameters, and the rest, the
// severity, and the timestamp are trailing options. A record the logger is
// not enabled for is never emitted. Identifiers omit the namespace prefix
// `edge.`, because the package name already carries it.
package edgeevent
