// Code generated by weaver. DO NOT EDIT.

package edgeevent

import (
	"context"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/log"

	"example.com/semconv/semconvlogger"
)

// UpstreamFailedOption sets an attribute, the severity, or the timestamp of
// an event EmitUpstreamFailed emits.
type UpstreamFailedOption interface {
	upstreamFailedOption(record *log.Record)
}

type upstreamFailedEventSeverity struct{ v log.Severity }

func (o upstreamFailedEventSeverity) upstreamFailedOption(record *log.Record) {
	record.SetSeverity(o.v)
}

// WithUpstreamFailedSeverity sets the severity of the event, in place of
// log.SeverityInfo.
func WithUpstreamFailedSeverity(severity log.Severity) UpstreamFailedOption {
	return upstreamFailedEventSeverity{v: severity}
}

type upstreamFailedEventTimestamp struct{ v time.Time }

func (o upstreamFailedEventTimestamp) upstreamFailedOption(record *log.Record) {
	record.SetTimestamp(o.v)
}

// WithUpstreamFailedTimestamp sets the time the event occurred. Without it
// the event carries only the time it was observed.
func WithUpstreamFailedTimestamp(timestamp time.Time) UpstreamFailedOption {
	return upstreamFailedEventTimestamp{v: timestamp}
}

type upstreamFailedEventServerAddress struct{ v string }

func (o upstreamFailedEventServerAddress) upstreamFailedOption(record *log.Record) {
	record.AddAttributes(attribute.String("server.address", o.v))
}

// WithUpstreamFailedServerAddress sets `server.address` on the event.
func WithUpstreamFailedServerAddress(v string) UpstreamFailedOption {
	return upstreamFailedEventServerAddress{v: v}
}

// EmitUpstreamFailed emits the `edge.upstream.failed` event through logger.
// It is skipped when logger is not enabled for it, and the zero logger emits
// nothing.
//
// A request to an upstream server failed.
func EmitUpstreamFailed(ctx context.Context, logger semconvlogger.Logger, errorType string, opts ...UpstreamFailedOption) {
	var record log.Record
	record.SetEventName("edge.upstream.failed")
	record.SetSeverity(log.SeverityInfo)
	record.AddAttributes(
		attribute.String("error.type", errorType),
	)
	for _, opt := range opts {
		opt.upstreamFailedOption(&record)
	}
	if !logger.LogLogger().Enabled(ctx, log.EnabledParameters{Severity: record.Severity(), EventName: record.EventName()}) {
		return
	}
	logger.LogLogger().Emit(ctx, record)
}
