// Code generated by weaver. DO NOT EDIT.

package myappattr

import "go.opentelemetry.io/otel/attribute"

// taskCancelledKey is the attribute key of `myapp.task.cancelled`.
const taskCancelledKey = attribute.Key("myapp.task.cancelled")

// TaskCancelledAttr is a value of `myapp.task.cancelled`.
//
// Whether the task was cancelled.
type TaskCancelledAttr struct{ value bool }

// NewTaskCancelledAttr returns a value of `myapp.task.cancelled`.
func NewTaskCancelledAttr(value bool) TaskCancelledAttr {
	return TaskCancelledAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskCancelledAttr) Key() attribute.Key {
	return taskCancelledKey
}

// KeyValue is the `myapp.task.cancelled` attribute set to this value.
func (v TaskCancelledAttr) KeyValue() attribute.KeyValue {
	return taskCancelledKey.Bool(v.value)
}

// taskFlagsKey is the attribute key of `myapp.task.flags`.
const taskFlagsKey = attribute.Key("myapp.task.flags")

// TaskFlagsAttr is a value of `myapp.task.flags`.
//
// Feature flags evaluated for the task.
type TaskFlagsAttr struct{ value []bool }

// NewTaskFlagsAttr returns a value of `myapp.task.flags`.
func NewTaskFlagsAttr(value ...bool) TaskFlagsAttr {
	return TaskFlagsAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskFlagsAttr) Key() attribute.Key {
	return taskFlagsKey
}

// KeyValue is the `myapp.task.flags` attribute set to this value.
func (v TaskFlagsAttr) KeyValue() attribute.KeyValue {
	return taskFlagsKey.BoolSlice(v.value)
}

// taskIDKey is the attribute key of `myapp.task.id`.
const taskIDKey = attribute.Key("myapp.task.id")

// TaskIDAttr is a value of `myapp.task.id`.
//
// Unique identifier of the task.
//
// The identifier is assigned by the scheduler and stays stable across
// retries.
type TaskIDAttr struct{ value string }

// NewTaskIDAttr returns a value of `myapp.task.id`.
func NewTaskIDAttr(value string) TaskIDAttr {
	return TaskIDAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskIDAttr) Key() attribute.Key {
	return taskIDKey
}

// KeyValue is the `myapp.task.id` attribute set to this value.
func (v TaskIDAttr) KeyValue() attribute.KeyValue {
	return taskIDKey.String(v.value)
}

// taskOwnerKey is the attribute key of `myapp.task.owner`.
//
// Deprecated: Replaced by `auth.user.id`.
const taskOwnerKey = attribute.Key("myapp.task.owner")

// TaskOwnerAttr is a value of `myapp.task.owner`.
//
// Owner of the task.
//
// Deprecated: Replaced by `auth.user.id`.
type TaskOwnerAttr struct{ value string }

// NewTaskOwnerAttr returns a value of `myapp.task.owner`.
//
// Deprecated: Replaced by `auth.user.id`.
func NewTaskOwnerAttr(value string) TaskOwnerAttr {
	return TaskOwnerAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskOwnerAttr) Key() attribute.Key {
	return taskOwnerKey
}

// KeyValue is the `myapp.task.owner` attribute set to this value.
func (v TaskOwnerAttr) KeyValue() attribute.KeyValue {
	return taskOwnerKey.String(v.value)
}

// taskProgressKey is the attribute key of `myapp.task.progress`.
const taskProgressKey = attribute.Key("myapp.task.progress")

// TaskProgressAttr is a value of `myapp.task.progress`.
//
// Fraction of the task that has completed, between 0 and 1.
type TaskProgressAttr struct{ value float64 }

// NewTaskProgressAttr returns a value of `myapp.task.progress`.
func NewTaskProgressAttr(value float64) TaskProgressAttr {
	return TaskProgressAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskProgressAttr) Key() attribute.Key {
	return taskProgressKey
}

// KeyValue is the `myapp.task.progress` attribute set to this value.
func (v TaskProgressAttr) KeyValue() attribute.KeyValue {
	return taskProgressKey.Float64(v.value)
}

// taskRetriesKey is the attribute key of `myapp.task.retries`.
const taskRetriesKey = attribute.Key("myapp.task.retries")

// TaskRetriesAttr is a value of `myapp.task.retries`.
//
// Number of times the task was retried.
type TaskRetriesAttr struct{ value int }

// NewTaskRetriesAttr returns a value of `myapp.task.retries`.
func NewTaskRetriesAttr(value int) TaskRetriesAttr {
	return TaskRetriesAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskRetriesAttr) Key() attribute.Key {
	return taskRetriesKey
}

// KeyValue is the `myapp.task.retries` attribute set to this value.
func (v TaskRetriesAttr) KeyValue() attribute.KeyValue {
	return taskRetriesKey.Int(v.value)
}

// taskShardIdsKey is the attribute key of `myapp.task.shard_ids`.
const taskShardIdsKey = attribute.Key("myapp.task.shard_ids")

// TaskShardIdsAttr is a value of `myapp.task.shard_ids`.
//
// Shards the task touched.
type TaskShardIdsAttr struct{ value []int }

// NewTaskShardIdsAttr returns a value of `myapp.task.shard_ids`.
func NewTaskShardIdsAttr(value ...int) TaskShardIdsAttr {
	return TaskShardIdsAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskShardIdsAttr) Key() attribute.Key {
	return taskShardIdsKey
}

// KeyValue is the `myapp.task.shard_ids` attribute set to this value.
func (v TaskShardIdsAttr) KeyValue() attribute.KeyValue {
	return taskShardIdsKey.IntSlice(v.value)
}

// taskStateKey is the attribute key of `myapp.task.state`.
const taskStateKey = attribute.Key("myapp.task.state")

// TaskStateAttr is a value of `myapp.task.state`.
//
// Current state of the task.
type TaskStateAttr struct{ value string }

// Key is the attribute key, for filters and views that need it.
func (TaskStateAttr) Key() attribute.Key {
	return taskStateKey
}

// KeyValue is the `myapp.task.state` attribute set to this value.
func (v TaskStateAttr) KeyValue() attribute.KeyValue {
	return taskStateKey.String(v.value)
}

var (
	// TaskStateQueued is the "queued" member of `myapp.task.state`.
	//
	// The task is waiting to run.
	TaskStateQueued = TaskStateAttr{value: "queued"}

	// TaskStateRunning is the "running" member of `myapp.task.state`.
	//
	// The task is running.
	//
	// A task stays running until it finishes or is cancelled.
	TaskStateRunning = TaskStateAttr{value: "running"}

	// TaskStatePaused is the "paused" member of `myapp.task.state`.
	//
	// The task was paused.
	//
	// Deprecated: Paused tasks are reported as queued.
	TaskStatePaused = TaskStateAttr{value: "paused"}
)

// taskTagsKey is the attribute key of `myapp.task.tags`.
const taskTagsKey = attribute.Key("myapp.task.tags")

// TaskTagsAttr is a value of `myapp.task.tags`.
//
// Tags attached to the task.
type TaskTagsAttr struct{ value []string }

// NewTaskTagsAttr returns a value of `myapp.task.tags`.
func NewTaskTagsAttr(value ...string) TaskTagsAttr {
	return TaskTagsAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskTagsAttr) Key() attribute.Key {
	return taskTagsKey
}

// KeyValue is the `myapp.task.tags` attribute set to this value.
func (v TaskTagsAttr) KeyValue() attribute.KeyValue {
	return taskTagsKey.StringSlice(v.value)
}

// taskWeightsKey is the attribute key of `myapp.task.weights`.
const taskWeightsKey = attribute.Key("myapp.task.weights")

// TaskWeightsAttr is a value of `myapp.task.weights`.
//
// Scheduling weights applied to the task.
type TaskWeightsAttr struct{ value []float64 }

// NewTaskWeightsAttr returns a value of `myapp.task.weights`.
func NewTaskWeightsAttr(value ...float64) TaskWeightsAttr {
	return TaskWeightsAttr{value: value}
}

// Key is the attribute key, for filters and views that need it.
func (TaskWeightsAttr) Key() attribute.Key {
	return taskWeightsKey
}

// KeyValue is the `myapp.task.weights` attribute set to this value.
func (v TaskWeightsAttr) KeyValue() attribute.KeyValue {
	return taskWeightsKey.Float64Slice(v.value)
}
