// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

// Package acmesemconv is the root of the Go form of a semantic convention
// registry.
//
// Use these packages for names the upstream registry does not define.
//
// It declares nothing itself. Every name lives in a package scoped by its
// namespace and the kind of signal it describes: attributes become
// `<namespace>attr`, holding typed attribute values, and metrics become
// `<namespace>metric`, holding typed instruments. Identifiers drop the
// namespace prefix the package name already carries, and a
// `<namespace>metric` package imports the `<namespace>attr` packages its
// metrics need, never the reverse.
//
// # Packages
//
//   - [example.com/acme/internal/acmesemconv/billingattr]: `acme.billing.*` and `billing.*` attributes
//   - [example.com/acme/internal/acmesemconv/billingmetric]: `acme.billing.*` metrics
//   - [example.com/acme/internal/acmesemconv/myappattr]: `myapp.*` attributes
package acmesemconv
