// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

// Package acmesemconv is the root of the Go form of a semantic convention
// registry.
//
// Use these packages for names the upstream registry does not define.
//
// It declares only SchemaURL, so importing it pulls in no OpenTelemetry API.
// The handles that carry it into telemetry, such as a Meter, live in
// packages of their own. Every name lives in a package scoped by its
// namespace and the kind it describes: attributes become `<namespace>attr`,
// holding typed attribute values, metrics become `<namespace>metric`,
// holding typed instruments, spans become `<namespace>span`, holding typed
// span starters, events become `<namespace>event`, holding typed event
// emitters, and entities become `<namespace>entity`, holding typed entity
// value types. Identifiers drop the namespace prefix the package name
// already carries, and a package imports the `<namespace>attr` packages its
// names need, never the reverse.
//
// # Packages
//
//   - [example.com/acme/internal/acmesemconv/acmesemconvmeter]: the Meter every metric instrument is created from
//   - [example.com/acme/internal/acmesemconv/billingattr]: `acme.billing.*` and `billing.*` attributes
//   - [example.com/acme/internal/acmesemconv/billingmetric]: `acme.billing.*` metrics
//   - [example.com/acme/internal/acmesemconv/myappattr]: `myapp.*` attributes
package acmesemconv
