// Code generated by weaver from model/. DO NOT EDIT.
// Run `mise run generate` after changing a convention.

package acmesemconv

// SchemaURL is the schema URL of the registry these packages are generated
// from.
const SchemaURL = "https://example.com/schemas/params/1.0.0"
