// Code generated by weaver. DO NOT EDIT.

// Package semconv is the root of the Go form of a semantic convention
// registry.
//
// It declares nothing itself. Every name lives in a package scoped by its
// namespace and the kind of signal it describes: attributes become
// `<namespace>attr`, holding typed attribute values, and metrics become
// `<namespace>metric`, holding typed instruments. Identifiers drop the
// namespace prefix the package name already carries, and a
// `<namespace>metric` package imports the `<namespace>attr` packages its
// metrics need, never the reverse.
//
// # Packages
//
//   - [example.com/semconv/authattr]: `auth.*` attributes
//   - [example.com/semconv/authmetric]: `auth.*` metrics
//   - [example.com/semconv/myappattr]: `myapp.*` attributes
//   - [example.com/semconv/myappmetric]: `myapp.*` metrics
package semconv
