// Code generated by weaver. DO NOT EDIT.

package semconv

// SchemaURL is the schema URL of the registry these packages are generated
// from.
const SchemaURL = "https://example.com/schemas/metrics/1.0.0"
