// Generated by OpenTelemetry Weaver.
/// Synthetic integer limits.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum BoundaryAttr {
    /// Lowest signed 64-bit integer.
    Minimum,
    /// Highest signed 64-bit integer.
    Maximum,
}

#[allow(deprecated)]
impl BoundaryAttr {
    pub const KEY: &'static str = "demo.boundary";
}

#[allow(deprecated)]
impl ::std::fmt::Display for BoundaryAttr {
    #[inline]
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let value: i64 = match self {
            BoundaryAttr::Minimum => -9223372036854775808,
            BoundaryAttr::Maximum => 9223372036854775807,
        };
        ::std::fmt::Display::fmt(&value, formatter)
    }
}

#[allow(deprecated)]
impl From<BoundaryAttr> for ::opentelemetry::KeyValue {
    #[inline]
    fn from(value: BoundaryAttr) -> Self {
        let value: i64 = match value {
            BoundaryAttr::Minimum => -9223372036854775808,
            BoundaryAttr::Maximum => 9223372036854775807,
        };
        ::opentelemetry::KeyValue::new(BoundaryAttr::KEY, value)
    }
}
