// Code generated by weaver. DO NOT EDIT.

// Package semconv is the root of the Go form of a semantic convention
// registry.
//
// It declares only SchemaURL, so importing it pulls in no OpenTelemetry API.
// The handles that carry it into telemetry, such as a Meter, live in
// packages of their own. Every name lives in a package scoped by its
// namespace and the kind it describes: attributes become `<namespace>attr`,
// holding typed attribute values, metrics become `<namespace>metric`,
// holding typed instruments, spans become `<namespace>span`, holding typed
// span starters, events become `<namespace>event`, holding typed event
// emitters, and entities become `<namespace>entity`, holding typed entity
// value types. Identifiers drop the namespace prefix the package name
// already carries, and a package imports the `<namespace>attr` packages its
// names need, never the reverse.
//
// # Packages
//
//   - [example.com/semconv/semconvtracer]: the Tracer that starts spans tied to the schema
//   - [example.com/semconv/semconvlogger]: the Logger that emits events tied to the schema
//   - [example.com/semconv/exceptionattr]: `exception.*` attributes
//   - [example.com/semconv/exceptionevent]: `exception` events
//   - [example.com/semconv/heartbeatattr]: `heartbeat.*` attributes
//   - [example.com/semconv/heartbeatspan]: `heartbeat` spans
//   - [example.com/semconv/hostattr]: `host.*` attributes
//   - [example.com/semconv/hostentity]: `host` entities
package semconv
