// Code generated by weaver. DO NOT EDIT.

// Package myappentity is the Go form of the entities named `myapp.*`.
//
// Each entity and entity refinement is a value type built by its New
// constructor from the identity and description attributes the convention
// requires, with the rest as trailing options. Attributes passed to the
// constructor are the only ones the value carries: Attributes returns them,
// and Resource builds a *resource.Resource tied to the registry's schema
// from them. Identifiers omit the namespace prefix `myapp.`, because the
// package name already carries it.
package myappentity
