// Code generated by weaver. DO NOT EDIT.

package myappentity

import (
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/sdk/resource"

	"example.com/semconv/myappattr"

	"example.com/semconv"
)

// HostEntityAttr is an attribute NewHostEntity accepts in addition to the
// ones it requires.
type HostEntityAttr interface {
	hostEntityAttr() attribute.KeyValue
}

type hostEntityHostCPUCount struct{ v myappattr.HostCPUCountAttr }

func (o hostEntityHostCPUCount) hostEntityAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithHostEntityHostCPUCount sets `myapp.host.cpu.count` on the entity.
//
// Opt-in: the convention records it only when a user asks for it.
func WithHostEntityHostCPUCount(v myappattr.HostCPUCountAttr) HostEntityAttr {
	return hostEntityHostCPUCount{v: v}
}

type hostEntityHostType struct{ v myappattr.HostTypeAttr }

func (o hostEntityHostType) hostEntityAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithHostEntityHostType sets `myapp.host.type` on the entity.
func WithHostEntityHostType(v myappattr.HostTypeAttr) HostEntityAttr {
	return hostEntityHostType{v: v}
}

// HostEntity is the `myapp.host` entity. The zero HostEntity has no
// attributes.
//
// A host running the application.
//
// Identified by its name across its lifetime.
//
// Identifies the entity: `myapp.host.name`.
//
// Describes the entity: `myapp.host.cpu.count`, `myapp.host.type`.
type HostEntity struct{ attrs []attribute.KeyValue }

// NewHostEntity builds a HostEntity from its required attributes and any
// given options.
func NewHostEntity(myappHostName myappattr.HostNameAttr, opts ...HostEntityAttr) HostEntity {
	attrs := make([]attribute.KeyValue, 0, 1+len(opts))
	attrs = append(attrs, myappHostName.KeyValue())
	for _, opt := range opts {
		attrs = append(attrs, opt.hostEntityAttr())
	}
	return HostEntity{attrs: attrs}
}

// Attributes returns a copy of the entity's attributes. The zero HostEntity
// returns none.
func (e HostEntity) Attributes() []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(e.attrs))
	copy(out, e.attrs)
	return out
}

// Resource returns a *resource.Resource built from the entity's attributes,
// tied to semconv.SchemaURL.
func (e HostEntity) Resource() *resource.Resource {
	return resource.NewWithAttributes(semconv.SchemaURL, e.attrs...)
}

// HostWorkerEntityAttr is an attribute NewHostWorkerEntity accepts in
// addition to the ones it requires.
type HostWorkerEntityAttr interface {
	hostWorkerEntityAttr() attribute.KeyValue
}

type hostWorkerEntityHostCPUCount struct{ v myappattr.HostCPUCountAttr }

func (o hostWorkerEntityHostCPUCount) hostWorkerEntityAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithHostWorkerEntityHostCPUCount sets `myapp.host.cpu.count` on the
// entity.
//
// Opt-in: the convention records it only when a user asks for it.
func WithHostWorkerEntityHostCPUCount(v myappattr.HostCPUCountAttr) HostWorkerEntityAttr {
	return hostWorkerEntityHostCPUCount{v: v}
}

type hostWorkerEntityHostType struct{ v myappattr.HostTypeAttr }

func (o hostWorkerEntityHostType) hostWorkerEntityAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithHostWorkerEntityHostType sets `myapp.host.type` on the entity.
func WithHostWorkerEntityHostType(v myappattr.HostTypeAttr) HostWorkerEntityAttr {
	return hostWorkerEntityHostType{v: v}
}

// HostWorkerEntity is the `myapp.host.worker` entity, a refinement of
// `myapp.host`. The zero HostWorkerEntity has no attributes.
//
// A host dedicated to running worker processes.
//
// Identified by its name across its lifetime.
//
// Identifies the entity: `myapp.host.name`.
//
// Describes the entity: `myapp.host.cpu.count`, `myapp.host.role`,
// `myapp.host.type`.
type HostWorkerEntity struct{ attrs []attribute.KeyValue }

// NewHostWorkerEntity builds a HostWorkerEntity from its required attributes
// and any given options.
func NewHostWorkerEntity(myappHostName myappattr.HostNameAttr, myappHostRole myappattr.HostRoleAttr, opts ...HostWorkerEntityAttr) HostWorkerEntity {
	attrs := make([]attribute.KeyValue, 0, 2+len(opts))
	attrs = append(attrs, myappHostName.KeyValue())
	attrs = append(attrs, myappHostRole.KeyValue())
	for _, opt := range opts {
		attrs = append(attrs, opt.hostWorkerEntityAttr())
	}
	return HostWorkerEntity{attrs: attrs}
}

// Attributes returns a copy of the entity's attributes. The zero
// HostWorkerEntity returns none.
func (e HostWorkerEntity) Attributes() []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(e.attrs))
	copy(out, e.attrs)
	return out
}

// Resource returns a *resource.Resource built from the entity's attributes,
// tied to semconv.SchemaURL.
func (e HostWorkerEntity) Resource() *resource.Resource {
	return resource.NewWithAttributes(semconv.SchemaURL, e.attrs...)
}

// QueueEntityAttr is an attribute NewQueueEntity accepts in addition to the
// ones it requires.
type QueueEntityAttr interface {
	queueEntityAttr() attribute.KeyValue
}

type queueEntityQueueSize struct{ v myappattr.QueueSizeAttr }

func (o queueEntityQueueSize) queueEntityAttr() attribute.KeyValue {
	return o.v.KeyValue()
}

// WithQueueEntityQueueSize sets `myapp.queue.size` on the entity.
func WithQueueEntityQueueSize(v myappattr.QueueSizeAttr) QueueEntityAttr {
	return queueEntityQueueSize{v: v}
}

// QueueEntity is the `myapp.queue` entity. The zero QueueEntity has no
// attributes.
//
// A queue of tasks.
//
// Identifies the entity: `myapp.queue.name`.
//
// Describes the entity: `myapp.queue.size`.
type QueueEntity struct{ attrs []attribute.KeyValue }

// NewQueueEntity builds a QueueEntity from its required attributes and any
// given options.
func NewQueueEntity(myappQueueName myappattr.QueueNameAttr, opts ...QueueEntityAttr) QueueEntity {
	attrs := make([]attribute.KeyValue, 0, 1+len(opts))
	attrs = append(attrs, myappQueueName.KeyValue())
	for _, opt := range opts {
		attrs = append(attrs, opt.queueEntityAttr())
	}
	return QueueEntity{attrs: attrs}
}

// Attributes returns a copy of the entity's attributes. The zero QueueEntity
// returns none.
func (e QueueEntity) Attributes() []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(e.attrs))
	copy(out, e.attrs)
	return out
}

// Resource returns a *resource.Resource built from the entity's attributes,
// tied to semconv.SchemaURL.
func (e QueueEntity) Resource() *resource.Resource {
	return resource.NewWithAttributes(semconv.SchemaURL, e.attrs...)
}
