// Generated by OpenTelemetry Weaver.
/// Assurance level of the authentication.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum LevelAttr {
    /// Single factor.
    Low,
    /// Multiple factors.
    High,
}

#[allow(deprecated)]
impl LevelAttr {
    pub const KEY: &'static str = "auth.level";
}

#[allow(deprecated)]
impl From<LevelAttr> for ::opentelemetry::KeyValue {
    fn from(value: LevelAttr) -> Self {
        let value: i64 = match value {
            LevelAttr::Low => 1,
            LevelAttr::High => 2,
        };
        ::opentelemetry::KeyValue::new(LevelAttr::KEY, value)
    }
}
/// How the user was authenticated.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum MethodAttr {
    /// A password was checked.
    Password,
    /// A bearer token was checked.
    Token,
}

#[allow(deprecated)]
impl MethodAttr {
    pub const KEY: &'static str = "auth.method";
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::KeyValue {
    fn from(value: MethodAttr) -> Self {
        let value: String = match value {
            MethodAttr::Password => "password".into(),
            MethodAttr::Token => "token".into(),
        };
        ::opentelemetry::KeyValue::new(MethodAttr::KEY, value)
    }
}
/// Identifier of the authenticated user.
#[derive(Debug, Clone, PartialEq)]
pub struct UserIdAttr(String);

#[allow(deprecated)]
impl UserIdAttr {
    pub const KEY: &'static str = "auth.user.id";
}

#[allow(deprecated)]
impl From<String> for UserIdAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for UserIdAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<UserIdAttr> for ::opentelemetry::KeyValue {
    fn from(value: UserIdAttr) -> Self {
        ::opentelemetry::KeyValue::new(UserIdAttr::KEY, value.0)
    }
}
