// Generated by OpenTelemetry Weaver.
/// Assurance level of the authentication.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum LevelAttr {
    /// Single factor.
    Low,
    /// Multiple factors.
    High,
}

#[allow(deprecated)]
impl LevelAttr {
    pub const KEY: &'static str = "auth.level";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: i64 = match self {
            Self::Low => 1,
            Self::High => 2,
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<LevelAttr> for ::opentelemetry::KeyValue {
    fn from(value: LevelAttr) -> Self {
        value.key_value()
    }
}
/// How the user was authenticated.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum MethodAttr {
    /// A password was checked.
    Password,
    /// A bearer token was checked.
    Token,
}

#[allow(deprecated)]
impl MethodAttr {
    pub const KEY: &'static str = "auth.method";

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        let value: String = match self {
            Self::Password => "password".into(),
            Self::Token => "token".into(),
        };
        ::opentelemetry::KeyValue::new(Self::KEY, value)
    }
}

#[allow(deprecated)]
impl From<MethodAttr> for ::opentelemetry::KeyValue {
    fn from(value: MethodAttr) -> Self {
        value.key_value()
    }
}
/// Identifier of the authenticated user.
#[derive(Debug, Clone, PartialEq)]
pub struct UserIdAttr(String);

#[allow(deprecated)]
impl UserIdAttr {
    pub const KEY: &'static str = "auth.user.id";
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn key_value(self) -> ::opentelemetry::KeyValue {
        ::opentelemetry::KeyValue::new(Self::KEY, self.0)
    }
}

#[allow(deprecated)]
impl From<UserIdAttr> for ::opentelemetry::KeyValue {
    fn from(value: UserIdAttr) -> Self {
        value.key_value()
    }
}
