// Generated by OpenTelemetry Weaver.
/// Who assigned the task.
///
/// The scheduler sets it on every task it passes along to `myapp.task.state`. Workers never set it themselves.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskAssignedByAttr(String);

#[allow(deprecated)]
impl TaskAssignedByAttr {
    pub const KEY: &'static str = "myapp.task.assigned_by";
}

#[allow(deprecated)]
impl From<String> for TaskAssignedByAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for TaskAssignedByAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<TaskAssignedByAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskAssignedByAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskAssignedByAttr::KEY, value.0)
    }
}
/// Whether the task was cancelled.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskCancelledAttr(bool);

#[allow(deprecated)]
impl TaskCancelledAttr {
    pub const KEY: &'static str = "myapp.task.cancelled";
}

#[allow(deprecated)]
impl From<bool> for TaskCancelledAttr {
    fn from(value: bool) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskCancelledAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskCancelledAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskCancelledAttr::KEY, value.0)
    }
}
/// Tests Rust string literals.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskEscapedAttr {
    /// Escaped text.
    Quoted,
}

#[allow(deprecated)]
impl TaskEscapedAttr {
    pub const KEY: &'static str = "myapp.task.escaped";
}

#[allow(deprecated)]
impl From<TaskEscapedAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskEscapedAttr) -> Self {
        let value: String = match value {
            TaskEscapedAttr::Quoted => "quote\" slash\\ newline\n tab\t backspace\u{0008} formfeed\u{000c} null\u{0000} snowman☃".into(),
        };
        ::opentelemetry::KeyValue::new(TaskEscapedAttr::KEY, value)
    }
}
/// Feature flags evaluated for the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskFlagsAttr(Vec<bool>);

#[allow(deprecated)]
impl TaskFlagsAttr {
    pub const KEY: &'static str = "myapp.task.flags";
}

#[allow(deprecated)]
impl From<Vec<bool>> for TaskFlagsAttr {
    fn from(value: Vec<bool>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskFlagsAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskFlagsAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskFlagsAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::Bool(value.0)))
    }
}
/// Unique identifier of the task.
///
/// The identifier is assigned by the scheduler and stays stable across retries.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskIdAttr(String);

#[allow(deprecated)]
impl TaskIdAttr {
    pub const KEY: &'static str = "myapp.task.id";
}

#[allow(deprecated)]
impl From<String> for TaskIdAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for TaskIdAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<TaskIdAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskIdAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskIdAttr::KEY, value.0)
    }
}
/// Lane the task was scheduled in.
#[deprecated(note = "Lanes were replaced by priorities.")]
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskLaneAttr {
    /// The fast lane.
    #[deprecated(note = "Lanes were replaced by priorities.")]
    Fast,
    /// The slow lane.
    #[deprecated(note = "Every task runs in the fast lane.")]
    Slow,
}

#[allow(deprecated)]
impl TaskLaneAttr {
    pub const KEY: &'static str = "myapp.task.lane";
}

#[allow(deprecated)]
impl From<TaskLaneAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskLaneAttr) -> Self {
        let value: String = match value {
            TaskLaneAttr::Fast => "fast".into(),
            TaskLaneAttr::Slow => "slow".into(),
        };
        ::opentelemetry::KeyValue::new(TaskLaneAttr::KEY, value)
    }
}
/// Owner of the task.
#[deprecated(note = "Replaced by `auth.user.id`.")]
#[derive(Debug, Clone, PartialEq)]
pub struct TaskOwnerAttr(String);

#[allow(deprecated)]
impl TaskOwnerAttr {
    pub const KEY: &'static str = "myapp.task.owner";
}

#[allow(deprecated)]
impl From<String> for TaskOwnerAttr {
    fn from(value: String) -> Self {
        Self(value)
    }
}
#[allow(deprecated)]
impl From<&str> for TaskOwnerAttr {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

#[allow(deprecated)]
impl From<TaskOwnerAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskOwnerAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskOwnerAttr::KEY, value.0)
    }
}
/// Whether the scheduler may preempt the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskPreemptibleAttr {
    /// The scheduler may preempt the task.
    Allowed,
    /// The task runs to completion.
    Forbidden,
}

#[allow(deprecated)]
impl TaskPreemptibleAttr {
    pub const KEY: &'static str = "myapp.task.preemptible";
}

#[allow(deprecated)]
impl From<TaskPreemptibleAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskPreemptibleAttr) -> Self {
        let value: bool = match value {
            TaskPreemptibleAttr::Allowed => true,
            TaskPreemptibleAttr::Forbidden => false,
        };
        ::opentelemetry::KeyValue::new(TaskPreemptibleAttr::KEY, value)
    }
}
/// Fraction of the task that has completed, between 0 and 1.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskProgressAttr(f64);

#[allow(deprecated)]
impl TaskProgressAttr {
    pub const KEY: &'static str = "myapp.task.progress";
}

#[allow(deprecated)]
impl From<f64> for TaskProgressAttr {
    fn from(value: f64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskProgressAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskProgressAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskProgressAttr::KEY, value.0)
    }
}
/// Number of times the task was retried.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskRetriesAttr(i64);

#[allow(deprecated)]
impl TaskRetriesAttr {
    pub const KEY: &'static str = "myapp.task.retries";
}

#[allow(deprecated)]
impl From<i64> for TaskRetriesAttr {
    fn from(value: i64) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskRetriesAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskRetriesAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskRetriesAttr::KEY, value.0)
    }
}
/// Fraction of tasks whose telemetry is sampled.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskSampleRateAttr {
    /// One task in ten is sampled.
    Tenth,
    /// Every task is sampled.
    All,
}

#[allow(deprecated)]
impl TaskSampleRateAttr {
    pub const KEY: &'static str = "myapp.task.sample_rate";
}

#[allow(deprecated)]
impl From<TaskSampleRateAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskSampleRateAttr) -> Self {
        let value: f64 = match value {
            TaskSampleRateAttr::Tenth => 0.1_f64,
            TaskSampleRateAttr::All => 1_f64,
        };
        ::opentelemetry::KeyValue::new(TaskSampleRateAttr::KEY, value)
    }
}
/// Shards the task touched.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskShardIdsAttr(Vec<i64>);

#[allow(deprecated)]
impl TaskShardIdsAttr {
    pub const KEY: &'static str = "myapp.task.shard_ids";
}

#[allow(deprecated)]
impl From<Vec<i64>> for TaskShardIdsAttr {
    fn from(value: Vec<i64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskShardIdsAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskShardIdsAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskShardIdsAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::I64(value.0)))
    }
}
/// Current state of the task.
#[derive(Debug, Clone, PartialEq, Copy)]
pub enum TaskStateAttr {
    /// The task is waiting to run.
    Queued,
    /// The task is running.
    ///
    /// A task stays running until it finishes or is cancelled.
    Running,
    /// The task was paused.
    #[deprecated(note = "Paused tasks are reported as queued.")]
    Paused,
}

#[allow(deprecated)]
impl TaskStateAttr {
    pub const KEY: &'static str = "myapp.task.state";
}

#[allow(deprecated)]
impl From<TaskStateAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskStateAttr) -> Self {
        let value: String = match value {
            TaskStateAttr::Queued => "queued".into(),
            TaskStateAttr::Running => "running".into(),
            TaskStateAttr::Paused => "paused".into(),
        };
        ::opentelemetry::KeyValue::new(TaskStateAttr::KEY, value)
    }
}
/// Tags attached to the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskTagsAttr(Vec<String>);

#[allow(deprecated)]
impl TaskTagsAttr {
    pub const KEY: &'static str = "myapp.task.tags";
}

#[allow(deprecated)]
impl From<Vec<String>> for TaskTagsAttr {
    fn from(value: Vec<String>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskTagsAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskTagsAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskTagsAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::String(value.0.into_iter().map(Into::into).collect())))
    }
}
/// Scheduling weights applied to the task.
#[derive(Debug, Clone, PartialEq)]
pub struct TaskWeightsAttr(Vec<f64>);

#[allow(deprecated)]
impl TaskWeightsAttr {
    pub const KEY: &'static str = "myapp.task.weights";
}

#[allow(deprecated)]
impl From<Vec<f64>> for TaskWeightsAttr {
    fn from(value: Vec<f64>) -> Self {
        Self(value)
    }
}

#[allow(deprecated)]
impl From<TaskWeightsAttr> for ::opentelemetry::KeyValue {
    fn from(value: TaskWeightsAttr) -> Self {
        ::opentelemetry::KeyValue::new(TaskWeightsAttr::KEY, ::opentelemetry::Value::Array(::opentelemetry::Array::F64(value.0)))
    }
}
